### ISSUE TITLE
Pod creation flood when running on k8s

### ISSUE THREAD

**Issue by Vlaaaaaaad** [zalando/zalenium#441] opened 2018-02-15 11:15 UTC
Issue created after discussion on [Slack](https://seleniumhq.slack.com/archives/C99KY79EK/p1518689803000467) and Gitter.

### Expected Behavior

When running a Selenium test on Kubernetes that requests 300 instances of Firefox( several scenarios running in parallel), I expected 300 pods to be created to serve that.

### Actual Behavior

Significantly more pods are are created to serve the request. The `maxDockerSeleniumContainers` limit was set to 600 and it was hit( the limit seemed to work and Zalenium reported stopping the requests due to the limit).

The following message can be seen in the logs for Zalenium hub:
```
INFO - [DS] Request has waited 30 attempts for a node, something went wrong with the previous attempts, creating a new node for { ... }
```

### Investigation and write-up

Zalenium is very... eager to schedule pods. When running a test that requests 10 pods, k8s would schedule 4, have no more space, cluster-autoscaler would create a new node that would join the cluster in a couple minutes and then the 6 pending pods would be scheduled. Meanwhile Zalenium would keep requesting new 6 pods over and over again. This leads to 20-something pods for a test that requested 10.

To confirm this an over-powered cluster was created where there were no issues with the 10-pod scheduling and subsequent cleanup. There were 10 pods requested, 10 were created, tests ran, pods were deleted. Perfect.

The same problem comes back when requesting more pods. At 300 pods, even on a larger cluster, scheduling and launching all the pods takes a while and Zalenium keeps requesting pods. For a request of 300 pods, Zalenium tries to create more than 600 pods. 

Looking a bit into the code points to this being hardcoded at
https://github.com/zalando/zalenium/blob/09f22a4375fd3f567303ec2017be7f31ba58bede/src/main/java/de/zalando/ep/zalenium/proxy/DockerSeleniumStarterRemoteProxy.java#L374 

I see no way to increase a timeout or the 30 attempts value. Something like "_OK Zalenium, you requested pods, just wait like 2 minutes for them to be ready_" would be a great addition.

### Env
**Zalenium Image Version**: 3

**Kubernetes Version**: 1.8.6, cluster created by kops, running on AWS

**Command to start Zalenium**:  installed on the cluster by deploying the helm chart with the following `values.yaml`:
```
hub:
  ## The repository and image
  ## ref: https://hub.docker.com/r/selenium/hub/
  image: "dosel/zalenium"

  ## The tag for the image
  ## ref: https://hub.docker.com/r/selenium/hub/tags/
  tag: "3"

  ## Specify a imagePullPolicy
  ## ref: http://kubernetes.io/docs/user-guide/images/#pre-pulling-images
  pullPolicy: "IfNotPresent"

  ## The port which the hub listens on
  port: 4444

  ## Timeout for probe Hub readiness via HTTP request on Hub console
  readinessTimeout: 10000

  ## Set the JAVA_OPTS environment variable
  ## If you find your selenium hub is OOMKilled, try adding -XX:+UseSerialGC
  javaOpts: "-Xmx18096m -XX:+UseSerialGC"

  ## Set the SE_OPTS environment variable
  ## ref: http://www.seleniumhq.org/docs/07_selenium_grid.jsp#node-configuration
  # seOpts:

  ## Defining a JMX port will open the port on the container, however, it
  ## requires additional javaOpts, ie
  ## javaOpts: >
  ##   -Dcom.sun.management.jmxremote.port=4000
  ##   -Dcom.sun.management.jmxremote.authenticate=false
  ##   -Dcom.sun.management.jmxremote.ssl=false
  ## ref: http://openjdk.java.net/groups/jmx/
  # jmxPort: 4000

  ## Use persistent storage or local?
  persistentVolumesEnabled: false
  localVolumesRoot: '/tmp'

  ## Configure resource requests and limits
  ## ref: http://kubernetes.io/docs/user-guide/compute-resources/
  resources:
    limits:
      cpu: "20"
      memory: "48Gi"

  ## The type of service to create
  ##   Values: ClusterIP, NodePort, LoadBalancer, or ExternalName
  ## ref: https://kubernetes.io/docs/user-guide/services/
  serviceType: "NodePort"

  ## Control where client requests go, to the same pod or round-robin
  ##   Values: ClientIP or None
  ## ref: https://kubernetes.io/docs/user-guide/services/
  serviceSessionAffinity: "None"

  # Zalenium hub uses these values to schedule pods through the k8s apiserver.
  cpuRequest: 500m
  cpuLimit: 1000m
  memRequest: 500Mi

  ## Start arguments for Zalenium hub itself
  ## https://github.com/zalando/zalenium/blob/master/docs/usage_examples.md
  desiredContainers: 2
  maxDockerSeleniumContainers: 600
  sauceLabsEnabled: false
  browserStackEnabled: false
  testingBotEnabled: false
  videoRecordingEnabled: true
  cpuRequest: 500m
  cpuLimit: 1000m
  memRequest: 500Mi
  screenWidth: 1440
  screenHeight: 900
  timeZone: "UTC"
  seleniumImageName: "elgalu/selenium"
  maxTestSessions: 5

  # Environment variables passed to Zalenium hub.
  sauceUserName: blank
  sauceAccessKey: blank
  browserStackUser: blank
  browserStackKey: blank
  testingBotKey: blank
  testingBotSecret: blank
```

**Comment by pearj** [comment] 2018-02-15 21:37
Just thinking about pod scheduling in kubernetes. I have a number of ideas about how to improve it. 

* for kubernetes we shouldn’t blindly retry creating a pod if it doesn’t appear. We should trust the kubernetes scheduler to do its job
* we should track pending pods when we create them, because on creation we are handed a pod name, so we should mark of the pods as the register. That way we know exactly what is outstanding. 
* potentially if we decide kubernetes has failed to schedule a particular pod than we should delete a pod request before creating a new one. 
* when registering and looking up the pod name by ip, maybe we should make that function asynchronous, if we can’t guarantee that we’ll be able to look it up first go.

**Comment by diemol** [comment] 2018-02-16 09:13
Yes, agree with those points. At least find a way to make the retry values configurable (times to retry and how long to wait between retries), so it can be tuned for Kubernetes, without changing the code too much.

**Comment by pearj** [comment] 2018-02-17 12:58
I was thinking that as soon as we start a pod we should put that pod on a queue that will have a background thread trying to resolve the IP address of that pod. So that when the pod eventually registers with zalenium we already have looked up the ip addresses for all the pods we are expecting to register. 

Since we don’t know when kubernetes will actually schedule a pod on a node it could take an unknown amount of time until that pod receives an IP address. So I was thinking that we could use a DelayQueue http://www.baeldung.com/java-delay-queue

So initially the pods are put in the queue with no delay, and they are attempted to be resolved to IP’s as soon as possible. Then if the lookup fails then are added back to the queue with a delay (a few seconds) and counter incremented. 

That way we can directly track the lifecycle of each pod, then after some configurable timeout we can simply delete the pod, and log the fact that we have given up on a pod. 

We could probably have multiple queues, one queue for resolving ip addresses and another for simply waiting for registration. We could say set a default 5 minute delay waiting for registration, at which point the pod is deleted, and maybe retried? Or maybe zalenium just gives up.

**Comment by Vlaaaaaaad** [comment] 2018-02-19 09:03
The approach sounds fine to me as long as both the delay and counter are user-configurable. Will the values be static( attempt, wait for X seconds, attempt again for Y times) or fancier( exponential back-off, with a max Z wait time)? Either way, a small random delay added to each request might be a good idea as not to spam the k8s API with request spikes. All pod scheduling requests will go out in a small XXXms window. And then nothing. And then another XXXms window full of requests.

And I think multiple queues is better. Say it takes 5 delays for the pod to be scheduled and then one more to get the IP. I'd like the IP-acquiring attempts to start from 0, not to continue. 

There might be some issues on the Selenium side with having a client wait 5 minutes for a browser, but looks like there [are some timeout options](https://github.com/SeleniumHQ/selenium/blob/master/rb/lib/selenium/webdriver/remote/http/default.rb#L35).

**Comment by diemol** [comment] 2018-02-20 14:45
Ah ok, so perhaps a combined approach then?

Monitoring the pod creation until a given point and then retry its creation in case it did not get created at all.

We can start looking into this in ~3 weeks, but any earlier contribution is highly appreciated.

**Comment by pearj** [comment] 2018-02-27 10:58
I started to toy around with the DelayQueues, but haven't got too far yet, as I just work on zalenium occasionally in my evenings. I'll see how far I get.

**Comment by pearj** [comment] 2018-03-16 12:25
I think I'll focus on #484 instead of making changes with DelayQueues and such things, as my changes (if successful) will drastically change the registration behaviour for kubernetes.

**Comment by pearj** [comment] 2018-03-19 11:32
Just bumped into this today, I do think there is still value solving this before any major re-achitecture of the kuberentes registration, as choosing how many pods to start is a separate concern anyway.

I've started investigating the excessive creation of selenium pods, and I've got my zalenium into a state, where it has 20 pods available for testing, but it is refusing to use any of them, and wants to start more, but it can't because I set the max to 20. So I attached a debugger and I found there are 114 requests in the new session queue, but all the tests failed hours earlier. 
I got into this situation by running 30 of the same test with 10 threads, after doing that a few times, zalenium was well and truly broken, "lights are on, but nobody is home" type of situation.

With TestNG you should be able to reproduce lots of threads really easily, just have a simple selenium test and update the annotation to look like: `@Test(invocationCount = 30, threadPoolSize = 10)`

@diemol you said that you might look at it this week, so here is my wishlist ;)

- Expire things from the `de.zalando.ep.zalenium.registry.ZaleniumRegistry.newSessionQueue` that are 1 minute old, after that point, the test has probably failed anyway.
- Merge `de.zalando.ep.zalenium.proxy.DockerSeleniumStarterRemoteProxy` into `de.zalando.ep.zalenium.registry.ZaleniumRegistry`, I think you already suggested this, but it looks like the registry is much better placed to start the docker containers, as it has more information available to it.
- Make starting docker containers single threaded, ie put the requests on a queue (I think the registry does that already), and then decide how many containers to start from one thread. Instead of creating containers on separate threads and tracking the creation status within that thread.
- Maybe have a "maxBurstContainers" flag, where you can say how many containers it's allowed to create at once, and it waits until those containers are created before starting more.  However, I'm thinking maybe this is just a band-aid over the fact we have dead sessions requests on the queue.
- Just generally make the registry simpler, you mentioned this on slack already.  The registry seems needlessly complicated, for what seems like should be a simple thing. Match incoming requests to a pool of resources and create more resources on demand.  Maybe there is a nice Java concurrent queue that can do what we want without having to use locks explicitly.

Tomorrow, I'll talk to my colleague and see if he has any ideas how to simplify the registry too.

**Comment by pearj** [comment] 2018-03-19 11:36
@diemol logs attached as requested [zalenium-5.log](https://github.com/zalando/zalenium/files/1824768/zalenium-5.log)
And there is also the newrelic account that should have information from the same timeframe as the logs.  The logs are in AEST timezone (+11) if you're trying to correlate them to newrelic.

**Comment by diemol** [comment] 2018-03-19 20:30
@pearj, thanks for the ideas, here is the list then:

- [ ] Expire incoming sessions from `ZaleniumRegistry. newSessionQueue `
  * I think I found a way to do that, I just need to test it. This would be a good improvement upstream as well.
- [ ] Merge `DockerSeleniumStarterRemoteProxy` and `ZaleniumRegistry`
- [ ] Make starting docker containers single threaded
  * Need to double check this, since it would slow down things when running tests in parallel.

Also, from the log you posted, I saw a bug where a completed test was marked afterwards as timeout because the file copy thing took too long. I'll also fix that.

In general, I see a few things to make things better in the k8s environment, but I will try to add it little by little since I don't have unlimited time to do this, and I don't want to start a branch where I can work only one or two days per week.

**Comment by pearj** [comment] 2018-03-19 22:51
I don't think starting docker containers on a single thread will hurt performance if we separate creating containers from waiting for containers to start.  I think they are separate concerns.

After you start a container you could simply hand off the tracking of the new container to another queue (or don't track it at all), and then immediately process the next request for a new test session.

With Kubernetes, I think we can trust that it isn't going to forget our request, even if for reasons it doesn't ultimately fulfil that request. So we could just query Kubernetes from time to time, and track the status of the requests.

I think this will actually be faster rather than slower, especially as you scale zalenium, in terms of numbers of selenium container, as more threads will cause more context switches slowing things down rather than speeding it up.

**Comment by pearj** [comment] 2018-03-19 22:55
In other news, it looks like the reason test sessions aren't being cleaned up is due to my handling of copying videos over, it's stuck in the countdown latch:

```
"Terminate Test Session int id: [82486527-89bf-4e46-9f63-1ad11703c537] ext id: [d8701abd9e3a33e225c2279645966e4d]" #1536 prio=5 os_prio=0 tid=0x00007ff2e4014000 nid=0xb11 waiting on condition [0x00007ff27f37a000]
   java.lang.Thread.State: WAITING (parking)
	at sun.misc.Unsafe.park(Native Method)
	- parking to wait for  <0x0000000678f91d50> (a java.util.concurrent.CountDownLatch$Sync)
	at java.util.concurrent.locks.LockSupport.park(LockSupport.java:175)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.parkAndCheckInterrupt(AbstractQueuedSynchronizer.java:836)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.doAcquireSharedInterruptibly(AbstractQueuedSynchronizer.java:997)
	at java.util.concurrent.locks.AbstractQueuedSynchronizer.acquireSharedInterruptibly(AbstractQueuedSynchronizer.java:1304)
	at java.util.concurrent.CountDownLatch.await(CountDownLatch.java:231)
	at de.zalando.ep.zalenium.container.kubernetes.KubernetesContainerClient.lambda$executeCommand$34(KubernetesContainerClient.java:251)
	at de.zalando.ep.zalenium.container.kubernetes.KubernetesContainerClient$$Lambda$220/1823068109.get(Unknown Source)
	at de.zalando.ep.zalenium.container.kubernetes.KubernetesContainerClient.executeCommand(KubernetesContainerClient.java:264)
	at de.zalando.ep.zalenium.proxy.DockerSeleniumRemoteProxy.processContainerAction(DockerSeleniumRemoteProxy.java:448)
	at de.zalando.ep.zalenium.proxy.DockerSeleniumRemoteProxy.processContainerAction(DockerSeleniumRemoteProxy.java:441)
	at de.zalando.ep.zalenium.proxy.DockerSeleniumRemoteProxy.videoRecording(DockerSeleniumRemoteProxy.java:405)
	at de.zalando.ep.zalenium.proxy.DockerSeleniumRemoteProxy.cleanupNode(DockerSeleniumRemoteProxy.java:550)
	at de.zalando.ep.zalenium.proxy.DockerSeleniumRemoteProxy.shutdownNode(DockerSeleniumRemoteProxy.java:567)
	at de.zalando.ep.zalenium.proxy.DockerSeleniumRemoteProxy.afterSession(DockerSeleniumRemoteProxy.java:290)
	at org.openqa.grid.internal.TestSlot.performAfterSessionEvent(TestSlot.java:253)
	at de.zalando.ep.zalenium.registry.ZaleniumRegistry._release(ZaleniumRegistry.java:114)
	at de.zalando.ep.zalenium.registry.ZaleniumRegistry.lambda$terminate$8(ZaleniumRegistry.java:98)
	at de.zalando.ep.zalenium.registry.ZaleniumRegistry$$Lambda$222/1735102591.run(Unknown Source)
	at java.lang.Thread.run(Thread.java:748
```

I'll dig into this and see if I can figure out why neither `onFailure` or `onClose` is called by the KubernetesClient in:
```
            @Override
            public void onFailure(Throwable t,
                                  Response response) {
                logger.log(Level.SEVERE, t, () -> String.format("%s Failed to execute command %s", containerId, Arrays.toString(command)));
                latch.countDown();
            }

            @Override
            public void onClose(int code,
                                String reason) {
                latch.countDown();
            }
```

**Comment by diemol** [comment] 2018-03-20 06:35
>I don't think starting docker containers on a single thread will hurt performance if we separate creating containers from waiting for containers to start. I think they are separate concerns.

True, I didn't think about it like that. Very good point, I'll have that in mind while I make changes today.

**Comment by pearj** [comment] 2018-03-20 11:17
@diemol I tried out your WIP commit that expires incoming sessions and it does appear to have helped me I think or something in that commit did at least. I ran 300 sessions to 10 threads, and it didn't lock up like normal. I'll run it a few more times and see how it goes

**Comment by diemol** [comment] 2018-03-21 00:08
@pearj I will remove the code I added to delete old requests (> 5 minutes), because after reading a bit the Selenium source code and the parameters... Well, there is something for that already. It is called `newSessionWaitTimeout`, and I just added it to the startup command, with a default of 5 minutes and it can be overwritten (the actual value has to be specified in milliseconds). It will show a stacktrace like this one:
```
00:56:32.656 INFO [RequestHandler.process] - Error forwarding the new session Request timed out waiting for a node to become available.
java.util.concurrent.TimeoutException: Request timed out waiting for a node to become available.
	at org.openqa.grid.web.servlet.handler.RequestHandler.waitForSessionBound(RequestHandler.java:197)
	at org.openqa.grid.web.servlet.handler.RequestHandler.process(RequestHandler.java:112)
	at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:86)
	at org.openqa.grid.web.servlet.DriverServlet.doPost(DriverServlet.java:70)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:860)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.seleniumhq.jetty9.server.Server.handle(Server.java:530)
	at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:347)
	at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:256)
	at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:102)
	at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.seleniumhq.jetty9.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:382)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:708)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:626)
	at java.lang.Thread.run(Thread.java:748)
```

Not ideal but at least is something Selenium Grid native that we don't need to maintain.

**Comment by pearj** [comment] 2018-05-03 11:46
Should be fixed by #537.

Reopen if it still happens.

**Closed by pearj** 2018-05-03 11:46 UTC
Labels: discussion, enhancement, help wanted

**Comment by pearj** [comment] 2018-05-08 09:39
@Vlaaaaaaad that’s good news. What time-out are you referring to? The one that gives up on requests that take too long? That is configurable. Also you might considering using pooling (desiredContainers) and enabling container reuse (maxTestSessions to something large). That will workaround slow start for a container to boot. Additionally you could add docker selenium to a local registry if most of the 60 seconds is pulling the image from docker hub

**Comment by Vlaaaaaaad** [comment] 2018-05-08 09:53
@pearj : when spamming the cluster with a lot of tests, the cluster may need to scale up. Adding a new node takes a couple minutes and during that time the connection requesting a browser may time out. 

I was using Watir which had a timeout of 60 seconds( will request a browser and wait up to 60 seconds to get the answer back). But launching a new instance and adding it to the cluster took more than 60 seconds. Zalenium did request the pod and was waiting for it to be scheduled( pod status was "_Pending_" as the k8s cluster waited for the scale up). Meanwhile, 60 seconds pass and my test code gave up with the error below and requested another pod: 
```
Net::ReadTimeout (Net::ReadTimeout)
/usr/local/lib/ruby/2.5.0/net/protocol.rb:181:in `rbuf_fill'
/usr/local/lib/ruby/2.5.0/net/protocol.rb:157:in `readuntil'
/usr/local/lib/ruby/2.5.0/net/protocol.rb:167:in `readline'
/usr/local/lib/ruby/2.5.0/net/http/response.rb:40:in `read_status_line'
/usr/local/lib/ruby/2.5.0/net/http/response.rb:29:in `read_new'
/usr/local/lib/ruby/2.5.0/net/http.rb:1494:in `block in transport_request'
/usr/local/lib/ruby/2.5.0/net/http.rb:1491:in `catch'
/usr/local/lib/ruby/2.5.0/net/http.rb:1491:in `transport_request'
/usr/local/lib/ruby/2.5.0/net/http.rb:1464:in `request'
/usr/local/lib/ruby/2.5.0/net/http.rb:1457:in `block in request'
/usr/local/lib/ruby/2.5.0/net/http.rb:910:in `start'
/usr/local/lib/ruby/2.5.0/net/http.rb:1455:in `request'
/usr/local/bundle/gems/selenium-webdriver-3.9.0/lib/selenium/webdriver/remote/http/default.rb:121:in `response_for'
/usr/local/bundle/gems/selenium-webdriver-3.9.0/lib/selenium/webdriver/remote/http/default.rb:76:in `request'
/usr/local/bundle/gems/selenium-webdriver-3.9.0/lib/selenium/webdriver/remote/http/common.rb:59:in `call'
/usr/local/bundle/gems/selenium-webdriver-3.9.0/lib/selenium/webdriver/remote/bridge.rb:164:in `execute'
/usr/local/bundle/gems/selenium-webdriver-3.9.0/lib/selenium/webdriver/remote/bridge.rb:97:in `create_session'
/usr/local/bundle/gems/selenium-webdriver-3.9.0/lib/selenium/webdriver/remote/bridge.rb:53:in `handshake'
/usr/local/bundle/gems/selenium-webdriver-3.9.0/lib/selenium/webdriver/remote/driver.rb:37:in `initialize'
/usr/local/bundle/gems/selenium-webdriver-3.9.0/lib/selenium/webdriver/common/driver.rb:56:in `new'
/usr/local/bundle/gems/selenium-webdriver-3.9.0/lib/selenium/webdriver/common/driver.rb:56:in `for'
/usr/local/bundle/gems/selenium-webdriver-3.9.0/lib/selenium/webdriver.rb:84:in `for'
/usr/local/bundle/gems/watir-6.10.3/lib/watir/browser.rb:48:in `initialize'
/home/jenkins/workspace/QA-1/features/support/env.rb:11:in `new'
```
Finally, the pods requested by Zalenium are out of "_Pending_", Zalenium sees that the first one is stale and deletes it. The second pod gets used for the test. Perfect behavior on the Zalenium side!

To get my tests to wait and not request a new pod so fast I had to add the `read_timeout` param:
```ruby
browser = Watir::Browser.new :firefox,
{
    timeout: 300,
    url: gridURL,
    'name': 'myTestName',
    open_timeout: (60 * 10),
    read_timeout: (60 * 10)
}
```

Yup, could've used `desiredContainers` or `maxTestSessions` to get around that, but I wanted to test Zalenium in the most severe conditions.
