### ISSUE TITLE
 the recorded video is not exist in dashboard and /tmp/videos

### ISSUE THREAD

**Issue by mehrdad-abdoli** [zalando/zalenium#848] opened 2019-01-27 14:14 UTC
## 💥 Regression Report
Error while copying the video . the recorded video is not exist in za dashboard and /tmp/videos

here is the log:
17:28:53.147 [http://172.25.0.3:40000] WARN  d.z.e.z.p.DockerSeleniumRemoteProxy - Error while copying the video
java.nio.file.NoSuchFileException: /home/seluser/videos/1420/zalenium_Web_Tests_Listing_Delete_Listing_IMG_And_Change_price_Build1420_PR5410_chrome_LINUX_20190127172755368_FAILED.mp4
        at sun.nio.fs.UnixException.translateToIOException(UnixException.java:86)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
        at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
        at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
        at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
        at java.nio.file.Files.newOutputStream(Files.java:216)
        at java.nio.file.Files.copy(Files.java:3016)
        at de.zalando.ep.zalenium.proxy.DockerSeleniumRemoteProxy.copyVideos(DockerSeleniumRemoteProxy.java:639)
        at de.zalando.ep.zalenium.proxy.DockerSeleniumRemoteProxy.processContainerAction(DockerSeleniumRemoteProxy.java:609)
        at de.zalando.ep.zalenium.proxy.DockerSeleniumRemoteProxy.processContainerAction(DockerSeleniumRemoteProxy.java:598)
        at de.zalando.ep.zalenium.proxy.DockerSeleniumRemoteProxy.videoRecording(DockerSeleniumRemoteProxy.java:562)
        at de.zalando.ep.zalenium.proxy.DockerSeleniumRemoteProxy.cleanupNode(DockerSeleniumRemoteProxy.java:749)
        at de.zalando.ep.zalenium.proxy.DockerSeleniumRemoteProxy.afterSession(DockerSeleniumRemoteProxy.java:402)
        at org.openqa.grid.internal.TestSlot.performAfterSessionEvent(TestSlot.java:253)
        at de.zalando.ep.zalenium.registry.ZaleniumRegistry._release(ZaleniumRegistry.java:198)
        at de.zalando.ep.zalenium.registry.ZaleniumRegistry.lambda$0(ZaleniumRegistry.java:182)
        at java.lang.Thread.run(Thread.java:748)

## Last working version
working till last 1 or 2 weeks 

Stopped working in version:
Latest (3.141.59g)

## To Reproduce

I use the zalenium more than 24 month and always with docker-compose
using robot framework tests 

## Expected behavior

recorded video can be found in /tmp/videos and dashboard

## Environment

OS: ubuntu 18
Zalenium Image Version(s): latest (3.141.59g)
Docker version: 18.09.0, build 4d60db4
Docker-Compose version (if applicable): 1.23.2, build 1110ad0
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well):
version: '2.2'

services:
  #--------------#
  zalenium:
    image: "dosel/zalenium"
    container_name: zalenium
    hostname: zalenium
    tty: true
    privileged: true
    volumes:
      - /tmp/videos:/home/seluser/videos
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
    ports:
      - 8899:4444
    command: >
      start --desiredContainers 0
            --maxTestSessions 4
            --maxDockerSeleniumContainers 15
            --screenWidth 1920
            --screenHeight 1080
            --timeZone "Asia/Tehran"
            --videoRecordingEnabled true
            --sauceLabsEnabled false
            --browserStackEnabled false
            --testingBotEnabled false
            --startTunnel false
            --keepOnlyFailedTests true
            --gridUser qa
            --gridPassword 1qaz3edc
    #      --debugEnabled true
    #      --debugEnabled true

    environment:
      - HOST_UID
      - HOST_GID

**Comment by diemol** [comment] 2019-01-29 20:33
Duplicate of #847

**Closed by diemol** 2019-01-29 20:33 UTC
