### ISSUE TITLE
No Such Session Webdriver Exception

### ISSUE THREAD

**Issue by Sharathn27** [zalando/zalenium#1105] opened 2019-12-06 05:26 UTC
## 🐛 Bug Report
I have a test suite which runs more than 2000 tests, which invokes the new driver 2000 times.
After around 1400 tests, Zalenium Hub stops responding which results in NoSuchSessionException

## To Reproduce

Steps to reproduce the behavior (including the docker command/docker-compose/Kubernetes manifests to start Zalenium):
We are using stock Zalenium, 
We are starting zalenium container by running below command

![image](https://user-images.githubusercontent.com/15869759/70298199-cd3e9800-1816-11ea-9db9-814f355541bf.png)

## Test script reproducing this issue (when applicable)

Please provide a test script to reproduce the issue you are reporting, if the 
setup is more complex, GitHub repo links are also OK.

Issues without a reproduction script are likely to stall and eventually be closed.

## Environment

OS: CentOs
Zalenium Image Version(s): 3.141.59u
Docker version: 1.13.1
Docker-Compose version (if applicable):
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well):
If using Kubernetes, specify your environment, and if relevant your manifests:

**Comment by diemol** [comment] 2019-12-09 17:45
Hi @Sharathn27,

Sorry, we cannot find a way to reproduce and help you troubleshoot the issue with the information provided. A wild guess could be that the environment is under-provisioned.

I will close this since we can treat it as a question, please join the #zalenium channel at [Slack](https://seleniumhq.herokuapp.com/) or [StackOverflow - Zalenium](https://stackoverflow.com/questions/tagged/zalenium) where the community can help you as well.

**Closed by diemol** 2019-12-09 17:45 UTC
