### ISSUE TITLE
Unable to start more than 50 containers 

### ISSUE THREAD

**Issue by ashkb** [zalando/zalenium#786] opened 2018-11-30 02:03 UTC
Zalenium Image Version(s):  3.141.59c
Selenium server version: 3.141.59

Docker Version:   18.06.1-ce

OS: 
Amazon Linux AMI 2018.03

Docker Command to start Zalenium:  
docker run --rm -ti --name zalenium -p 4444:4444 -v /tmp/videos:/home/seluser/videos -v /var/run/docker.sock:/var/run/docker.sock  --privileged dosel/zalenium start --desiredContainers 55 --maxDockerSeleniumContainers 55

## Expected Behavior -
I am using an Amazon **m5.12xlarge** instance type to start 55 containers to run my tests.  The expected behavior is that all 55 containers are started and register to the hub successfully .  

## Actual Behavior -
It registers only 30 to 40 nodes and after that I  see the node count reducing.   Look like it get into a state where it is trying to constantly start and stop containers. It never reaches the desired count .

I tested used older Zalenium version 3.8.1  on the same configuration and it works fine. I was able to scale up to 100 containers. With version 3.141.59c, I am able to scale up to 50.  More than 50 fails.

Attached is the full log file 
[logfile.txt](https://github.com/zalando/zalenium/files/2631653/logfile.txt)

**Comment by diemol** [comment] 2018-12-06 21:34
Hi @ashkb,

Would it be possible to get the logs for the same scenario but with the latest release? https://github.com/zalando/zalenium/releases/tag/3.141.59d

**Comment by ashkb** [comment] 2018-12-13 19:16
Hi @diemol ,

Attached are the logs for the same scenario on the latest release  3.141.59d


[Zalenum_3.141.59d.txt](https://github.com/zalando/zalenium/files/2677360/Zalenum_3.141.59d.txt)

**Comment by diemol** [comment] 2018-12-13 19:21
Thanks @ashkb, after checking the logs I can see that this is a duplicate of #624. Please follow up the progress there.

**Closed by diemol** 2018-12-13 19:21 UTC
Labels: waiting-answer
