### ISSUE TITLE
Tests are getting stuck with elgalu/docker-selenium:3.141.59-p34-35

### ISSUE THREAD

**Issue by dmarkdvt** [zalando/zalenium#1128] opened 2020-01-07 10:46 UTC
## 🐛 Bug Report

Tests are getting stuck when you are using Zalenium 3.141.59(u-w) with elgalu/docker-selenium:3.141.59-p34-35. That means that you have to click in a Window from the Live preview manually. Then the test is continuing. Everything is running fine with elgalu/docker-selenium:3.141.59-p32.

## To Reproduce

Steps to reproduce the behavior (including the docker command/docker-compose/Kubernetes manifests to start Zalenium):

1. Install Zalenium 3.141.59w via Helm charts into OpenShift 3.11.0
2. Run a test
3. Open Live Preview http://HOST/grid/admin/live
3. Wait for a window to get stuck
4. Click into the faulty window
5. Watch test continuing

## Expected behavior

The tests should run completely standalone.

## Test script reproducing this issue (when applicable)

Please read the steps to reproduce the issue.

## Environment

OS: Red Hat Enterprise Linux Server release 7.7 (Maipo)
Zalenium Image Version(s): 3.141.59u - 3.141.59w
Docker version: 1.13.1
Docker-Compose version (if applicable): 1.9.0
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well):
If using Kubernetes, specify your environment, and if relevant your manifests: 
```
helm template --name zvh --set hub.serviceType=NodePort charts/zalenium | kubectl -n zvh apply -f -
```
```
[root@okdtest01 zalenium]# kubectl version
Client Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2018-10-15T09:45:30Z", GoVersion:"go1.10.2", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"11+", GitVersion:"v1.11.0+d4cacc0", GitCommit:"d4cacc0", GitTreeState:"clean", BuildDate:"2019-12-19T05:39:29Z", GoVersion:"go1.10.8", Compiler:"gc", Platform:"linux/amd64"}
```

**Comment by diemol** [comment] 2020-01-10 04:01
Hi @dmarkdvt,

 I will close this issue since there is no reproduction scenario, only a narrative. Feel free to open a new issue when a script that reproduces the issue is attached.

**Closed by diemol** 2020-01-10 04:01 UTC

**Comment by dmarkdvt** [comment] 2020-01-10 06:15
Okay, do you have an example issue where such a script is provided? Then I can create a new proper issue.

**Comment by pavelsmolensky** [comment] 2020-01-10 15:01
Observing the same problem starting from Chrome 79. There is an error "Timed out receiving message from renderer..." in chrome logs. @dmarkdvt Do you also use chrome and have this error log entry? It's unlikely to be zalenium's issue though.

**Comment by dmarkdvt** [comment] 2020-01-20 10:27
> Observing the same problem starting from Chrome 79. There is an error "Timed out receiving message from renderer..." in chrome logs. @dmarkdvt Do you also use chrome and have this error log entry? It's unlikely to be zalenium's issue though.

@pavelsmolensky We are using Chrome. Are the logs created by default or how can I access it?

**Comment by pavelsmolensky** [comment] 2020-01-21 23:08
@dmarkdvt Having the reference you provided now it's clear that this is the Chrome's bug. Regarding the logs - you can find them by navigating to `/dashboard` of your zalenium instance
