### ISSUE TITLE
java.io.EOFException: \n not found: limit=0 content=��� happens randomly (ERROR o.o.g.w.s.handler.RequestHandler - cannot forward the request unexpected end of stream on Connection{172.18.0.10:40161, proxy=DIRECT hostAddress=/172.18.0.10:40161 cipherSuite=none protocol=http/1.1})

### ISSUE THREAD

**Issue by henrykuijpers** [zalando/zalenium#1092] opened 2019-11-19 13:23 UTC
## 🐛 Bug Report

When running tests, all of a sudden invalid responses are output, due to which OkHttp3 breaks with the following stack trace:

Note, the "Caused by: java.io.EOFException: \n not found: limit=0 content=���" is suspicious.

```
[36mzalenium            |[0m 2019-11-18T22:45:16.296611000Z 23:45:16.292 [qtp109069556-2048] ERROR o.o.g.w.s.handler.RequestHandler - cannot forward the request unexpected end of stream on Connection{172.18.0.10:40161, proxy=DIRECT hostAddress=/172.18.0.10:40161 cipherSuite=none protocol=http/1.1}
[36mzalenium            |[0m 2019-11-18T22:45:16.297068000Z java.io.IOException: unexpected end of stream on Connection{172.18.0.10:40161, proxy=DIRECT hostAddress=/172.18.0.10:40161 cipherSuite=none protocol=http/1.1}
[36mzalenium            |[0m 2019-11-18T22:45:16.297558000Z 	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:208)
[36mzalenium            |[0m 2019-11-18T22:45:16.297997000Z 	at okhttp3.internal.http.CallServerInterceptor.intercept(CallServerInterceptor.java:88)
[36mzalenium            |[0m 2019-11-18T22:45:16.298470000Z 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[36mzalenium            |[0m 2019-11-18T22:45:16.298865000Z 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[36mzalenium            |[0m 2019-11-18T22:45:16.299362000Z 	at org.openqa.selenium.remote.internal.OkHttpClient$Factory$1.lambda$createClient$1(OkHttpClient.java:152)
[36mzalenium            |[0m 2019-11-18T22:45:16.299785000Z 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[36mzalenium            |[0m 2019-11-18T22:45:16.301742000Z 	at okhttp3.internal.connection.ConnectInterceptor.intercept(ConnectInterceptor.java:45)
[36mzalenium            |[0m 2019-11-18T22:45:16.302256000Z 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[36mzalenium            |[0m 2019-11-18T22:45:16.302785000Z 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[36mzalenium            |[0m 2019-11-18T22:45:16.303325000Z 	at okhttp3.internal.cache.CacheInterceptor.intercept(CacheInterceptor.java:93)
[36mzalenium            |[0m 2019-11-18T22:45:16.303878000Z 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[36mzalenium            |[0m 2019-11-18T22:45:16.304413000Z 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[36mzalenium            |[0m 2019-11-18T22:45:16.304875000Z 	at okhttp3.internal.http.BridgeInterceptor.intercept(BridgeInterceptor.java:93)
[36mzalenium            |[0m 2019-11-18T22:45:16.305463000Z 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[36mzalenium            |[0m 2019-11-18T22:45:16.306005000Z 	at okhttp3.internal.http.RetryAndFollowUpInterceptor.intercept(RetryAndFollowUpInterceptor.java:126)
[36mzalenium            |[0m 2019-11-18T22:45:16.306476000Z 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:147)
[36mzalenium            |[0m 2019-11-18T22:45:16.306898000Z 	at okhttp3.internal.http.RealInterceptorChain.proceed(RealInterceptorChain.java:121)
[36mzalenium            |[0m 2019-11-18T22:45:16.307450000Z 	at okhttp3.RealCall.getResponseWithInterceptorChain(RealCall.java:200)
[36mzalenium            |[0m 2019-11-18T22:45:16.307875000Z 	at okhttp3.RealCall.execute(RealCall.java:77)
[36mzalenium            |[0m 2019-11-18T22:45:16.308544000Z 	at org.openqa.selenium.remote.internal.OkHttpClient.execute(OkHttpClient.java:103)
[36mzalenium            |[0m 2019-11-18T22:45:16.309862000Z 	at org.openqa.grid.internal.TestSession.sendRequestToNode(TestSession.java:422)
[36mzalenium            |[0m 2019-11-18T22:45:16.310401000Z 	at org.openqa.grid.internal.TestSession.forward(TestSession.java:229)
[36mzalenium            |[0m 2019-11-18T22:45:16.310851000Z 	at org.openqa.grid.web.servlet.handler.RequestHandler.forwardRequest(RequestHandler.java:99)
[36mzalenium            |[0m 2019-11-18T22:45:16.311321000Z 	at org.openqa.grid.web.servlet.handler.RequestHandler.process(RequestHandler.java:133)
[36mzalenium            |[0m 2019-11-18T22:45:16.311753000Z 	at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:85)
[36mzalenium            |[0m 2019-11-18T22:45:16.312325000Z 	at org.openqa.grid.web.servlet.DriverServlet.doPost(DriverServlet.java:69)
[36mzalenium            |[0m 2019-11-18T22:45:16.312792000Z 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
[36mzalenium            |[0m 2019-11-18T22:45:16.313325000Z 	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
[36mzalenium            |[0m 2019-11-18T22:45:16.313780000Z 	at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:865)
[36mzalenium            |[0m 2019-11-18T22:45:16.314286000Z 	at org.seleniumhq.jetty9.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1655)
[36mzalenium            |[0m 2019-11-18T22:45:16.314766000Z 	at io.prometheus.client.filter.MetricsFilter.doFilter(MetricsFilter.java:170)
[36mzalenium            |[0m 2019-11-18T22:45:16.324766000Z 	at org.seleniumhq.jetty9.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1642)
[36mzalenium            |[0m 2019-11-18T22:45:16.325263000Z 	at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:533)
[36mzalenium            |[0m 2019-11-18T22:45:16.325721000Z 	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:146)
[36mzalenium            |[0m 2019-11-18T22:45:16.326202000Z 	at org.seleniumhq.jetty9.security.SecurityHandler.handle(SecurityHandler.java:548)
[36mzalenium            |[0m 2019-11-18T22:45:16.326600000Z 	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
[36mzalenium            |[0m 2019-11-18T22:45:16.327071000Z 	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:257)
[36mzalenium            |[0m 2019-11-18T22:45:16.327529000Z 	at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
[36mzalenium            |[0m 2019-11-18T22:45:16.327934000Z 	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:255)
[36mzalenium            |[0m 2019-11-18T22:45:16.328464000Z 	at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1340)
[36mzalenium            |[0m 2019-11-18T22:45:16.328963000Z 	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:203)
[36mzalenium            |[0m 2019-11-18T22:45:16.329511000Z 	at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
[36mzalenium            |[0m 2019-11-18T22:45:16.329954000Z 	at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)
[36mzalenium            |[0m 2019-11-18T22:45:16.330479000Z 	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:201)
[36mzalenium            |[0m 2019-11-18T22:45:16.330912000Z 	at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1242)
[36mzalenium            |[0m 2019-11-18T22:45:16.331466000Z 	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:144)
[36mzalenium            |[0m 2019-11-18T22:45:16.331895000Z 	at org.seleniumhq.jetty9.server.handler.StatisticsHandler.handle(StatisticsHandler.java:174)
[36mzalenium            |[0m 2019-11-18T22:45:16.332435000Z 	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
[36mzalenium            |[0m 2019-11-18T22:45:16.332938000Z 	at org.seleniumhq.jetty9.server.Server.handle(Server.java:503)
[36mzalenium            |[0m 2019-11-18T22:45:16.333468000Z 	at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:364)
[36mzalenium            |[0m 2019-11-18T22:45:16.333901000Z 	at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:260)
[36mzalenium            |[0m 2019-11-18T22:45:16.334514000Z 	at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:305)
[36mzalenium            |[0m 2019-11-18T22:45:16.352182000Z 	at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:103)
[36mzalenium            |[0m 2019-11-18T22:45:16.352699000Z 	at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:118)
[36mzalenium            |[0m 2019-11-18T22:45:16.353203000Z 	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.runTask(EatWhatYouKill.java:333)
[36mzalenium            |[0m 2019-11-18T22:45:16.353591000Z 	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:310)
[36mzalenium            |[0m 2019-11-18T22:45:16.354011000Z 	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
[36mzalenium            |[0m 2019-11-18T22:45:16.354448000Z 	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
[36mzalenium            |[0m 2019-11-18T22:45:16.354838000Z 	at org.seleniumhq.jetty9.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
[36mzalenium            |[0m 2019-11-18T22:45:16.355361000Z 	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
[36mzalenium            |[0m 2019-11-18T22:45:16.355761000Z 	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
[36mzalenium            |[0m 2019-11-18T22:45:16.356253000Z 	at java.lang.Thread.run(Thread.java:748)
[36mzalenium            |[0m 2019-11-18T22:45:16.356655000Z Caused by: java.io.EOFException: \n not found: limit=0 content=���
[36mzalenium            |[0m 2019-11-18T22:45:16.357124000Z 	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:237)
[36mzalenium            |[0m 2019-11-18T22:45:16.357532000Z 	at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:215)
[36mzalenium            |[0m 2019-11-18T22:45:16.357903000Z 	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
[36mzalenium            |[0m 2019-11-18T22:45:16.358390000Z 	... 61 common frames omitted
[36mzalenium            |[0m 2019-11-18T22:45:16.358790000Z 23:45:16.317 [http://172.18.0.10:40161] INFO  d.z.e.z.p.DockerSeleniumRemoteProxy - Session bb756a80-0f2f-492d-92d9-73dde8d6353e completed. Node should shutdown soon...
[36mzalenium            |[0m 2019-11-18T22:45:16.359236000Z 23:45:16.348 [http://172.18.0.10:40161] DEBUG d.z.e.z.c.DockerContainerClient - http://172.18.0.10:40161 [bash, -c, notify 'Zalenium', 'TEST COMPLETED', --icon=/home/seluser/images/completed.png]
[36mzalenium            |[0m 2019-11-18T22:45:16.504559000Z 23:45:16.500 [http://172.18.0.10:40161] DEBUG d.z.e.z.p.DockerSeleniumRemoteProxy - lastCommand: GET - executing...
[36mzalenium            |[0m 2019-11-18T22:45:16.897409000Z 23:45:16.890 [http://172.18.0.10:40161] DEBUG d.z.e.z.c.DockerContainerClient - http://172.18.0.10:40161 
[36mzalenium            |[0m 2019-11-18T22:45:16.914065000Z 23:45:16.912 [http://172.18.0.10:40161] DEBUG d.z.e.z.c.DockerContainerClient - http://172.18.0.10:40161 [bash, -c, stop-video]
[36mzalenium            |[0m 2019-11-18T22:45:17.846557000Z 23:45:17.831 [http://172.18.0.10:40161] DEBUG d.z.e.z.p.DockerSeleniumRemoteProxy - lastCommand: GET - executing...
[36mzalenium            |[0m 2019-11-18T22:45:18.007444000Z 23:45:18.000 [http://172.18.0.10:40161] DEBUG d.z.e.z.p.DockerSeleniumRemoteProxy - lastCommand: POST - executing...
[36mzalenium            |[0m 2019-11-18T22:45:18.024887000Z 23:45:18.020 [http://172.18.0.10:40161] DEBUG d.z.e.z.p.DockerSeleniumRemoteProxy - lastCommand: POST - executing...
[36mzalenium            |[0m 2019-11-18T22:45:18.043934000Z 23:45:18.041 [http://172.18.0.10:40161] DEBUG d.z.e.z.p.DockerSeleniumRemoteProxy - lastCommand: POST - executing...
[36mzalenium            |[0m 2019-11-18T22:45:18.044569000Z 23:45:18.041 [http://172.18.0.10:40161] DEBUG d.z.e.z.p.DockerSeleniumRemoteProxy - Checking for cookies... {
[36mzalenium            |[0m 2019-11-18T22:45:18.045037000Z   "cookie": {
[36mzalenium            |[0m 2019-11-18T22:45:18.045577000Z     "httpOnly": false,
[36mzalenium            |[0m 2019-11-18T22:45:18.045999000Z     "name": "zaleniumTestPassed",
[36mzalenium            |[0m 2019-11-18T22:45:18.046544000Z     "path": "\u002f",
[36mzalenium            |[0m 2019-11-18T22:45:18.046989000Z     "secure": false,
[36mzalenium            |[0m 2019-11-18T22:45:18.047502000Z     "value": "false"
[36mzalenium            |[0m 2019-11-18T22:45:18.047890000Z   }
[36mzalenium            |[0m 2019-11-18T22:45:18.048376000Z }
[36mzalenium            |[0m 2019-11-18T22:45:18.062415000Z 23:45:18.059 [http://172.18.0.10:40161] DEBUG d.z.e.z.p.DockerSeleniumRemoteProxy - lastCommand: POST - executing...
[36mzalenium            |[0m 2019-11-18T22:45:18.068815000Z 23:45:18.067 [http://172.18.0.10:40161] DEBUG d.z.e.z.p.DockerSeleniumRemoteProxy - lastCommand: DELETE - executing...
[36mzalenium            |[0m 2019-11-18T22:45:18.227681000Z 23:45:18.220 [http://172.18.0.10:40161] DEBUG d.z.e.z.p.DockerSeleniumRemoteProxy - lastCommand: DELETE - executing...
[36mzalenium            |[0m 2019-11-18T22:45:18.239788000Z 23:45:18.236 [http://172.18.0.10:40161] DEBUG d.z.e.z.p.DockerSeleniumRemoteProxy - lastCommand: DELETE - executing...
[36mzalenium            |[0m 2019-11-18T22:45:18.253149000Z 23:45:18.247 [http://172.18.0.10:40161] DEBUG d.z.e.z.p.DockerSeleniumRemoteProxy - lastCommand: DELETE - executing...
```

## To Reproduce

It, unfortunately, happens randomly. We could have a successful test run for days, but then all of a sudden a test starts failing.

## Expected behavior

We'd expect, if this happens, that Zalenium is able to recover, instead of terminating the current test and marking it is as failed. I.e. retrying the request, or solving the bug that caused the invalid request.

## Test script reproducing this issue (when applicable)

Unfortunately it's hard to provide a reproduction script. 

## Environment

OS: Linux CentOS, Docker
Zalenium Image Version(s): 3.141.59u
Docker version: 
Docker-Compose version (if applicable):
Exact Docker command to start the containers (if using docker-compose, provide 
the docker-compose file as well):
If using Kubernetes, specify your environment, and if relevant your manifests:

**Comment by ls-sergii-buchovskyi** [comment] 2019-11-19 13:59
Look like similar to these:
https://github.com/zalando/zalenium/issues/742
https://github.com/zalando/zalenium/issues/939
https://github.com/zalando/zalenium/issues/993

**Comment by henrykuijpers** [comment] 2019-11-19 14:00
Yes... But never a fix.

**Comment by henrykuijpers** [comment] 2019-11-19 18:40
@diemol 
https://github.com/zalando/zalenium/commit/1a584812bfcfb74a762424e1aa2e3849b18efaf3
https://github.com/zalando/zalenium/issues/756#issuecomment-443524279

I see suggestions that this issue could be related to the performance of the environment in which the Docker containers are running. Would the above 2 links be of any help into tackling this issue? I.e. configuring a limit on CPU/memory? Or limiting the amount of containers?

Our current configuration, for the zalenium container hosting is:
```
  zalenium:
    image: dosel/zalenium:3.141.59u
    container_name: zalenium
    hostname: zalenium
    tty: true
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./test-videos:/home/seluser/videos
    ports:
      - "4444:4444"
    command: >
      start --desiredContainers ${DOCKER_SELENIUM_CONTAINERS:-2}
            --maxDockerSeleniumContainers ${DOCKER_MAX_SELENIUM_CONTAINERS:-4}
            --screenWidth 1920
            --screenHeight 1080
            --timeZone "Europe/Amsterdam"
            --videoRecordingEnabled true
            --keepOnlyFailedTests true
            --seleniumImageName elgalu/selenium:3.141.59-p12
            --debugEnabled true
    environment:
      - PULL_SELENIUM_IMAGE=true
    privileged: true
    networks:
      - test-network
```
Next to that container, we're also hosting *2 very heavy containers in terms of CPU/memory* + a container for a mail client, a container for a webserver/loadbalancer, and a container for running our tests against the grid.

WDYT @diemol ?

**Comment by ls-sergii-buchovskyi** [comment] 2019-11-19 19:47
We had performance issues in CircleCI last week and that error happened 6-8 times in 5 jobs with 80 tests in total, now when performance is stable we are getting 1-2 errors in test run. It's better but error is still there..

**Comment by henrykuijpers** [comment] 2019-11-20 10:21
That's interesting. So we can confirm that it means the failures are more apparent when there's higher load / lower performance? 

I'm still a bit confused on where to search for the root cause: Could it be that one of the grid containers fails, for some reason?

On the other hand: Wouldn't it be desirable to have retries in the client, accessing those containers? I mean, at any point in time a hickup in the network could happen. Should it necessarily fail the test? Or should it be failing the test if after 5 retries (or something) it was still not successful? I'd vouch for the last.

Or does it mean that, for some reason, the newly created container, registers itself too soon? Or too late (while it is already being terminated)? Causing the client to assume that access to the container should be possible, therefore failing miserably? 

I'd like to dig into this issue further, since we are very obstructed with this behaviour in our current regression test setup. I'd like to see this fixed. If there's anything we can do, i.e. raise certain log levels, or maybe even attach profilers, or whatever is needed.

Our setup is currently being ran every night, given that this is already on the long term an intermittent issue, we should be able to gather enough statistics to be analayzed. But I'd need to some guidance in doing so, because currently I don't see exactly what is causing this behaviour.

**Comment by ahaverdings** [comment] 2019-11-20 14:49
I have seen the exception occur after a selenium docker container (created by zalenium) is requesting 100% cpu and mem while it is not doing a test execution. When this happens all other containers are very slow and throw timeout exceptions. After the hanging containers is killed order seems to be restored.

As documentation describes that the error occurs when the swarm is overloaded it makes sense that the error is thrown when a container is at 100% cpu. But the cause of this overload is random and would stil happen even if desired and max containers is set to 1. 
The least number of exceptions occur when you don't let zalenium create the selenium docker containers but have 1 dedicated container running. IMO the cause of the overload is connected to the way zalenium is creating and destroying the selenium docker images.

**Comment by diemol** [comment] 2019-12-09 17:56
So this is mostly a duplicate of #939 
In the end, regarding issue reproduction, we are in the same situation as you all mention... I have tried several times to reproduce it and never achieved it. So it is really hard to fix something we cannot reproduce.

Again, I apologize for not providing a complete answer or pointing to a solution, but the clear point is that no one has at least provided a way to reproduce it. Summing to this is the situation where we are lacking time to work on this, due to our day jobs and also to resources to run tests to attempt to reproduce the issue.

**Comment by diemol** [comment] 2019-12-09 17:56
I will close this one so the conversation continues in #939

**Closed by diemol** 2019-12-09 17:56 UTC
