### ISSUE TITLE
On hitting localhost url, getting a message in browser " The site cannot be reached"

### ISSUE THREAD

**Issue by mohitsh08** [zalando/zalenium#665] opened 2018-07-20 12:26 UTC
**Please make sure that you provide enough information for us to help you with this issue. Thank you!**

Zalenium Image Version(s):  Using Latest Zalenium version. Pulled from dosel/zalenium

Docker Version:  Docker version 18.03.0-ce, build 0520e24302

If using docker-compose, version:   NA

OS: Window 7 64 bit

Docker Command to start Zalenium:  docker run --rm -ti --name zalenium -p 4444:4444 -v /var/run/docker.sock:/var/run/docker.sock -V/tmp/videos:/home/seluser/videos --privileged dosel/zalenium start

If using Kubernetes, specify your environment, and if relevant your manifests:  

## Actual Behavior - After hitting the url, getting a message in the browser, This site can’t be reached
localhost refused to connect.
Search Google for localhost 4444 dashboard
ERR_CONNECTION_REFUSED

**Comment by diemol** [comment] 2018-07-22 20:41
Hi @mohitsh08,

Could you please share a test that we could use to reproduce the issue?

**Comment by mohitsh08** [comment] 2018-07-23 08:08
Hi @diemol,

I am working behind the corporate proxy. I have done setup in my office machine. I am running a simple webdriver test to open google.com. Also i have tried running it on my personal laptop and it is running fine.
Is there any special setup or configuration which i need to do, please let me know.

**Comment by diemol** [comment] 2018-07-23 08:14
Could you please provide more information?

What does this mean?
>localhost refused to connect.
Search Google for localhost 4444 dashboard
ERR_CONNECTION_REFUSED

Where do you get those messages? How does the test look like?

Besides, I see that the volume being mounted looks like this
```
-V/tmp/videos:/home/seluser/videos 
```

The "v" is in capital letters, and there is no space after it.

**Comment by mohitsh08** [comment] 2018-07-23 10:34
Hi @diemol,

Please refer to the attached screenshots.

Docker is up and running and I am using below command:
docker run --rm -ti --name zalenium -p 4444:4444 -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/videos:/home/seluser/videos --privileged dosel/zalenium start.

I have attached Zalenium Live preview screen and Zalenium container logs.
![zaleniumnodelogs](https://user-images.githubusercontent.com/35256646/43071952-039a3720-8e92-11e8-8142-5e781206be7c.PNG)
![zaleniumcontainerlogs](https://user-images.githubusercontent.com/35256646/43071953-043c3f02-8e92-11e8-877d-fd5465c1ead1.PNG)
![zaleniumlivepreview](https://user-images.githubusercontent.com/35256646/43071954-04cc3a12-8e92-11e8-8f4f-1d75f519714e.PNG)

**Comment by mohitsh08** [comment] 2018-07-23 10:37
Hi @diemol ,

Below is the sample test i am using to run on Zalenium:
package test.zalenium;

import java.net.MalformedURLException;
import java.net.URL;
import java.util.concurrent.TimeUnit;

import org.openqa.selenium.WebDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.remote.RemoteWebDriver;

public class ZaleniumTest {

	public static void main(String[] args) throws MalformedURLException {
		// TODO Auto-generated method stub
		String URL = "http://192.168.99.100:4444/wd/hub";
		WebDriver driver = null;
		
		DesiredCapabilities cap = null;
		cap = new DesiredCapabilities().chrome();
		
		driver = new RemoteWebDriver(new URL(URL), cap);
		driver.manage().deleteAllCookies();
		driver.manage().window().maximize();
		driver.get("https://www.google.com");
		driver.manage().timeouts().implicitlyWait(10, TimeUnit.SECONDS);
	}

}

**Comment by diemol** [comment] 2018-07-24 07:18
@mohitsh08 if you are behind a proxy, it also needs to be configured either in the docker container or in the Selenium test.

You can check the "Adding proxy configuration to the containers" section on https://opensource.zalando.com/zalenium/, or here to set it in Chrome when starting the test http://chromedriver.chromium.org/capabilities

I will close the issue since it it not really a Zalenium issue. If any other problem shows up, feel free to open a new issue.

**Closed by diemol** 2018-07-24 07:18 UTC

**Comment by mohitsh08** [comment] 2018-07-24 08:52
Hi @diemol ,

Thank you so much for your response. It is working fine now. 
After adding proper configuration and http_proxy in Zalenium start command, I am able to start test execution.
Thanks a lot once again :+1:

**Comment by oliviazhu81** [comment] 2018-11-29 09:38
Hi @mohitsh08 ,
I have the same Problem with my office computer, can you tell me how do you add the proper configuration and what do you add in the http_proxy command to solve this problem? Thank you!

**Comment by mohitsh08** [comment] 2018-12-02 18:58
Hi @oliviazhu81 ,

Apologies for late response.

Please try with below docker command. I have added proxy parameter to it.

docker run --rm -ti --name zalenium -p 4444:4444 -v /var/run/docker.sock:/var/run/docker.sock -v /tmp/videos:/home/seluser/videos -e "zalenium_http_proxy=http://username:password@corporate_proxy:port no" -e "zalenium_https_proxy=https://username:password@corporate_proxy:port no" -e "zalenium_no_proxy=172.16/12, 10.0.0.0/8, *.local, 169.254/16, 192.168.99.*, localhost, 127.0.0.1" -e "WAIT_TIME_OUT_VIDEO_STOP=5m" -e "WAIT_TIMEOUT=5m" --privileged dosel/zalenium start.

Please let me know if you are able to run or not.
