### ISSUE TITLE
Can't open dashboard

### ISSUE THREAD

**Issue by diogompg** [zalando/zalenium#882] opened 2019-02-27 17:15 UTC
I'm using Windows and installed Zalenium with the .\prepare.bat

Then, when i try o start Zalenium with:
    docker run --rm -ti --name zalenium -p 4444:4444 \
      -v /var/run/docker.sock:/var/run/docker.sock \
      -v /tmp/videos:/home/seluser/videos \
      --privileged dosel/zalenium start
I get an error on the console:
Copying files for Dashboard...
cp: cannot create regular file '/home/seluser/videos/dashboard.html': No such file or directory

Everything works except the Dashboard.
I'm using the latest version.
Thank you

**Comment by diemol** [comment] 2019-03-01 11:13
@diogompg 
How can I reproduce that?
Also, the dashboard changed recently, so perhaps you would need to delete the whole `/tmp/videos/` directory and try again.

**Comment by diemol** [comment] 2019-03-30 21:47
I'll close this for now, feel free to reopen if more information is available.

**Closed by diemol** 2019-03-30 21:47 UTC
Labels: waiting-answer

**Comment by taylorcoffelt** [comment] 2019-04-01 17:24
I'm also having this issue with the latest version of the zalenium docker image (dosel/zalenium:3), if I try to start it with just 
`docker run --rm -ti --name zalenium -p 4444:4444 --privileged dosel/zalenium:latest start`
I get this output: 
```4/1/2019 11:05:20 AMDocker version 18.09.0, build 4d60db4
4/1/2019 11:05:20 AM-- LOG 19:05:20:377033469 Ensuring docker works...
4/1/2019 11:05:20 AM-- LOG 19:05:20:505598160 Ensuring docker-selenium is available...
4/1/2019 11:05:20 AMhaveged: haveged starting up
4/1/2019 11:05:20 AMCopying files for Dashboard...
4/1/2019 11:05:20 AMcp: cannot create regular file '/home/seluser/videos/dashboard.html': No such file or directory
4/1/2019 11:05:25 AMStarting Nginx reverse proxy...
4/1/2019 11:05:25 AMStarting Selenium Hub...
4/1/2019 11:05:26 AM...19:05:26.129 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Selenium server version: 3.141.59, revision: unknown
4/1/2019 11:05:26 AM19:05:26.215 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Launching Selenium Grid hub on port 4445
4/1/2019 11:05:26 AM..19:05:26.576 [main] INFO  d.z.e.z.c.DockerContainerClient - About to clean up any left over DockerSelenium containers created by Zalenium
4/1/2019 11:05:27 AM....19:05:27.537 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Starting poller.
4/1/2019 11:05:27 AM..19:05:27.936 [main] INFO  d.z.ep.zalenium.aspect.HubAspect - Registering custom Zalenium servlets
4/1/2019 11:05:28 AM19:05:28.044 [main] INFO  org.openqa.grid.web.Hub - Selenium Grid hub is up and running
4/1/2019 11:05:28 AM19:05:28.045 [main] INFO  org.openqa.grid.web.Hub - Nodes should register to http://10.42.98.28:4445/grid/register/
4/1/2019 11:05:28 AM19:05:28.045 [main] INFO  org.openqa.grid.web.Hub - Clients should connect to http://10.42.98.28:4445/wd/hub
4/1/2019 11:05:28 AMSelenium Hub started!
4/1/2019 11:05:28 AMSauce Labs not enabled...
4/1/2019 11:05:28 AMBrowser Stack not enabled...
4/1/2019 11:05:28 AMTestingBot not enabled...
4/1/2019 11:05:28 AMZalenium is now ready!
4/1/2019 11:05:28 AM*************************************** Data Processing Agreement ***************************************
4/1/2019 11:05:28 AMBy using this software you agree that the following non-PII (non personally identifiable information)
4/1/2019 11:05:28 AMdata will be collected, processed and used by Zalando SE for the purpose of improving our test
4/1/2019 11:05:28 AMinfrastructure tools. Anonymisation with respect of the IP address means that only the first two octets
4/1/2019 11:05:28 AMof the IP address are collected.
4/1/2019 11:05:28 AM
4/1/2019 11:05:28 AMSee the complete license at https://github.com/zalando/zalenium/blob/master/LICENSE.md
4/1/2019 11:05:28 AM*************************************** Data Processing Agreement ***************************************
4/1/2019 11:05:36 AM19:05:36.595 [Thread-10] INFO  d.z.e.z.registry.ZaleniumRegistry - Registered a node http://172.17.0.3:40000
4/1/2019 11:05:41 AM19:05:41.815 [Thread-11] INFO  d.z.e.z.registry.ZaleniumRegistry - Registered a node http://172.17.0.4:40001
```

Visiting http://localhost:4444/dashboard gives me a `403 Forbidden` error, and I've confirmed that the file is missing from the `/home/seluser/videos/` in the container.

However,  is looks like `dashboard_template.html` is placed in the `/home/seluser` directory, and needs can be manually moved to the `videos` directory as `dashboard.html` If I do that, the page will then load, but the styles are missing as it's looking for them at `/dashboard/css/dashboard.css` but the `css` directory doesn't exist in `videos`. Once I manually move the css into that folder, the dashboard will load up correctly, so it looks like it's just some quick path fixes that need to happen.

**Comment by gerrit8143** [comment] 2019-04-04 12:57
I'm having the same issue with the helm chart, as soon as i enable the video persistent volume the dashboard returns a 403 Forbidden.

with video PV enabled /home/seluser/videos is empty, with video PV disabled /home/seluser/videos contains:

seluser@zalenium-59f7d8d88f-m6dg6:~$ ls -l /home/seluser/videos/
total 40
drwxr-xr-x. 2 seluser seluser  4096 Apr  4 12:52 css
-rwxr--r--. 1 seluser seluser 10996 Apr  4 12:52 dashboard.html
drwxr-xr-x. 2 seluser seluser  4096 Apr  4 12:52 img
drwxr-xr-x. 2 seluser seluser  4096 Apr  4 12:52 js

**Comment by Karl515** [comment] 2020-02-18 23:30
asdasd

**Comment by Karl515** [comment] 2020-02-18 23:32
I was also experience the problem that I can't open zalenium dashboard in localhost:4444/dashboard. Then I look at my terminal then I saw this.
![image](https://user-images.githubusercontent.com/39723049/74787309-d1446700-52e9-11ea-8de7-5eafbe7b6337.png)

I tried using the ip then zalenium dashboard opens. Hope it also helps others ;)

**Comment by drordk** [comment] 2020-04-23 20:09
> I'm also having this issue with the latest version of the zalenium docker image (dosel/zalenium:3), if I try to start it with just
> `docker run --rm -ti --name zalenium -p 4444:4444 --privileged dosel/zalenium:latest start`
> I get this output:
> 
> ```
> 4/1/2019 11:05:20 AM-- LOG 19:05:20:377033469 Ensuring docker works...
> 4/1/2019 11:05:20 AM-- LOG 19:05:20:505598160 Ensuring docker-selenium is available...
> 4/1/2019 11:05:20 AMhaveged: haveged starting up
> 4/1/2019 11:05:20 AMCopying files for Dashboard...
> 4/1/2019 11:05:20 AMcp: cannot create regular file '/home/seluser/videos/dashboard.html': No such file or directory
> 4/1/2019 11:05:25 AMStarting Nginx reverse proxy...
> 4/1/2019 11:05:25 AMStarting Selenium Hub...
> 4/1/2019 11:05:26 AM...19:05:26.129 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Selenium server version: 3.141.59, revision: unknown
> 4/1/2019 11:05:26 AM19:05:26.215 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Launching Selenium Grid hub on port 4445
> 4/1/2019 11:05:26 AM..19:05:26.576 [main] INFO  d.z.e.z.c.DockerContainerClient - About to clean up any left over DockerSelenium containers created by Zalenium
> 4/1/2019 11:05:27 AM....19:05:27.537 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Starting poller.
> 4/1/2019 11:05:27 AM..19:05:27.936 [main] INFO  d.z.ep.zalenium.aspect.HubAspect - Registering custom Zalenium servlets
> 4/1/2019 11:05:28 AM19:05:28.044 [main] INFO  org.openqa.grid.web.Hub - Selenium Grid hub is up and running
> 4/1/2019 11:05:28 AM19:05:28.045 [main] INFO  org.openqa.grid.web.Hub - Nodes should register to http://10.42.98.28:4445/grid/register/
> 4/1/2019 11:05:28 AM19:05:28.045 [main] INFO  org.openqa.grid.web.Hub - Clients should connect to http://10.42.98.28:4445/wd/hub
> 4/1/2019 11:05:28 AMSelenium Hub started!
> 4/1/2019 11:05:28 AMSauce Labs not enabled...
> 4/1/2019 11:05:28 AMBrowser Stack not enabled...
> 4/1/2019 11:05:28 AMTestingBot not enabled...
> 4/1/2019 11:05:28 AMZalenium is now ready!
> 4/1/2019 11:05:28 AM*************************************** Data Processing Agreement ***************************************
> 4/1/2019 11:05:28 AMBy using this software you agree that the following non-PII (non personally identifiable information)
> 4/1/2019 11:05:28 AMdata will be collected, processed and used by Zalando SE for the purpose of improving our test
> 4/1/2019 11:05:28 AMinfrastructure tools. Anonymisation with respect of the IP address means that only the first two octets
> 4/1/2019 11:05:28 AMof the IP address are collected.
> 4/1/2019 11:05:28 AM
> 4/1/2019 11:05:28 AMSee the complete license at https://github.com/zalando/zalenium/blob/master/LICENSE.md
> 4/1/2019 11:05:28 AM*************************************** Data Processing Agreement ***************************************
> 4/1/2019 11:05:36 AM19:05:36.595 [Thread-10] INFO  d.z.e.z.registry.ZaleniumRegistry - Registered a node http://172.17.0.3:40000
> 4/1/2019 11:05:41 AM19:05:41.815 [Thread-11] INFO  d.z.e.z.registry.ZaleniumRegistry - Registered a node http://172.17.0.4:40001
> ```
> 
> Visiting http://localhost:4444/dashboard gives me a `403 Forbidden` error, and I've confirmed that the file is missing from the `/home/seluser/videos/` in the container.
> 
> However, is looks like `dashboard_template.html` is placed in the `/home/seluser` directory, and can be manually moved to the `videos` directory as `dashboard.html` If I do that, the page will then load, but the styles are missing as it's looking for them at `/dashboard/css/dashboard.css` but the `css` directory doesn't exist in `videos`. Once I manually move the css into that folder, the dashboard will load up correctly, so it looks like it's just some quick path fixes that need to happen.

So you should be able to access it (without changes) via:
[http://localhost:4444/dashboard_template.html](http://localhost:4444/dashboard_template.html)

I had the same issue, tried it (after saw your comment) and this link works.

**Comment by duykhanhrc** [comment] 2021-07-16 09:08
> I was also experience the problem that I can't open zalenium dashboard in localhost:4444/dashboard. Then I look at my terminal then I saw this.
> ![image](https://user-images.githubusercontent.com/39723049/74787309-d1446700-52e9-11ea-8de7-5eafbe7b6337.png)
> 
> I tried using the ip then zalenium dashboard opens. Hope it also helps others ;)

This works for me !
