### ISSUE TITLE
restarted Selenium Containers are not removed from List of tracked Containers

### ISSUE THREAD

**Issue by FrankWue** [zalando/zalenium#751] opened 2018-10-23 07:41 UTC
**Please make sure that you provide enough information for us to help you with this issue. Thank you!**

Zalenium Image Version(s):  3.14.0f 
Docker Version:  18.05.0-ce, build f150324
docker-compose, version:  1.22.0, build f46880fe
OS: Red Hat Enterprise Linux Server release 7.4 (Maipo) 
Docker Command to start Zalenium:  
-- docker-compose.yaml.  --
version: '3.6'
services:
  zalenium:
    container_name: zalenium
    image: dosel/zalenium
    restart: always
    privileged: true
    volumes:
      - /zalenium/videos:/home/seluser/videos
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      zalenium_http_proxy: "http://placeholder.com"
      zalenium_https_proxy: "http://placeholder.com"
      zalenium_no_proxy: "localhost, *.local, 169.254/16, 127.0.0.1, 10.0.0.0/8, 172.19/16"
    ports:
      - "4444:4444"
    command: >
        start
              --timeZone "Europe/Berlin"
              --desiredContainers 2
              --maxDockerSeleniumContainers 8

## Expected Behavior -
Due to the fact that the Selenium containers are terminated after 120 Seconds of idle time. the containers should be marked as inactives and removed from the checklist
## Actual Behavior -
All the terminated containers remain in the list and are checked again with every check cycle although the log says that the node is marked as down and unregistered.

### Here is a Part of my log to show this behaviour -
09:37:13.926 [Thread-14] INFO  d.z.e.z.proxy.AutoStartProxySet - Registered a container b0aa8ead1ef93966d3cc319f629b9a565c17d2967b645318147ed0ed743a9e88 http://172.19.0.3:40004.
09:38:30.219 [RemoteProxy failure poller thread for http://172.19.0.3:40001] INFO  o.o.g.s.proxy.DefaultRemoteProxy - Unregistering the node http://172.19.0.3:40001 because it's been down for 91003 milliseconds
09:38:30.219 [RemoteProxy failure poller thread for http://172.19.0.3:40001] INFO  o.o.g.s.proxy.DefaultRemoteProxy - Unregistering the node http://172.19.0.3:40001 because it's been down for 182007 milliseconds
09:38:37.339 [RemoteProxy failure poller thread for http://172.19.0.3:40002] INFO  o.o.g.s.proxy.DefaultRemoteProxy - Marking the node http://172.19.0.3:40002 as down: cannot reach the node for 2 tries
09:38:52.123 [RemoteProxy failure poller thread for http://172.19.0.3:40000] INFO  o.o.g.s.proxy.DefaultRemoteProxy - Unregistering the node http://172.19.0.3:40000 because it's been down for 100004 milliseconds
09:38:52.124 [RemoteProxy failure poller thread for http://172.19.0.3:40000] INFO  o.o.g.s.proxy.DefaultRemoteProxy - Unregistering the node http://172.19.0.3:40000 because it's been down for 203012 milliseconds
09:38:52.124 [RemoteProxy failure poller thread for http://172.19.0.3:40000] INFO  o.o.g.s.proxy.DefaultRemoteProxy - Unregistering the node http://172.19.0.3:40000 because it's been down for 303016 milliseconds
09:39:15.164 [AutoStartProxyPoolPoller] INFO  d.z.e.z.c.DockerContainerClient - Container ContainerCreationStatus [isCreated=true, containerName=zalenium_ukXC6C, containerId=b0aa8ead1ef93966d3cc319f629b9a565c17d2967b645318147ed0ed743a9e88, nodePort=40004] not found - it is terminated.
09:39:15.164 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Container ContainerCreationStatus [isCreated=true, containerName=zalenium_ukXC6C, containerId=b0aa8ead1ef93966d3cc319f629b9a565c17d2967b645318147ed0ed743a9e88, nodePort=40004] is terminated. Removing from tracked set.
09:39:15.164 [AutoStartProxyPoolPoller] INFO  d.z.e.z.p.DockerSeleniumRemoteProxy - b0aa8ead1ef93966d3cc319f629b9a565c17d2967b645318147ed0ed743a9e88 Marking node down.
09:39:16.164 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - AutoStarting container, because 0 is less than min 1
09:39:16.638 [AutoStartProxyPoolPoller] INFO  d.z.e.z.p.DockeredSeleniumStarter - Created container [zalenium_KmhaWe] with dimensions [(1920, 1080)] and tz [sun.util.calendar.ZoneInfo[id="Europe/Berlin",offset=3600000,dstSavings=3600000,useDaylight=true,transitions=143,lastRule=java.util.SimpleTimeZone[id=Europe/Berlin,offset=3600000,dstSavings=3600000,useDaylight=true,startYear=0,startMode=2,startMonth=2,startDay=-1,startDayOfWeek=1,startTime=3600000,startTimeMode=2,endMode=2,endMonth=9,endDay=-1,endDayOfWeek=1,endTime=3600000,endTimeMode=2]]].
09:39:16.639 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Created ContainerCreationStatus [isCreated=true, containerName=zalenium_KmhaWe, containerId=eee5e2bc3265aae7fb9e9835fb3eabaabd2a9792ac7849f40de78b7956069213, nodePort=40005].
09:39:20.077 [Thread-15] INFO  d.z.e.z.registry.ZaleniumRegistry - Registered a node http://172.19.0.3:40005
09:39:20.077 [Thread-15] INFO  d.z.e.z.proxy.AutoStartProxySet - Registered a container eee5e2bc3265aae7fb9e9835fb3eabaabd2a9792ac7849f40de78b7956069213 http://172.19.0.3:40005.
09:39:20.761 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Container zalenium_KmhaWe started after 4122.
09:40:01.222 [RemoteProxy failure poller thread for http://172.19.0.3:40001] INFO  o.o.g.s.proxy.DefaultRemoteProxy - Unregistering the node http://172.19.0.3:40001 because it's been down for 91003 milliseconds
09:40:01.223 [RemoteProxy failure poller thread for http://172.19.0.3:40001] INFO  o.o.g.s.proxy.DefaultRemoteProxy - Unregistering the node http://172.19.0.3:40001 because it's been down for 182007 milliseconds
09:40:01.223 [RemoteProxy failure poller thread for http://172.19.0.3:40001] INFO  o.o.g.s.proxy.DefaultRemoteProxy - Unregistering the node http://172.19.0.3:40001 because it's been down for 273010 milliseconds
09:40:29.342 [RemoteProxy failure poller thread for http://172.19.0.3:40002] INFO  o.o.g.s.proxy.DefaultRemoteProxy - Unregistering the node http://172.19.0.3:40002 because it's been down for 112003 milliseconds
09:40:32.126 [RemoteProxy failure poller thread for http://172.19.0.3:40000] INFO  o.o.g.s.proxy.DefaultRemoteProxy - Unregistering the node http://172.19.0.3:40000 because it's been down for 100004 milliseconds
09:40:32.127 [RemoteProxy failure poller thread for http://172.19.0.3:40000] INFO  o.o.g.s.proxy.DefaultRemoteProxy - Unregistering the node http://172.19.0.3:40000 because it's been down for 203012 milliseconds
09:40:32.127 [RemoteProxy failure poller thread for http://172.19.0.3:40000] INFO  o.o.g.s.proxy.DefaultRemoteProxy - Unregistering the node http://172.19.0.3:40000 because it's been down for 303016 milliseconds
09:40:32.127 [RemoteProxy failure poller thread for http://172.19.0.3:40000] INFO  o.o.g.s.proxy.DefaultRemoteProxy - Unregistering the node http://172.19.0.3:40000 because it's been down for 403019 milliseconds
09:40:55.795 [RemoteProxy failure poller thread for http://172.19.0.3:40003] INFO  o.o.g.s.proxy.DefaultRemoteProxy - Marking the node http://172.19.0.3:40003 as down: cannot reach the node for 2 tries
09:41:21.149 [AutoStartProxyPoolPoller] INFO  d.z.e.z.c.DockerContainerClient - Container ContainerCreationStatus [isCreated=true, containerName=zalenium_KmhaWe, containerId=eee5e2bc3265aae7fb9e9835fb3eabaabd2a9792ac7849f40de78b7956069213, nodePort=40005] not found - it is terminated.
09:41:21.149 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Container ContainerCreationStatus [isCreated=true, containerName=zalenium_KmhaWe, containerId=eee5e2bc3265aae7fb9e9835fb3eabaabd2a9792ac7849f40de78b7956069213, nodePort=40005] is terminated. Removing from tracked set.
09:41:21.149 [AutoStartProxyPoolPoller] INFO  d.z.e.z.p.DockerSeleniumRemoteProxy - eee5e2bc3265aae7fb9e9835fb3eabaabd2a9792ac7849f40de78b7956069213 Marking node down.
09:41:22.149 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - AutoStarting container, because 0 is less than min 1
### -

**Comment by FrankWue** [comment] 2018-10-23 07:44
The worst Problem is that the logfile is growing faster with every check cycle as there are more lines for each terminated node

**Comment by diemol** [comment] 2018-10-29 13:29
Hi @FrankWue,

This looks just like #679. When the proxy is not properly configured, this behaviour of containers being shutdown and new ones started after two minutes is shown.

I was able to see it when I was troubleshooting #679 and I also misconfigured the proxy. Please have a look at this [comment](https://github.com/zalando/zalenium/issues/679#issuecomment-433008829). Also double check that the proxy url is included in the no_proxy part (the container should not use the proxy to access the proxy itself).

I'll close it since it looks like a duplicate, if not, feel free to reopen.

**Closed by diemol** 2018-10-29 13:29 UTC

**Comment by FrankWue** [comment] 2018-10-31 10:02
This issue is not a duplicate of  #679 since it is not about "org.openqa.selenium.WebDriverException: cannot forward the request Connect ..."
The behavior is that the Selenium container terminates always after 2 Minutes of idle time and the registered nodes are not unregistered although it is stated in the logs

**Comment by diemol** [comment] 2018-10-31 10:14
I know what you mean, the issue name is different from yours, but the cause is the same one, proxy configuration.

The difference is that in the referenced issues, they were running the test and bumping into that message. If you do not run any tests, you end up having your situation, containers being stopped and new ones started every two minutes.

The reason for both is the same, proxy configuration. What you could do first is just to configure proxy only using elgalu/selenium, when that is working, you can try it with Zalenium.
