### ISSUE TITLE
Zalenium with Minikube on AWS EC2

### ISSUE THREAD

**Issue by sinujamal** [zalando/zalenium#691] opened 2018-08-09 12:36 UTC
**Please make sure that you provide enough information for us to help you with this issue. Thank you!**

Zalenium Image Version(s):  
latest
Minikube Version:  
v0.28.2

OS: 
Ubuntu 16.094
Docker Command to start Zalenium:  
Using minikube
If using Kubernetes, specify your environment, and if relevant your manifests:  

## Expected Behavior -
When I run minikube service zalenium, I get the URL http://172.31.95.134:31196.

## Actual Behavior -
But when opened in a browser the 502 Bad Gateway error is being thrown.
How to get a browser instance in my TestNG when running zalenium in Minikube

**Comment by diemol** [comment] 2018-08-09 21:03
This looks like a duplicate of #681, please follow that issue which should be solved soon.

**Closed by diemol** 2018-08-09 21:03 UTC
Labels: duplicate
