### ISSUE TITLE
Zalenium hub URL throws exception, cannot connect webdriver

### ISSUE THREAD

**Issue by schlomo** [zalando/zalenium#188] opened 2017-07-18 15:27 UTC
Following the instructions I started Zalenium with `curl -sSL https://raw.githubusercontent.com/dosel/t/i/p | bash -s start` and the Console looks fine. When I check http://localhost:4444/wd/hub it only shows me a stack trace. Pointing a webdriver at his URL also doesn't work, for example this code fails:
```python
driver = webdriver.Remote(
    command_executor='http://localhost:4444/wd/hub',
    desired_capabilities=DesiredCapabilities.FIREFOX)
```
According to http://selenium-python.readthedocs.io/getting-started.html#using-selenium-with-remote-webdriver this should work.

The stack trace is this:
```json
{
    "status": 13,
    "value": {
        "class": "java.lang.NullPointerException",
        "stackTrace": [
            {
                "className": "org.openqa.grid.internal.ExternalSessionKey",
                "fileName": "ExternalSessionKey.java",
                "lineNumber": 77,
                "methodName": "fromWebDriverRequest"
            },
            {
                "className": "org.openqa.grid.web.servlet.handler.WebDriverRequest",
                "fileName": "WebDriverRequest.java",
                "lineNumber": 58,
                "methodName": "extractSession"
            },
            {
                "className": "org.openqa.grid.web.servlet.handler.RequestHandler",
                "fileName": "RequestHandler.java",
                "lineNumber": 231,
                "methodName": "getSession"
            },
            {
                "className": "org.openqa.grid.web.servlet.handler.RequestHandler",
                "fileName": "RequestHandler.java",
                "lineNumber": 117,
                "methodName": "process"
            },
            {
                "className": "org.openqa.grid.web.servlet.DriverServlet",
                "fileName": "DriverServlet.java",
                "lineNumber": 83,
                "methodName": "process"
            },
            {
                "className": "org.openqa.grid.web.servlet.DriverServlet",
                "fileName": "DriverServlet.java",
                "lineNumber": 61,
                "methodName": "doGet"
            },
            {
                "className": "javax.servlet.http.HttpServlet",
                "fileName": "HttpServlet.java",
                "lineNumber": 687,
                "methodName": "service"
            },
            {
                "className": "javax.servlet.http.HttpServlet",
                "fileName": "HttpServlet.java",
                "lineNumber": 790,
                "methodName": "service"
            },
            {
                "className": "org.seleniumhq.jetty9.servlet.ServletHolder",
                "fileName": "ServletHolder.java",
                "lineNumber": 841,
                "methodName": "handle"
            },
            {
                "className": "org.seleniumhq.jetty9.servlet.ServletHandler",
                "fileName": "ServletHandler.java",
                "lineNumber": 543,
                "methodName": "doHandle"
            },
            {
                "className": "org.seleniumhq.jetty9.server.handler.ScopedHandler",
                "fileName": "ScopedHandler.java",
                "lineNumber": 188,
                "methodName": "nextHandle"
            },
            {
                "className": "org.seleniumhq.jetty9.server.session.SessionHandler",
                "fileName": "SessionHandler.java",
                "lineNumber": 1584,
                "methodName": "doHandle"
            },
            {
                "className": "org.seleniumhq.jetty9.server.handler.ScopedHandler",
                "fileName": "ScopedHandler.java",
                "lineNumber": 188,
                "methodName": "nextHandle"
            },
            {
                "className": "org.seleniumhq.jetty9.server.handler.ContextHandler",
                "fileName": "ContextHandler.java",
                "lineNumber": 1228,
                "methodName": "doHandle"
            },
            {
                "className": "org.seleniumhq.jetty9.server.handler.ScopedHandler",
                "fileName": "ScopedHandler.java",
                "lineNumber": 168,
                "methodName": "nextScope"
            },
            {
                "className": "org.seleniumhq.jetty9.servlet.ServletHandler",
                "fileName": "ServletHandler.java",
                "lineNumber": 481,
                "methodName": "doScope"
            },
            {
                "className": "org.seleniumhq.jetty9.server.session.SessionHandler",
                "fileName": "SessionHandler.java",
                "lineNumber": 1553,
                "methodName": "doScope"
            },
            {
                "className": "org.seleniumhq.jetty9.server.handler.ScopedHandler",
                "fileName": "ScopedHandler.java",
                "lineNumber": 166,
                "methodName": "nextScope"
            },
            {
                "className": "org.seleniumhq.jetty9.server.handler.ContextHandler",
                "fileName": "ContextHandler.java",
                "lineNumber": 1130,
                "methodName": "doScope"
            },
            {
                "className": "org.seleniumhq.jetty9.server.handler.ScopedHandler",
                "fileName": "ScopedHandler.java",
                "lineNumber": 141,
                "methodName": "handle"
            },
            {
                "className": "org.seleniumhq.jetty9.server.handler.HandlerWrapper",
                "fileName": "HandlerWrapper.java",
                "lineNumber": 132,
                "methodName": "handle"
            },
            {
                "className": "org.seleniumhq.jetty9.server.Server",
                "fileName": "Server.java",
                "lineNumber": 564,
                "methodName": "handle"
            },
            {
                "className": "org.seleniumhq.jetty9.server.HttpChannel",
                "fileName": "HttpChannel.java",
                "lineNumber": 320,
                "methodName": "handle"
            },
            {
                "className": "org.seleniumhq.jetty9.server.HttpConnection",
                "fileName": "HttpConnection.java",
                "lineNumber": 251,
                "methodName": "onFillable"
            },
            {
                "className": "org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback",
                "fileName": "AbstractConnection.java",
                "lineNumber": 279,
                "methodName": "succeeded"
            },
            {
                "className": "org.seleniumhq.jetty9.io.FillInterest",
                "fileName": "FillInterest.java",
                "lineNumber": 112,
                "methodName": "fillable"
            },
            {
                "className": "org.seleniumhq.jetty9.io.ChannelEndPoint$2",
                "fileName": "ChannelEndPoint.java",
                "lineNumber": 124,
                "methodName": "run"
            },
            {
                "className": "org.seleniumhq.jetty9.util.thread.Invocable",
                "fileName": "Invocable.java",
                "lineNumber": 122,
                "methodName": "invokePreferred"
            },
            {
                "className": "org.seleniumhq.jetty9.util.thread.strategy.ExecutingExecutionStrategy",
                "fileName": "ExecutingExecutionStrategy.java",
                "lineNumber": 58,
                "methodName": "invoke"
            },
            {
                "className": "org.seleniumhq.jetty9.util.thread.strategy.ExecuteProduceConsume",
                "fileName": "ExecuteProduceConsume.java",
                "lineNumber": 201,
                "methodName": "produceConsume"
            },
            {
                "className": "org.seleniumhq.jetty9.util.thread.strategy.ExecuteProduceConsume",
                "fileName": "ExecuteProduceConsume.java",
                "lineNumber": 133,
                "methodName": "run"
            },
            {
                "className": "org.seleniumhq.jetty9.util.thread.QueuedThreadPool",
                "fileName": "QueuedThreadPool.java",
                "lineNumber": 672,
                "methodName": "runJob"
            },
            {
                "className": "org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2",
                "fileName": "QueuedThreadPool.java",
                "lineNumber": 590,
                "methodName": "run"
            },
            {
                "className": "java.lang.Thread",
                "fileName": "Thread.java",
                "lineNumber": 748,
                "methodName": "run"
            }
        ]
    }
}
```

**Comment by diemol** [comment] 2017-07-18 21:19
Hi @schlomo, thanks for trying Zalenium!

We have two things here. 

First, the stacktrace you get when accessing http://localhost:4444/wd/hub is normal. To be honest I haven't dig the logic of it since that one is meant more for WebDriver commands. The response is the standard you get from a Selenium Grid.

The second issue you are getting is well known for the Python bindings, the issue is being tracked here: https://github.com/SeleniumHQ/selenium/issues/3808
Some other people have bumped into the same situation, like in this case: https://github.com/elgalu/docker-selenium/issues/166 
That is why we have not upgraded Zalenium to use the latest version of Selenium. Currently, we are using 3.3.1 (not 3.4.0).

The simplest way to fix that is to use the version 3.3.1 of the bindings.
```
pip uninstall selenium
pip install selenium==3.3.1
```
After that, you should be able to run your script again.

Let us know how it went.

PS: If you are using the example from the "Getting Started" page in the Python bindings, change the `driver.close()` command to `driver.quit()`, to properly close the Selenium session.

**Comment by schlomo** [comment] 2017-07-20 08:17
Thanks a lot, that helped.

If you could anyhow get rid of the stack trace from http://localhost:4444/wd/hub that would probably help a lot of new users to think beyond blaming Zalenium/Selenium. If that URL expects a POST with data then it could easily respond to a GET with a simple page that contains links to the documentation or getting started guide.

**Comment by elgalu** [comment] 2017-07-20 17:22
It's a Selenium (not Zalenium) design issue.

At best a PR to upstream Selenium should be sent to fix it IMHO
https://github.com/SeleniumHQ/selenium

**Comment by diemol** [comment] 2017-07-22 09:30
I don't really know if it is a design issue or if it was meant to be like that.

If you download the Selenium jar and start it locally, you'll get the same response.

I completely agree that the response might be misleading for a person who is starting to use Selenium, nevertheless the url http://localhost:4444/wd/hub is meant to be used to send and receive WebDriver commands, and more than that, as @elgalu mentions, it is not in the scope nor control of Zalenium to change it since it comes like that by default. 

I'm happy that you can run Zalenium and your UI tests @schlomo! Thanks for the blog post!

I'll close this issue since the initial request was solved based on our scope.

**Closed by diemol** 2017-07-22 09:30 UTC
