### ISSUE TITLE
running 2 or more instances of zalenium not working anymore

### ISSUE THREAD

**Issue by borisivan** [zalando/zalenium#362] opened 2017-12-11 21:45 UTC
**Please make sure that you provide enough information for us to help you with this issue. Thank you!**

Zalenium Image Version(s):  
3.8.1.c. And my suite always does a pull before execution.

Docker Version:  
17.04.0-ce

OS: 
SLES 12 GA

Docker Command to start Zalenium:
forgive the commas -- these are the arguments separated by commas. Works fine.

docker, run, -tid, --name=obfuscated, -p, 4445:4444, -v, /var/run/docker.sock:/var/run/docker.sock, -v, /usr/bin/docker:/usr/bin/docker, -v, /tmp/videos/obfuscated:/home/seluser/videos, -v, /tmp/Downloads/obfuscated:/tmp/node/home/seluser/Downloads, --privileged, dosel/zalenium, start, --chromeContainers, 6, --screenWidth, 1920, --screenHeight, 1080, --firefoxContainers, 0, --videoRecordingEnabled, true, --maxTestSessions, 150

## Expected Behavior -
There was already an instance of Zalenium running (and was mapping host 4444 to zalenium 4444). When I attempt to launch the instance above (which dynamically determines that host 4444 is already mapped, so it correctly attempts to map host 4445 to new zalenium 4444....), this should create 6 chrome containers and run tests. This has worked for months. I often have 3 zalenium instances (each with 6 subcontainers) running the same suite against a different device-under-test, at the same time.

## Actual Behavior -
The existing suite (which had 6 child containers) continued to run fine. But the new instance of zalenium failed to bring up the 6th child container. It did bring up 5... but that's it. I wait 30 seconds for zalenium to initialize, and then I check to see what containers are up and running. In this case, I see 5 child containers started in about 5 seconds. But there was either no attempt in the next 25 seconds to bring up that last container, or it failed. In either case, there were 5 child containers, not 6. This has happened often today -- not sure if it happens every time, or if this is intermittent, but it's happened at least 7-8 times today.

I notice that zalenium's strategy for finding the port that the child container should use is to start  at 50000 and just walk up. Was any change made there to have it stop at 50010? Here is what I am seeing:

[InputStream]com.spotify.docker.client.exceptions.DockerRequestException: Request error: POST unix://localhost:80/containers/c05fe4694944124cbf3a8fb7fddda64c6ab577d5adfd766e946f205611f8cf26/start: 500, body: {"message":"driver failed programming external connectivity on endpoint zal-obfuscated_40001 (ace3ffa1f7c86e4d67c3459e419e42f6563365a72a6de13aabe4f7de822eb275): Bind for 0.0.0.0:**50001 failed: port is already allocated**"}

(we always get the errors above when launching a second or third suite, normally it's benign).

For the existing suite running, the _child_ containers were using 50000 -> 50005. For the suite I was trying to launch, it successfully grabbed 50006 -> 50010 (after seeing the error messages above, repeated for ports 50000 -> 50005) But I see no attempt in the zalenium log to grab 50011 -- nothing. Neither 40011 or 50011 is in the logs, even as an error message.

Here are the containers when it's done initializing the second suite -- you can see that this docker host has the 6 child containers (and zalenium master container) for the _original_ suite that has been running for 14 minutes. But the _new_ suite only has 5 child containers (and zalenium master container). There should be 6 child containers. After launching zalenium I wait 30 seconds for it to initialize, and since you can see that the 5 child containers in the new suite have been running for 20 seconds or more, I really don't think it's because things got slow/busy. It's as if zalenium never tries to start that 6th container for the second suite.

c05c9d654c29        elgalu/selenium:latest   "entry.sh"               22 seconds ago      Up 20 seconds       0.0.0.0:40010->40010/tcp, 0.0.0.0:50010->50010/tcp  zal-obfuscated2_40010
825adabfa0b7        elgalu/selenium:latest   "entry.sh"               22 seconds ago      Up 20 seconds       0.0.0.0:40009->40009/tcp, 0.0.0.0:50009->50009/tcp   zal-obfuscated2_40009
75ea7a5a2020        elgalu/selenium:latest   "entry.sh"               25 seconds ago      Up 22 seconds       0.0.0.0:40008->40008/tcp, 0.0.0.0:50008->50008/tcp   zal-obfuscated2_40008
53dac79ac21c        elgalu/selenium:latest   "entry.sh"               25 seconds ago      Up 22 seconds       0.0.0.0:40007->40007/tcp, 0.0.0.0:50007->50007/tcp   zal-obfuscated2_40007
31f4b8a220ad        elgalu/selenium:latest   "entry.sh"               25 seconds ago      Up 23 seconds       0.0.0.0:40006->40006/tcp, 0.0.0.0:50006->50006/tcp   zal-obfuscated2_40006
2940ded06ea7        dosel/zalenium           "entry.sh start --..."   31 seconds ago      Up 30 seconds       4445/tcp, 0.0.0.0:4445->4444/tcp                     zal-obfuscated2
2b00d001f69c        elgalu/selenium:latest   "entry.sh"               14 minutes ago      Up 14 minutes       0.0.0.0:40005->40005/tcp, 0.0.0.0:50005->50005/tcp   zal-obfuscated1_40005
af8d6bbff575        elgalu/selenium:latest   "entry.sh"               14 minutes ago      Up 14 minutes       0.0.0.0:40004->40004/tcp, 0.0.0.0:50004->50004/tcp   zal-obfuscated1_40004
2d1df2e090b4        elgalu/selenium:latest   "entry.sh"               14 minutes ago      Up 14 minutes       0.0.0.0:40003->40003/tcp, 0.0.0.0:50003->50003/tcp   zal-obfuscated1_40003
142ad716df04        elgalu/selenium:latest   "entry.sh"               14 minutes ago      Up 14 minutes       0.0.0.0:40002->40002/tcp, 0.0.0.0:50002->50002/tcp   zal-obfuscated1_40002
61edcf1ec9d5        elgalu/selenium:latest   "entry.sh"               14 minutes ago      Up 14 minutes       0.0.0.0:40001->40001/tcp, 0.0.0.0:50001->50001/tcp   zal-obfuscated1_40001
5c9664b2fd47        elgalu/selenium:latest   "entry.sh"               14 minutes ago      Up 14 minutes       0.0.0.0:40000->40000/tcp, 0.0.0.0:50000->50000/tcp   zal-obfuscated1_40000
093caddcb0fa        dosel/zalenium           "entry.sh start --..."   14 minutes ago      Up 14 minutes       0.0.0.0:4444->4444/tcp, 4445/tcp                     zal-obfuscated1 

Again, this functionality has been working great for months -- sometimes I have 3 suites in parallel. But something seems to have changed. This is very important for us, it's currently breaking continuous integration testing. Any help is greatly appreciated.

**Comment by borisivan** [comment] 2017-12-12 15:47
Reproducible. The second suite always starts child containers 1-5, does not seem to even attempt to create child container #6.

Not sure if it's relevant, but I saw the commits re: registry / registryCycle / etc -- could any of that be related?

With the 1st suite having the 6 child containers consume 40000-40005 <-> 50000-50005, and the second suite trying to create 6 child containers, but only having 5 successfully created, which end up with 40006-40010 <-> 50006-50010, it seems like an interesting magic number re: the successful containers overall: 40000-40010 and 50000-50010. But 40011 <-> 50011 should have been attempted (and was previously working), but I can't even see that port in the logs for the zalenium container.

As a side note, I do notice that when the second suite starts, zalenium simply tries to find room for the new containers, starting at 40000. But since zalenium already consumes with the existing suite from 40000-40005, I see that Zalenium walks up to find the next available port. Not sure what I'd recommend for a better solution, as multiple existing suites might each use different numbers of containers, and one suite might finish earlier than another suite, freeing up a range of ports inbetween the ones suite 1 and suite 3 are still using, etc. But it would be interesting to know what the current algorithm does (and what delay might exist between looking from one port to the next, etc).

This is currently some significant grief as we just brought new personnel into the test effort and had a solution to launch more than 1 instance of the suite in parallel, but it looks like this just broke a couple days ago, and we need to manually restrict execution of the suite on this continuous integration server now.

Is there anything I can provide re: logs or test a private image?

**Comment by diemol** [comment] 2017-12-12 18:12
Hi @borisivan,

I could not reproduce it, but I can imagine it to happen due to port conflicts. The current solution to find ports works but it is just a dirty one. We'll think about a nicer solution.

One question, are the 2 or more instances started around the same time?

**Comment by borisivan** [comment] 2017-12-12 18:25
Hi @diemol, they were started ~ 14 minutes apart, note the output above re: the correct set of containers up 14 minutes, then the next set up ~20 seconds. That output is from the docker ps -a command, showing all the containers 30 seconds after I started Zalenum.. and then the new suite aborts itself because it knows was missing a zalenium container (I have it check the output of that command).

Since the second one starts at 40000 (and 40000-40005 <-> 50000-50005 are already in use...) -- what does the algorithm do to find the next port -- I assume it 'walks up', since I see the second suite use 40006-40010 <-> 50006-50010. But does the algorithm walk up forever, or up until a certain limit? Is the limit a certain port range, or certain amount of time? And if time, is there a delay inbetween each attempt? If so, then if it was set to abort after not finding a port in 10 seconds, with a 1 second delay between checking the next port number.....

**Comment by diemol** [comment] 2017-12-12 19:00
@borisivan, can you please try with this image?
diemol/zalenium:3.8.1d-SNAPSHOT

I realised that we don't need to map the ports to the host anyway, only the hub port. I tried it quickly and it showed good results, I still need to run it through the CI, but I thought you could pull it and help me test it locally over there.

**Comment by diemol** [comment] 2017-12-13 12:20
Hi @borisivan,

did you have the chance to try it?

**Comment by borisivan** [comment] 2017-12-13 13:13
Not yet, but will be able to today. Thx!

**Comment by borisivan** [comment] 2017-12-13 21:43
difficult to say if it's safe. I was able to start 2 suites and all containers started this time, but:

1) I didn't try this on the same system that previously showed the problem -- waiting for that to free up, and want to try it there. Will advise.

2) In the suite of ~ 100 tests, both suite instance 1 and suite instance 2 were running along OK, but then I ran into a couple of problems that I can't know for sure if they're due to your recent change or not. I think I've seen this once or twice before:

org.openqa.selenium.NoSuchSessionException: Session ID is null. Using WebDriver after calling quit()?
Build info: version: '3.7.0', revision: '2321c73', time: '2017-11-02T22:22:35.584Z'
System info: host: 'ubuntu1604', ip: '10.141.56.42', os.name: 'Linux', os.arch: 'amd64', os.version: '4.4.0-96-generic', java.version: '1.8.0_151'
Driver info: driver.version: RemoteWebDriver
	at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:131)
	at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:600)
	at org.openqa.selenium.remote.RemoteWebDriver.findElements(RemoteWebDriver.java:397)

and an attempt at another test a little later:

org.openqa.selenium.WebDriverException: Error forwarding the new session Error forwarding the request Connect to 172.17.0.14:40001 [/172.17.0.14] failed: Connection refused (Connection refused)

I never see this when running one instance of the suite (though I have the tests running in parallel across 6 child containers). When I would run 2 instances of the suite previously, I think I may have seen this a couple times, so it might be a timing problem when the machine gets low on resources, in general. Not sure.

Will try a few more times, including on the (more powerful) SLES 12 node when available.

**Comment by diemol** [comment] 2017-12-14 13:20
Sure, no problem.

Yes, errors like that can be seen when many containers are used and not too many resources are available. But I almost never see them when I use powerful machines.

**Comment by diemol** [comment] 2017-12-20 13:16
Hi @borisivan,

The changes we made for this are being released right now, https://github.com/zalando/zalenium/releases/tag/3.8.1d

Whenever you can, please give us some feedback about it. I'll close this issue for now, but if you still have the problem, please reopen it.

**Closed by diemol** 2017-12-20 13:16 UTC
Labels: waiting-answer, waiting-retest
