### ISSUE TITLE
Setting maxTestSessions to 0 should disable node shutdown

### ISSUE THREAD

**Issue by bernardomk** [zalando/zalenium#933] opened 2019-04-11 21:39 UTC
## 🚀 Feature Proposal

A clear and concise description of what the feature is.
Currently there's no way to disable node replacement after maxTestSessions is reached. The proposal is to change never shutdown the node if maxTestSessions == 0. 

## Motivation

We experienced issues because nodes got shut down while we triggered it, we would want to manage pod replacement ourselves, e.g.: k8s CronJob.

## Example

Set maxTestSessions = 0 and nodes are never shutdown after # of test is reached.

**Comment by diemol** [comment] 2019-04-25 19:22
Hi @bernardomk, it does not sound so crazy, nevertheless you should keep in mind that at some point the container will crash (just because opening and closing a browser lots of times won't end up in a good way). 
But that does not sound like the best approach for your issue, if nodes got shut down, would not it be better to find out the root cause?

**Comment by diemol** [comment] 2019-05-02 13:09
Merging into #654 and looking for contributors!

**Closed by diemol** 2019-05-02 13:09 UTC
Labels: waiting-answer
