### ISSUE TITLE
Firefox Node idelTimeout SetCapability returns "W3C payload contained keys that do not comply with the spec: [tz, idleTimeout]"

### ISSUE THREAD

**Issue by mitchellmaler** [zalando/zalenium#269] opened 2017-10-10 19:44 UTC
I have been trying to prove out using Zalenium for our Selenium tests and everything have been working smoothly except when I try to set the idleTimeout and/or tz values for Firefox. 

Our tests are written in C# using the FirefoxOptions object to set the options for the WebDriver. It then is converted to ICapabilities using the ToCapabilities() method before creating the RemoteWebDriver. Here is where I create a cast to DesiredCapabilities so I can add:
```
desiredCapabilities.SetCapability("idleTimeout", 180);
desiredCapabilities.SetCapability("tz", "America/Chicago");
```

When running the test the Firefox node returns the error in the Zalenium logs ```Caused by: java.lang.IllegalArgumentException: W3C payload contained keys that do not comply with the spec: [tz, idleTimeout]```

I also tried calling the FirefoxOptions AddAdditionalCapability("idleTimeout", 180); method and when the node is created I receive the error: ```System.InvalidOperationException : Invalid moz:firefoxOptions field idleTimeout```

**Comment by diemol** [comment] 2017-10-17 22:32
Hi @mitchellmaler,

Can you please show me the whole code snipped where you create the capabilities and the remote web driver? Do you know if this only happens in C#?

**Comment by mitchellmaler** [comment] 2017-10-18 15:16
Here is the code I am using to set the capabilities. I have only wrote this using C# so I do not know if it is an issue with other languages.
```
FirefoxProfile firefoxHeadlessProfile = new FirefoxProfile
{
    DeleteAfterUse = true
};
firefoxHeadlessProfile.SetPreference("browser.cache.disk.enable", false);
firefoxHeadlessProfile.SetPreference("browser.cache.memory.enable", false);
firefoxHeadlessProfile.SetPreference("browser.cache.offline.enable", false);
firefoxHeadlessProfile.SetPreference("network.http.use-cache", false);
FirefoxOptions firefoxHeadlessOptions = new FirefoxOptions
{
    Profile = firefoxHeadlessProfile
};
firefoxHeadlessOptions.AddArgument("--headless");
// Cast to DesiredCapabilities from the ICapabilities interface to make it mutable
DesiredCapabilities desiredCapabilities = (DesiredCapabilities) firefoxHeadlessOptions.ToCapabilities();
desiredCapabilities.SetCapability("idleTimeout", 300);
desiredCapabilities.SetCapability("tz", "America/Chicago");
desiredCapabilities.SetCapability("recordVideo", EnableZaleniumVideoRecording);
IWebDriver WebDriver = new RemoteWebDriver(GridHubUri, capabilities, GridCommandTimeout);
```

When I run that code for Firefox the hub prints out a bunch of letters and then ends with: 
```
...,"args":["--headless"]},"idleTimeout":300,"tz":"America/Chicago","recordVideo":false}]}}
        at org.openqa.grid.web.servlet.handler.WebDriverRequest.extractDesiredCapability(WebDriverRequest.java:78)
        at org.openqa.grid.web.servlet.handler.SeleniumBasedRequest.<init>(SeleniumBasedRequest.java:102)
        at org.openqa.grid.web.servlet.handler.WebDriverRequest.<init>(WebDriverRequest.java:38)
        at org.openqa.grid.web.servlet.handler.WebDriverRequestFactory.createFromRequest(WebDriverRequestFactory.java:30)
        at org.openqa.grid.web.servlet.handler.SeleniumBasedRequest.createFromRequest(SeleniumBasedRequest.java:73)
        at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:82)
        ... 29 common frames omitted
Caused by: java.lang.IllegalArgumentException: W3C payload contained keys that do not comply with the spec: [tz, idleTimeout, recordVideo]
        at org.openqa.selenium.remote.server.NewSessionPayload.validateSpecCompliance(NewSessionPayload.java:179)
        at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:372)
        at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
        at java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1235)
        at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
        at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
        at java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:708)
        at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:499)
        at org.openqa.selenium.remote.server.NewSessionPayload.validate(NewSessionPayload.java:164)
        at org.openqa.selenium.remote.server.NewSessionPayload.<init>(NewSessionPayload.java:146)
        at org.openqa.grid.web.servlet.handler.WebDriverRequest.extractDesiredCapability(WebDriverRequest.java:68)
        ... 34 common frames omitted
```

**Comment by diemol** [comment] 2017-12-10 23:40
Hi @mitchellmaler,

Do you still have this problem? I tried the Java bindings and I was not able to reproduce it. Maybe it is related to the .NET bindings?

**Comment by mitchellmaler** [comment] 2017-12-11 03:46
Yea this is still an issue. I just tested it out with the newest versions of dosel/zalenium using elgalu/selenium. I tried converting to DesiredCapabilities type and adding the additional capability but received the same error above. 
```
,"idleTimeout":300}]}}
	at org.openqa.grid.web.servlet.handler.WebDriverRequest.extractDesiredCapability(WebDriverRequest.java:76)
	at org.openqa.grid.web.servlet.handler.SeleniumBasedRequest.<init>(SeleniumBasedRequest.java:102)
	at org.openqa.grid.web.servlet.handler.WebDriverRequest.<init>(WebDriverRequest.java:36)
	at org.openqa.grid.web.servlet.handler.WebDriverRequestFactory.createFromRequest(WebDriverRequestFactory.java:30)
	at org.openqa.grid.web.servlet.handler.SeleniumBasedRequest.createFromRequest(SeleniumBasedRequest.java:73)
	at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:82)
	... 29 more
Caused by: java.lang.IllegalArgumentException: Illegal key values seen in w3c capabilities: [idleTimeout]
	at org.openqa.selenium.remote.NewSessionPayload.lambda$validate$6(NewSessionPayload.java:211)
	at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:372)
	at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:373)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:373)
	at java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1235)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.openqa.selenium.remote.NewSessionPayload.validate(NewSessionPayload.java:215)
	at org.openqa.selenium.remote.NewSessionPayload.<init>(NewSessionPayload.java:163)
	at org.openqa.selenium.remote.NewSessionPayload.create(NewSessionPayload.java:118)
	at org.openqa.grid.web.servlet.handler.WebDriverRequest.extractDesiredCapability(WebDriverRequest.java:66)
	... 34 more
```

I then tried directly calling the FirefoxOptions AddAdditionalCapability method which then did allow the grid to create the request for a new webdriver node but then gecko threw errors
```
Error Message:
 OneTimeSetUp: System.InvalidOperationException : Invalid moz:firefoxOptions field idleTimeout
Build info: version: '3.8.1', revision: '6e95a6684b', time: '2017-12-01T19:05:32.194Z'
System info: host: '3e2bb9be38e9', ip: '172.17.0.4', os.name: 'Linux', os.arch: 'amd64', os.version: '4.9.49-moby', java.version: '1.8.0_151'
Driver info: driver.version: unknown
remote stacktrace: stack backtrace:
   0:           0x4edb3c - backtrace::backtrace::trace::hc4bd56a2f176de7e
   1:           0x4edb72 - backtrace::capture::Backtrace::new::he3b2a15d39027c46
   2:           0x440ac8 - webdriver::error::WebDriverError::new::ha0fbd6d1a1131b43
   3:           0x437513 - <&'a mut I as core::iter::iterator::Iterator>::next::hbb01b33ace84bf9d
   4:           0x4414c5 - geckodriver::marionette::MarionetteHandler::create_connection::hf0532ddb9e159684
   5:           0x428570 - <webdriver::server::Dispatcher<T, U>>::run::h2119c674d7b88193
   6:           0x4029b9 - std::sys_common::backtrace::__rust_begin_short_backtrace::h21d98a9ff86d4c25
   7:           0x40be65 - std::panicking::try::do_call::h5cff0c9b18cfdbba
   8:           0x5e6a6c - panic_unwind::__rust_maybe_catch_panic
                        at /checkout/src/libpanic_unwind/lib.rs:99
   9:           0x41eb22 - <F as alloc::boxed::FnBox<A>>::call_box::h413eb1d9d9f1c473
  10:           0x5df13b - alloc::boxed::{{impl}}::call_once<(),()>
                        at /checkout/src/liballoc/boxed.rs:692
                         - std::sys_common::thread::start_thread
                        at /checkout/src/libstd/sys_common/thread.rs:21
                         - std::sys::imp::thread::{{impl}}::new::thread_start
                        at /checkout/src/libstd/sys/unix/thread.rs:84 (61)
```

**Comment by diemol** [comment] 2017-12-11 08:21
OK, I'll check the Selenium source code to see what could be happening.

**Comment by diemol** [comment] 2017-12-21 19:08
I installed Visual Studio Community and coded in C# again after several years :)

I can reproduce it now, and it happens when this is done:
```
DesiredCapabilities desiredCapabilities = (DesiredCapabilities) firefoxHeadlessOptions.ToCapabilities();
```
Because this basically makes all capabilities as if they were Firefox capabilities, and of course `idleTimeout`, `tz`, and `recordVideo` are not Firefox W3C capabilities, so they get rejected and it fails.

I am not sure if this only happens in C# (.NET bindings), but we need to fix this in Zalenium anyway because the idea is that every 3rd party with special capabilities uses a prefix. For example, in Zalenium we could add `zal:recordVideo` and then it would not make part of the Firefox capabilities and it will work. But we need to make the change. 

Thanks for reporting this, and I'm sorry it has taken so long. We will implement this soon so you can use Zalenium with C#.

**Comment by diemol** [comment] 2017-12-21 19:22
So in Java it does not happen because I cannot cast `FirefoxOptions` to `DesiredCapabilities`. But there is a workaround by doing `desiredCapabilities.setCapability(FirefoxOptions.FIREFOX_OPTIONS, firefoxOptions)`.
I tried the same thing in C# and it didn't work. 
So sadly there seems to be no workaround in C# right now.

**Comment by jimevans** [comment] 2017-12-21 19:57
@diemol There is a C# workaround that should get the job done correctly (assuming the remote end can understand it properly). The code should look like this:

    FirefoxProfile firefoxHeadlessProfile = new FirefoxProfile
    {
        DeleteAfterUse = true
    };
    firefoxHeadlessProfile.SetPreference("browser.cache.disk.enable", false);
    firefoxHeadlessProfile.SetPreference("browser.cache.memory.enable", false);
    firefoxHeadlessProfile.SetPreference("browser.cache.offline.enable", false);
    firefoxHeadlessProfile.SetPreference("network.http.use-cache", false);
    FirefoxOptions firefoxHeadlessOptions = new FirefoxOptions
    {
        Profile = firefoxHeadlessProfile
    };
    firefoxHeadlessOptions.AddArgument("--headless");

    // N.B. Using true for the isGlobalCapability argument in the overload.
    // This tells the options class to add to the top-level dictionary instead
    // of adding the additional capability to the browser-specific moz:firefoxOptions
    // capability.
    firefoxHeadlessOptions.AddAdditionalCapability("idleTimeout", 300, true);
    firefoxHeadlessOptions.AddAdditionalCapability("tz", "America/Chicago", true);
    firefoxHeadlessOptions.AddAdditionalCapability("recordVideo", EnableZaleniumVideoRecording, true);

    IWebDriver WebDriver = new RemoteWebDriver(GridHubUri, firefoxHeadlessOptions.ToCapabilities(), GridCommandTimeout);

This feature has been in the .NET bindings for years, so it's nothing new. Most people just haven't had a use for the overload in most cases (which is why the default adds additional capabilities to the browser-specific dictionary).

**Comment by diemol** [comment] 2017-12-21 20:20
Thanks @jimevans, I tried and it did not work.  

When setting `isGlobalCapability` to false, the `desiredCapabilities` object looks like this: (which is the known issue)
```
{browserName: firefox, moz:firefoxOptions: {args: [--headless], idleTimeout: 180, recordVideo: false, tz: America/Chicago}}
```

When setting `isGlobalCapability` to true, looks like this:
```
{"desiredCapabilities":{"browserName":"firefox","moz:firefoxOptions":{"args":["--headless"]},"idleTimeout":180,"tz":"America/Chicago","recordVideo":"false"},"capabilities":{"firstMatch":[{"browserName":"firefox","moz:firefoxOptions":{"args":["--headless"]},"idleTimeout":180,"tz":"America/Chicago","recordVideo":"false"}]}}
```

But then the Grid throws an Exception: (happens both in Zalenium and a vanilla Grid).
```
2017-12-21 20:14:25.903:WARN:osjs.HttpChannel:qtp1412925683-13: /wd/hub/session
java.io.IOException: org.openqa.grid.common.exception.GridException: Cannot extract a capabilities from the request: {"desiredCapabilities":{"browserName":"firefox","moz:firefoxOptions":{"args":["--headless"]},"idleTimeout":180,"tz":"America/Chicago","recordVideo":"false"},"capabilities":{"firstMatch":[{"browserName":"firefox","moz:firefoxOptions":{"args":["--headless"]},"idleTimeout":180,"tz":"America/Chicago","recordVideo":"false"}]}}
	at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:135)
	at org.openqa.grid.web.servlet.DriverServlet.doPost(DriverServlet.java:68)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:841)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.seleniumhq.jetty9.server.Server.handle(Server.java:561)
	at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:334)
	at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:104)
	at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.seleniumhq.jetty9.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:243)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:679)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:597)
	at java.lang.Thread.run(Thread.java:748)
Caused by:
org.openqa.grid.common.exception.GridException: Cannot extract a capabilities from the request: {"desiredCapabilities":{"browserName":"firefox","moz:firefoxOptions":{"args":["--headless"]},"idleTimeout":180,"tz":"America/Chicago","recordVideo":"false"},"capabilities":{"firstMatch":[{"browserName":"firefox","moz:firefoxOptions":{"args":["--headless"]},"idleTimeout":180,"tz":"America/Chicago","recordVideo":"false"}]}}
	at org.openqa.grid.web.servlet.handler.WebDriverRequest.extractDesiredCapability(WebDriverRequest.java:76)
	at org.openqa.grid.web.servlet.handler.SeleniumBasedRequest.<init>(SeleniumBasedRequest.java:102)
	at org.openqa.grid.web.servlet.handler.WebDriverRequest.<init>(WebDriverRequest.java:36)
	at org.openqa.grid.web.servlet.handler.WebDriverRequestFactory.createFromRequest(WebDriverRequestFactory.java:30)
	at org.openqa.grid.web.servlet.handler.SeleniumBasedRequest.createFromRequest(SeleniumBasedRequest.java:73)
	at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:82)
	at org.openqa.grid.web.servlet.DriverServlet.doPost(DriverServlet.java:68)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:841)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.seleniumhq.jetty9.server.Server.handle(Server.java:561)
	at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:334)
	at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:104)
	at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.seleniumhq.jetty9.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:243)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:679)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:597)
	at java.lang.Thread.run(Thread.java:748)
Caused by:
java.lang.IllegalArgumentException: Illegal key values seen in w3c capabilities: [idleTimeout, recordVideo, tz]
	at org.openqa.selenium.remote.NewSessionPayload.lambda$validate$6(NewSessionPayload.java:211)
	at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:372)
	at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:373)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.stream.ReferencePipeline$11$1.accept(ReferencePipeline.java:373)
	at java.util.LinkedList$LLSpliterator.forEachRemaining(LinkedList.java:1235)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at org.openqa.selenium.remote.NewSessionPayload.validate(NewSessionPayload.java:215)
	at org.openqa.selenium.remote.NewSessionPayload.<init>(NewSessionPayload.java:163)
	at org.openqa.selenium.remote.NewSessionPayload.create(NewSessionPayload.java:118)
	at org.openqa.grid.web.servlet.handler.WebDriverRequest.extractDesiredCapability(WebDriverRequest.java:66)
	at org.openqa.grid.web.servlet.handler.SeleniumBasedRequest.<init>(SeleniumBasedRequest.java:102)
	at org.openqa.grid.web.servlet.handler.WebDriverRequest.<init>(WebDriverRequest.java:36)
	at org.openqa.grid.web.servlet.handler.WebDriverRequestFactory.createFromRequest(WebDriverRequestFactory.java:30)
	at org.openqa.grid.web.servlet.handler.SeleniumBasedRequest.createFromRequest(SeleniumBasedRequest.java:73)
	at org.openqa.grid.web.servlet.DriverServlet.process(DriverServlet.java:82)
	at org.openqa.grid.web.servlet.DriverServlet.doPost(DriverServlet.java:68)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:707)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at org.seleniumhq.jetty9.servlet.ServletHolder.handle(ServletHolder.java:841)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doHandle(ServletHandler.java:535)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doHandle(SessionHandler.java:1595)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextHandle(ScopedHandler.java:188)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doHandle(ContextHandler.java:1253)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:168)
	at org.seleniumhq.jetty9.servlet.ServletHandler.doScope(ServletHandler.java:473)
	at org.seleniumhq.jetty9.server.session.SessionHandler.doScope(SessionHandler.java:1564)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.nextScope(ScopedHandler.java:166)
	at org.seleniumhq.jetty9.server.handler.ContextHandler.doScope(ContextHandler.java:1155)
	at org.seleniumhq.jetty9.server.handler.ScopedHandler.handle(ScopedHandler.java:141)
	at org.seleniumhq.jetty9.server.handler.HandlerWrapper.handle(HandlerWrapper.java:132)
	at org.seleniumhq.jetty9.server.Server.handle(Server.java:561)
	at org.seleniumhq.jetty9.server.HttpChannel.handle(HttpChannel.java:334)
	at org.seleniumhq.jetty9.server.HttpConnection.onFillable(HttpConnection.java:251)
	at org.seleniumhq.jetty9.io.AbstractConnection$ReadCallback.succeeded(AbstractConnection.java:279)
	at org.seleniumhq.jetty9.io.FillInterest.fillable(FillInterest.java:104)
	at org.seleniumhq.jetty9.io.ChannelEndPoint$2.run(ChannelEndPoint.java:124)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.doProduce(EatWhatYouKill.java:247)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.produce(EatWhatYouKill.java:140)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:131)
	at org.seleniumhq.jetty9.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:243)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:679)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:597)
	at java.lang.Thread.run(Thread.java:748)
```

I'll look more into it. I think prefixing custom capabilities is the way to go.

**Comment by diemol** [comment] 2017-12-21 20:21
Here is the code I tried, for future reference:

```C#
    public class FirefoxTest
    {
        static void Main(string[] args)
        {

            FirefoxProfile firefoxHeadlessProfile = new FirefoxProfile
            {
                DeleteAfterUse = true
            };
            firefoxHeadlessProfile.SetPreference("browser.cache.disk.enable", false);
            firefoxHeadlessProfile.SetPreference("browser.cache.memory.enable", false);
            firefoxHeadlessProfile.SetPreference("browser.cache.offline.enable", false);
            firefoxHeadlessProfile.SetPreference("network.http.use-cache", false);

            FirefoxOptions firefoxHeadlessOptions = new FirefoxOptions();
            firefoxHeadlessOptions.AddArgument("--headless");
            firefoxHeadlessOptions.AddAdditionalCapability("zal:idleTimeout", 180, true);
            firefoxHeadlessOptions.AddAdditionalCapability("zal:tz", "America/Chicago", true);
            firefoxHeadlessOptions.AddAdditionalCapability("zal:recordVideo", "false", true);

            Uri gridUrl = new Uri("http://localhost:4444/wd/hub");

            IWebDriver driver = new RemoteWebDriver(gridUrl, firefoxHeadlessOptions)
            {
                Url = "http://www.google.com"
            };
            driver.Quit();
        }
    }
```

**Comment by diemol** [comment] 2017-12-22 20:08
Hi @mitchellmaler 

We just released https://github.com/zalando/zalenium/releases/tag/3.8.1e, and this version is able to match prefixed capabilities. This means that you'd need to prefix them when you set them so Zalenium can parse them properly and create a node with those characteristics.

In short, please pull the new version, and prefix any Zalenium related capability with `zal:`, e.g:

```C#
desiredCapabilities.SetCapability("zal:idleTimeout", 180);
desiredCapabilities.SetCapability("zal:tz", "America/Chicago");
```

Let us know how it went, thanks.

PS: This version also contains the fix for the live preview in Firefox.

**Comment by mitchellmaler** [comment] 2017-12-22 20:16
Awesome, thanks! I'll let you know how it works out once I have time to test it.

**Comment by mitchellmaler** [comment] 2017-12-23 05:05
Everything looks to be working now! I was able to prefix the capabilities and it didn't throw the error and set the configuration. I also checked the live preview and that is now not refreshing every second and I was able to specify an interval.

**Comment by diemol** [comment] 2017-12-23 12:10
Awesome! So if it is ok with you, I'll close this issue and then try to check later the other one you created. Thanks for the quick feedback.

**Closed by diemol** 2017-12-23 12:10 UTC
Labels: investigating
