### ISSUE TITLE
Kubernetes GKE support

### ISSUE THREAD

**Issue by christopherL91** [zalando/zalenium#184] opened 2017-07-13 18:03 UTC
Running kubernetes version 1.6.6 on GKE and I'm having trouble getting started with zalenium.

Manifest:

```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zalenium
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: zalenium
subjects:
- kind: ServiceAccount
  name: zalenium
roleRef:
  kind: ClusterRole
  name: admin
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: zalenium-grid
spec:
  selector:
    app: zalenium
    role: grid
  ports:
  - name: zalenium-grid
    protocol: TCP
    port: 4444
    targetPort: 4444
  type: NodePort
---
apiVersion: v1
kind: Service
metadata:
  name: zalenium-videos
spec:
  selector:
    app: zalenium
    role: grid
  ports:
  - name: zalenium-videos
    protocol: TCP
    port: 5555
    targetPort: 5555
  type: NodePort
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zalenium-shared
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  gcePersistentDisk:
    pdName: "zalenium-shared"
    fsType: "ext4"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zalenium-shared
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zalenium-videos
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteMany
  gcePersistentDisk:
    pdName: "zalenium-videos"
    fsType: "ext4"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zalenium-videos
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zalenium
  labels:
    app: zalenium
    role: grid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zalenium
      role: grid
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: zalenium
        role: grid
    spec:
      serviceAccountName: zalenium
      serviceAccount: zalenium
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: gcr-json-key
      volumes:
      - name: zalenium-videos
        persistentVolumeClaim:
          claimName: zalenium-videos
      - name: zalenium-shared
        persistentVolumeClaim:
          claimName: zalenium-shared
      - name: dshm
        emptyDir:
          medium: Memory
      - name: dockersocket
        hostPath:
          path: /var/run/docker.sock
      restartPolicy: Always
      terminationGracePeriodSeconds: 120
      containers:
      - name: zalenium
        image: dosel/zalenium
        imagePullPolicy: Always
        terminationMessagePath: /dev/termination-log
        args:
        - start
        - --chromeContainers
        - '2'
        - --firefoxContainers
        - '2'
        - --screenWidth
        - '1440'
        - --screenHeight
        - '810'
        - --timeZone
        - Sweden/Stockholm
        ports:
        - name: zalenium-grid
          containerPort: 4444
        - name: zalenium-videos
          containerPort: 5555
        volumeMounts:
        - name: zalenium-videos
          mountPath: /home/seluser/videos
        - name: zalenium-shared
          mountPath: /tmp/mounted
        - name: dshm
          mountPath: /dev/shm
        - name: dockersocket
          mountPath: /var/run/docker.sock
```

Gives:

```
Kubernetes service account found.
-- LOG 17:29:09:606904905 Running additional checks...
Copying files for Dashboard...
Starting Nginx reverse proxy...
Starting Selenium Hub...
17:29:09.906 INFO - Selenium build info: version: '3.3.1', revision: '5234b32'
17:29:09.907 INFO - Launching Selenium Grid hub
17:29:10.474 INFO - binding de.zalando.ep.zalenium.servlet.LivePreviewServlet to /grid/admin/LivePreviewServlet/*
17:29:10.475 INFO - binding de.zalando.ep.zalenium.servlet.ZaleniumConsoleServlet to /grid/admin/ZaleniumConsoleServlet/*
17:29:10.476 INFO - binding de.zalando.ep.zalenium.servlet.ZaleniumResourceServlet to /grid/admin/ZaleniumResourceServlet/*
17:29:10.476 INFO - binding de.zalando.ep.zalenium.dashboard.DashboardCleanupServlet to /grid/admin/DashboardCleanupServlet/*
17:29:10.546 INFO - Will listen on 4445
17:29:10.710 INFO - Nodes should register to http://10.0.17.54:4445/grid/register/
17:29:10.710 INFO - Selenium Grid hub is up and running
.....Selenium Hub started!
Starting DockerSeleniumStarter node...
17:29:11.136 INFO - Selenium build info: version: '3.3.1', revision: '5234b32'
17:29:11.137 INFO - Launching a Selenium Grid node
2017-07-13 17:29:11.544:INFO::main: Logging initialized @676ms to org.seleniumhq.jetty9.util.log.StdErrLog
17:29:11.581 INFO - Driver provider org.openqa.selenium.ie.InternetExplorerDriver registration is skipped:
 registration capabilities Capabilities [{ensureCleanSession=true, browserName=internet explorer, version=, platform=WINDOWS}] does not match the current platform LINUX
17:29:11.581 INFO - Driver provider org.openqa.selenium.edge.EdgeDriver registration is skipped:
 registration capabilities Capabilities [{browserName=MicrosoftEdge, version=, platform=WINDOWS}] does not match the current platform LINUX
17:29:11.582 INFO - Driver class not found: com.opera.core.systems.OperaDriver
17:29:11.582 INFO - Driver provider com.opera.core.systems.OperaDriver registration is skipped:
Unable to create new instances on this machine.
17:29:11.582 INFO - Driver class not found: com.opera.core.systems.OperaDriver
17:29:11.582 INFO - Driver provider com.opera.core.systems.OperaDriver is not registered
17:29:11.583 INFO - Driver provider org.openqa.selenium.safari.SafariDriver registration is skipped:
 registration capabilities Capabilities [{browserName=safari, version=, platform=MAC}] does not match the current platform LINUX
2017-07-13 17:29:11.627:INFO:osjs.Server:main: jetty-9.2.20.v20161216
2017-07-13 17:29:11.668:INFO:osjsh.ContextHandler:main: Started o.s.j.s.ServletContextHandler@cd3fee8{/,null,AVAILABLE}
2017-07-13 17:29:11.683:INFO:osjs.AbstractConnector:main: Started ServerConnector@25306456{HTTP/1.1,[http/1.1]}{0.0.0.0:30000}
2017-07-13 17:29:11.684:INFO:osjs.Server:main: Started @816ms
17:29:11.684 INFO - Selenium Grid node is up and ready to register to the hub
17:29:11.699 INFO - Registering the node to the hub: http://localhost:4444/grid/register
17:29:11.942 INFO - Initialising Kubernetes support
17:29:11.975 INFO - SessionCleaner initialized with insideBrowserTimeout 0 and clientGoneTimeout 1800000 polling every 180000
org.openqa.grid.common.exception.GridException: Error sending the registration request: The hub responded with 500:Server Error
	at org.openqa.grid.internal.utils.SelfRegisteringRemote.registerToHub(SelfRegisteringRemote.java:277)
	at org.openqa.grid.internal.utils.SelfRegisteringRemote.startRegistrationProcess(SelfRegisteringRemote.java:218)
	at org.openqa.grid.selenium.GridLauncherV3$3.launch(GridLauncherV3.java:290)
	at org.openqa.grid.selenium.GridLauncherV3.main(GridLauncherV3.java:99)
..............................................................................................................................................StarterRemoteProxy failed to register to the hub after 30 seconds, failing...
```

**Comment by diemol** [comment] 2017-07-14 14:28
Hi @christopherL91,

From the error in the log, it seems that the main Selenium node is not able to register itself. It should be related to the start parameters.

Can you please try to add a single quote to the other parameters, like this:

```
        - start
        - '--chromeContainers'
        - '2'
        - '--firefoxContainers'
        - '2'
        - '--screenWidth'
        - '1440'
        - '--screenHeight'
        - '810'
        - '--timeZone'
        - Sweden/Stockholm
``` 

If it does not work, try removing the parameters for a moment to see if it starts.

And if it does work, please don't close the issue. Even if the parameters are not well formatted, we should print a warning and fallback to defaults, so I want to leave it open to remind us to check that.

**Comment by christopherL91** [comment] 2017-07-16 14:45
It doesn't work even if I remove all other flags except for start. I get exactly the same error message as stated above.

**Comment by diemol** [comment] 2017-07-27 12:50
Sorry for the late reply, we'll check that soon since we will start using Zalenium in k8s internally more intensively soon.

**Comment by diemol** [comment] 2017-08-01 15:03
Short update here, I was able to reproduce the issue, will debug to see what's happening.

**Comment by dequin-cl** [comment] 2017-08-01 19:09
gcePersistentDisk does not support ReadWriteMany. See https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes

**Comment by rstuven** [comment] 2017-08-01 19:11
gcePersistentDisk does not support ReadWriteMany. See https://kubernetes.io/docs/concepts/storage/persistent-volumes/#access-modes

**Comment by diemol** [comment] 2017-08-03 13:50
Hi @christopherL91,

My problems went away after I created the service account properly, it was lacking the permissions to create the pods on demand, therefore the node registration failed at startup which causes the stack trace you got.

Try to follow the suggestion we have in the documentation, it should help your case. https://github.com/zalando/zalenium/blob/master/docs/k8s/zalenium-role.json
https://github.com/zalando/zalenium/blob/master/docs/k8s/kubernetes.md#kubernetes-service-account

**Comment by christopherL91** [comment] 2017-08-03 14:27
I have fixed those two problems but I'm still having issues.
The manifest file now looks like this:

```
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: zalenium
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: ClusterRole
metadata:
  name: zalenium-role
rules:
- verbs:
  - create
  - list
  - get
  - delete
  - exec
  apiGroups:
  - ''
  resources:
  - pods
- verbs:
  - list
  - create
  - delete
  - get
  apiGroups:
  - ''
  resources:
  - services
- verbs:
  - create
  - get
  apiGroups:
  - ''
  resources:
  - pods/exec
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: zalenium-role-binding
subjects:
- kind: ServiceAccount
  name: zalenium
roleRef:
  kind: ClusterRole
  name: zalenium-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: Service
metadata:
  name: zalenium
spec:
  selector:
    app: zalenium
    role: grid
  ports:
  - name: zalenium-videos
    protocol: TCP
    port: 5555
    targetPort: 5555
  - name: zalenium-shared
    protocol: TCP
    port: 4444
    targetPort: 4444
  type: NodePort
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zalenium-shared
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  gcePersistentDisk:
    pdName: "zalenium-shared"
    fsType: "ext4"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zalenium-shared
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: zalenium-videos
spec:
  capacity:
    storage: 10Gi
  accessModes:
  - ReadWriteOnce
  gcePersistentDisk:
    pdName: "zalenium-videos"
    fsType: "ext4"
---
kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: zalenium-videos
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: zalenium
  labels:
    app: zalenium
    role: grid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: zalenium
      role: grid
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  minReadySeconds: 5
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: zalenium
        role: grid
    spec:
      serviceAccountName: zalenium
      serviceAccount: zalenium
      dnsPolicy: ClusterFirst
      imagePullSecrets:
      - name: gcr-json-key
      volumes:
      - name: zalenium-videos
        persistentVolumeClaim:
          claimName: zalenium-videos
      - name: zalenium-shared
        persistentVolumeClaim:
          claimName: zalenium-shared
      - name: dshm
        emptyDir:
          medium: Memory
      - name: dockersocket
        hostPath:
          path: /var/run/docker.sock
      restartPolicy: Always
      terminationGracePeriodSeconds: 120
      containers:
      - name: zalenium
        image: dosel/zalenium
        imagePullPolicy: Always
        terminationMessagePath: /dev/termination-log
        args:
        - start
        - '--chromeContainers'
        - '2'
        - '--firefoxContainers'
        - '2'
        - '--screenWidth'
        - '1440'
        - '--screenHeight'
        - '810'
        - '--timeZone'
        - Sweden/Stockholm
        ports:
        - name: zalenium-grid
          containerPort: 4444
        - name: zalenium-videos
          containerPort: 5555
        volumeMounts:
        - name: zalenium-videos
          mountPath: /home/seluser/videos
        - name: zalenium-shared
          mountPath: /tmp/mounted
        - name: dshm
          mountPath: /dev/shm
        - name: dockersocket
          mountPath: /var/run/docker.sock
```

Which I think is what it should look like

**Comment by diemol** [comment] 2017-08-03 14:37
What issues are you having? Can you briefly describe them please?

**Comment by christopherL91** [comment] 2017-08-04 07:13
@diemol It won't start. See the error log in my last comment. It's the same error message I saw before.

**Comment by diemol** [comment] 2017-09-21 13:39
Hi @christopherL91, we got this [contribution](https://github.com/zalando/zalenium/blob/master/docs/k8s/gke/gke.md) from @laszlocph.

Can you please check and see if it helps you to have Zalenium working in GKE?

**Comment by diemol** [comment] 2017-10-16 07:21
I'll close this issue due to inactivity, please feel free to reopen in case some support is needed.

**Closed by diemol** 2017-10-16 07:21 UTC
Labels: waiting-retest
