### ISSUE TITLE
Attached videos to dashboard failed

### ISSUE THREAD

**Issue by ansonliao** [zalando/zalenium#1039] opened 2019-08-24 20:16 UTC
## 🐛 Bug Report

During run selenium testing in docker against Zalenium of docker in docker-compose, the docker-compose console throws some errors as below, looks like some errors met when attached videos to the dashboard, please advise how to solve the problem, thanks.

```bash
zalenium           | 04:02:51.075 [http://172.30.0.5:40000] WARN  d.z.e.z.p.DockerSeleniumRemoteProxy - Error while copying the video
zalenium           | java.nio.file.FileAlreadyExistsException: /home/seluser/videos
zalenium           | 	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:88)
zalenium           | 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
zalenium           | 	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
zalenium           | 	at sun.nio.fs.UnixFileSystemProvider.createDirectory(UnixFileSystemProvider.java:384)
zalenium           | 	at java.nio.file.Files.createDirectory(Files.java:674)
zalenium           | 	at java.nio.file.Files.createAndCheckIsDirectory(Files.java:781)
zalenium           | 	at java.nio.file.Files.createDirectories(Files.java:727)
zalenium           | 	at de.zalando.ep.zalenium.proxy.DockerSeleniumRemoteProxy.copyVideos(DockerSeleniumRemoteProxy.java:640)
zalenium           | 	at de.zalando.ep.zalenium.proxy.DockerSeleniumRemoteProxy.processContainerAction(DockerSeleniumRemoteProxy.java:612)
zalenium           | 	at de.zalando.ep.zalenium.proxy.DockerSeleniumRemoteProxy.processContainerAction(DockerSeleniumRemoteProxy.java:601)
zalenium           | 	at de.zalando.ep.zalenium.proxy.DockerSeleniumRemoteProxy.videoRecording(DockerSeleniumRemoteProxy.java:565)
zalenium           | 	at de.zalando.ep.zalenium.proxy.DockerSeleniumRemoteProxy.cleanupNode(DockerSeleniumRemoteProxy.java:757)
zalenium           | 	at de.zalando.ep.zalenium.proxy.DockerSeleniumRemoteProxy.afterSession(DockerSeleniumRemoteProxy.java:405)
zalenium           | 	at org.openqa.grid.internal.TestSlot.performAfterSessionEvent(TestSlot.java:253)
zalenium           | 	at de.zalando.ep.zalenium.registry.ZaleniumRegistry._release(ZaleniumRegistry.java:193)
zalenium           | 	at de.zalando.ep.zalenium.registry.ZaleniumRegistry.lambda$0(ZaleniumRegistry.java:177)
zalenium           | 	at java.lang.Thread.run(Thread.java:748)
```

## Environment

OS: OSX
Zalenium Image Version(s): 3.141.59t
Docker version: 19.03.1
Docker-Compose version (if applicable): 2.2
docker-compose file:

```yaml
version: '2.2'

services:
  elgalu-selenium:
    image: "elgalu/selenium:latest"
    container_name: "elgalu-selenium"

  zalenium:
    image: "dosel/zalenium:latest"
    container_name: zalenium
    hostname: zalenium
    tty: true
    dns:
      - '8.8.8.8'
      - '8.8.4.4'
    volumes:
      - ./videos:/home/seluser/videos
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - '4444:4444'
    command: >
      start --desiredContainers 1
            --maxDockerSeleniumContainers 2
            --screenWidth 1920 --screenHeight 1080
            --timeZone "Asia/Hong_Kong"
            --startTunnel false
            --maxTestSessions 50

  gradle:
    image: gradle:5.6-jdk8
    dns:
      - '8.8.8.8'
      - '8.8.4.4'
    volumes:
      - .:/home/gradle/project
    working_dir: /home/gradle/project
    depends_on:
      - zalenium
    links:
      - zalenium
    command: ./gradlew clean runAgainstZelenium
```

**Comment by antlong** [comment] 2019-09-10 19:54
Does "- ./videos:/home/seluser/videos" exist?

**Comment by nucknorris** [comment] 2019-10-16 14:01
I have the same issue. It only occurs if I mount `/home/seluser/videos`. If I remove the mount, my test suite runs without problems. 

With the mount the zalenium container reports the mentioned `FileAlreadyExistsException`. Here you can see the permissions output from the running container: 

```
drwxrwxr-x 1 seluser seluser     4096 Oct 16 15:41 .
drwxr-xr-x 1 root    root        4096 Sep 20 04:18 ..
-rwxrw-r-- 1 seluser seluser     4529 Sep 20 04:15 Analytics.md
-rwxrw-r-- 1 seluser seluser      220 Sep  1  2015 .bash_logout
-rwxrw-r-- 1 seluser seluser     3771 Sep  1  2015 .bashrc
drwxrwxr-x 1 seluser seluser     4096 Sep 20 04:19 css
-rwxrw-r-- 1 seluser seluser    10996 Sep 20 04:15 dashboard_template.html
-rw-r--r-- 1 root    root        1311 Oct 16 15:41 docker_info.txt
drwxrwxr-x 1 seluser seluser     4096 Sep 20 04:19 img
drwxrwxr-x 1 seluser seluser     4096 Sep 20 04:19 js
-rwxrw-r-- 1 seluser seluser     2128 Sep 20 04:15 LICENSE.md
-rwxrw-r-- 1 seluser seluser     1082 Sep 20 04:15 logback.xml
-rwxrw-r-- 1 seluser seluser     2738 Sep 20 04:15 logging_debug.properties
-rwxrw-r-- 1 seluser seluser     2699 Sep 20 04:15 logging_info.properties
drwxr-xr-x 2 root    root        4096 Oct 16 15:41 logs
-rwxrw-r-- 1 seluser seluser     2593 Oct 16 15:41 nginx.conf
-rwxrw-r-- 1 seluser seluser     2609 Oct 16 15:41 nginx.conf.bak
-rwxrw-r-- 1 seluser seluser      655 May 16  2017 .profile
-rwxrwxr-x 1 seluser seluser     1287 Sep 20 04:15 start-browserstack.sh
-rwxrwxr-x 1 seluser seluser     1078 Sep 20 04:15 start-cbt.sh
-rwxrwxr-x 1 seluser seluser     1061 Sep 20 04:15 start-lambdatest.sh
-rwxrwxr-x 1 seluser seluser     2679 Sep 20 04:15 start-saucelabs.sh
-rwxrwxr-x 1 seluser seluser     1268 Sep 20 04:15 start-testingbot.sh
-rwxrw-r-- 1 seluser seluser        0 Sep 20 04:19 .sudo_as_admin_successful
d????????? ? ?       ?              ?            ? videos
-rwxrwxr-x 1 seluser seluser      831 Sep 20 04:15 wait-browserstack.sh
-rwxrwxr-x 1 seluser seluser      746 Sep 20 04:15 wait-cbt.sh
-rwxrwxr-x 1 seluser seluser      933 Sep 20 04:15 wait-lambdatest.sh
-rwxrwxr-x 1 seluser seluser      983 Sep 20 04:15 wait-saucelabs.sh
-rwxrwxr-x 1 seluser seluser      770 Sep 20 04:15 wait-testingbot.sh
-rwxrw-r-- 1 seluser seluser    15086 Sep 20 04:15 zalando.ico
-rw-rw-r-- 1 seluser seluser 41183898 Sep 20 04:16 zalenium-3.141.59u.jar
-rwxrwxr-x 1 seluser seluser    41195 Sep 20 04:15 zalenium.sh
```

- If the `videos` directory doesn't exist on my local machine, I get this error
- If I create the `videos` directory beforehand, I  can `exec` into the container and there I can find the `videos` directory with the correct permissions. However, if I start the test suite Zalenium deletes the directory and then fails with the same issue as if it wasn't there in the first place

**Comment by kumar1210** [comment] 2019-11-12 18:20
I am also getting the same exception 
19:12:52.636 [http://172.17.0.8:40005] WARN  d.z.e.z.p.DockerSeleniumRemoteProxy - Error while copying the video
java.nio.file.FileAlreadyExistsException: /home/seluser/videos/zalenium_testclasspath_firefox_LINUX_20191112190852182_COMPLETED.mp4
	at sun.nio.fs.UnixException.translateToIOException(UnixException.java:88)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:102)
	at sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:107)
	at sun.nio.fs.UnixFileSystemProvider.newByteChannel(UnixFileSystemProvider.java:214)
	at java.nio.file.spi.FileSystemProvider.newOutputStream(FileSystemProvider.java:434)
	at java.nio.file.Files.newOutputStream(Files.java:216)
	at java.nio.file.Files.copy(Files.java:3016)
	at de.zalando.ep.zalenium.proxy.DockerSeleniumRemoteProxy.copyVideos(DockerSeleniumRemoteProxy.java:642)
	at de.zalando.ep.zalenium.proxy.DockerSeleniumRemoteProxy.processContainerAction(DockerSeleniumRemoteProxy.java:612)
	at de.zalando.ep.zalenium.proxy.DockerSeleniumRemoteProxy.processContainerAction(DockerSeleniumRemoteProxy.java:601)
	at de.zalando.ep.zalenium.proxy.DockerSeleniumRemoteProxy.videoRecording(DockerSeleniumRemoteProxy.java:565)
	at de.zalando.ep.zalenium.proxy.DockerSeleniumRemoteProxy.cleanupNode(DockerSeleniumRemoteProxy.java:757)
	at de.zalando.ep.zalenium.proxy.DockerSeleniumRemoteProxy.afterSession(DockerSeleniumRemoteProxy.java:400)
	at org.openqa.grid.internal.TestSlot.performAfterSessionEvent(TestSlot.java:253)
	at de.zalando.ep.zalenium.registry.ZaleniumRegistry._release(ZaleniumRegistry.java:193)
	at de.zalando.ep.zalenium.registry.ZaleniumRegistry.lambda$0(ZaleniumRegistry.java:177)
	at java.lang.Thread.run(Thread.java:748)


Any solution or workaround ?

**Comment by nucknorris** [comment] 2019-11-27 10:43
Not from our side, sorry. We stopped using zalenium due to multiple issues, this one being one of them.

**Comment by ansonliao** [comment] 2019-11-27 13:57
@kumar1210 
Don't delete the `videos` directory

**Comment by ansonliao** [comment] 2019-11-27 13:59
Hi @nucknorris , I solved the problem by your comment `It only occurs if I mount /home/seluser/videos. If I remove the mount, my test suite runs without problems.`, now I don't delete the `videos` from my test run, it works fine to me

**Comment by diemol** [comment] 2019-12-09 17:00
The information used to create the file names is based on the test capabilities sent, we appreciate having this issue reported, but we cannot reproduce it since we don't have a sample of the tests used to bump into it.

For example, the provided docker-compose file has:
```
  gradle:
    image: gradle:5.6-jdk8
    dns:
      - '8.8.8.8'
      - '8.8.4.4'
    volumes:
      - .:/home/gradle/project
    working_dir: /home/gradle/project
    depends_on:
      - zalenium
    links:
      - zalenium
    command: ./gradlew clean runAgainstZelenium
```
But where are those files?

Could you please provide something we can use to reproduce the issue?

**Comment by ansonliao** [comment] 2019-12-20 17:46
@diemol 

Thanks for your reply and apology for the late reply.

Initialize the WebDriver instance is simple, similar as below:

```java
ChromeOptions chromeOptions = new ChromeOptions();
chromeOptions.setCapability(CapabilityType.BROWSER_NAME, "chrome");
WebDriver driver = new new RemoteWebDriver(new URL("http://zalenium:4444/wd/hub"), chromeOptions);
```

But I think the problem is when the `zalenium` docker container is running, and then deleted the `videos` directory forced, and then re-run the test against to the running `zalenium` docker service, maybe can cause this problem.

Why I said `maybe`, because we are stopping using `zalenium` as our selenium grid as we meet other problems such as the selenium webdriver's docker containers (for example chromedriver docker container) created by zalenium that keep killed by zalenium and then creating the new container of webdriver around 2 minutes, and this problem cause our selenium testing script initialize the remove webdriver many failures, and we can't to solve the problem by ourself, we can't set `zalenium` as persistent grid in testing server for our selenium testing.

Thanks.

**Comment by ansonliao** [comment] 2019-12-20 17:52
@nikhil-lambda 
We are stopping using zalenium as our selenium grid also, and seeking other solution for it, we are meet this problem: #594 , and we tried many solutions include the discussed this the issue #594, also similar to :
https://stackoverflow.com/questions/54468143/zalenium-node-container-terminate-and-restart-continuously-on-using-proxy

but no luck to us.

**Comment by diemol** [comment] 2019-12-22 03:51
OK, so we never really got a clear description on how to reproduce this to figure out if it is a bug or not. Since the OP has no way to provide this, I'll close the issue.

**Closed by diemol** 2019-12-22 03:51 UTC
Labels: waiting-answer
