### ISSUE TITLE
Clearer way to setup node configuration

### ISSUE THREAD

**Issue by Comette** [zalando/zalenium#735] opened 2018-10-03 19:45 UTC
First I would like to congrats the team for this awesome tool for parallel acceptance test execution. Even though, I had some troubles configuring it. I would like a more frendly documentaion about how to setup the nodes configuration. Actualy, I didn't see much option about de node configuration, such as defining what browser is needed on container. Right now, it's setup to both chrome and firefox, but we only need chrome. Also I wold love to see a better session about node and sever configurations on the docs.

Zalenium Image Version(s):  
Latest (3.14.0d)

Docker Version:  
18.06.1-ce

OS: 
Windows 10

Docker Command to start Zalenium:  
docker run --rm -d -ti --name zalenium -p 4444:4444 -v //var/run/docker.sock:/var/run/docker.sock --net="host" --privileged dosel/zalenium start --chromeContainers 1 --maxDockerSeleniumContainers 14 --timeZone "America/Sao_Paulo"

## Expected Behavior -
I was waiting for the hub to star with just one node container running only chrome browser.

## Actual Behavior -
Since the "--chromeContainers" command was deprecated in 3.7.1d release, the actual behavior is that the hub starts up 2 containers with both firefox and chrome (as it does by default).

**Comment by Comette** [comment] 2018-10-08 13:02
Is anything wrong with my question? I saw newer questions that has been answered but not even a comment on my. Sorry if it's something too simple or stupid, but I'll really appreciate some help... @diemol @elgalu

**Comment by elgalu** [comment] 2018-10-08 13:11
Hi @Comette , there is nothing wrong with your question, I'm really sorry we didn't get back to you

At the moment we have too much in our plate so responsiveness is going down.

We would like also Zalenium to be more community driven, specially regarding questions, so the project creators are not a bottle-neck.

Just give it a few days to see if someone jumps in.

> I would like to congrats the team for this awesome tool for parallel acceptance test execution
Thanks, we appreciate it:)

**Comment by diemol** [comment] 2018-10-08 13:20
Complementing @elgalu's comment, there is a #zalenium channel in the Selenium slack where questions can be asked and many other users are helping each other.

About configuring the nodes, there is not so much room for it if you use Zalenium directly. As you can see, Zalenium uses @elgalu's docker-selenium which offers tons of configuration parameters. So a way to configure the nodes is to create your own image based on docker-selenium and customize it according to your needs.

Right now, when a node starts, it has the capabilities for Chrome and Firefox, which makes all the code more simple in Zalenium, and this lead to a more simple maintainability. In the end, the image has already Chrome and Firefox installed, so even if you show only Chrome, Firefox is also installed in the image as well. 

If you have more questions related to this item, I invite you to join https://seleniumhq.herokuapp.com, go to the #zalenium channel and post them there.

I'll close this issue since it is not a bug and neither has an action item for the project.

**Closed by diemol** 2018-10-08 13:20 UTC
Labels: help wanted, question
