### ISSUE TITLE
Cannot extract a capabilities from the request

### ISSUE THREAD

**Issue by jpswade** [zalando/zalenium#543] opened 2018-04-26 14:12 UTC
**Please make sure that you provide enough information for us to help you with this issue. Thank you!**

Zalenium Image Version(s):  
latest
Docker Version:  
Docker version 18.04.0-ce, build 3d479c0
OS: 
Mac OS X
Docker Command to start Zalenium:  
```
docker run --rm --name ${INTEGRATION_WEB_DRIVER_HOST} \
    -p ${INTEGRATION_WEB_DRIVER_PORT}:${INTEGRATION_WEB_DRIVER_PORT} \
    -e DOCKER=17.06.2-ce \
    -v /var/run/docker.sock:/var/run/docker.sock \
    -v /tmp/videos:/home/seluser/videos \
    --detach \
    --privileged dosel/zalenium start
```
## Expected Behavior -
Let's take this example from here: https://gist.github.com/prashanthrajagopal/12f53e5c98385fbf50e2

```
curl -X POST http://127.0.0.1:4444/wd/hub/session -d '{"desiredCapabilities":{"browserName":"firefox","platform":"MAC"}}' --fail
...
```

Not a failure...

## Actual Behavior -
```
$ curl -X POST http://127.0.0.1:4444/wd/hub/session -d '{"desiredCapabilities":{"browserName":"firefox","platform":"MAC"}}' --fail
curl: (22) The requested URL returned error: 500 Server Error
```
## Additional notes...

I'm trying to prove that this works.

**Comment by diemol** [comment] 2018-04-26 14:34
Hi @jpswade,

Strange, I tried the same and it worked, here are the commands:

Request:
```
curl --fail http://localhost:4444/wd/hub/session --data '{"desiredCapabilities":{"browserName":"chrome", "platform":"ANY", "acceptSslCerts":true}}'
```

Response: 
```
{"status":0,"sessionId":"826566a0bc6559bc68ac370bffa391a6","value":{"applicationCacheEnabled":false,"rotatable":false,"mobileEmulationEnabled":false,"networkConnectionEnabled":false,"chrome":{"chromedriverVersion":"2.38.551591 (bcc4a2cdef0f6b942b2bb8049068f65340fa2a69)","userDataDir":"/tmp/.org.chromium.Chromium.qlsja6"},"takesHeapSnapshot":true,"pageLoadStrategy":"normal","databaseEnabled":false,"handlesAlerts":true,"hasTouchScreen":false,"version":"66.0.3359.117","platform":"Linux","browserConnectionEnabled":false,"nativeEvents":true,"acceptSslCerts":false,"acceptInsecureCerts":false,"locationContextEnabled":true,"webStorageEnabled":true,"browserName":"chrome","takesScreenshot":true,"javascriptEnabled":true,"cssSelectorsEnabled":true,"setWindowRect":true,"unexpectedAlertBehaviour":"","webdriver.remote.sessionid":"826566a0bc6559bc68ac370bffa391a6"}}% 
```

Could you please double check on your end?

**Comment by diemol** [comment] 2018-05-03 21:11
I'll close this since we were not able to reproduce and no more feedback was provided.

Feel free to reopen in case it still happens.

**Closed by diemol** 2018-05-03 21:11 UTC
Labels: waiting-answer, waiting-retest
