### ISSUE TITLE
Zalenium is not compatible with selenium web driver 3.4.0

### ISSUE THREAD

**Issue by wantorp** [zalando/zalenium#173] opened 2017-06-30 08:54 UTC
Hello,

I'm using Zalenium to run my tests and it works fine until version 3.3.0 of Selenium.

I recently upgraded the Selenium web driver to version 3.4.0 and stopped communicating with the hub.

I always get this error:
   at OpenQA.Selenium.Remote.RemoteWebDriver.UnpackAndThrowOnError(Response errorResponse)
   at OpenQA.Selenium.Remote.RemoteWebDriver.Execute(String driverCommandToExecute, Dictionary`2 parameters)
   at OpenQA.Selenium.Remote.RemoteWebDriver.StartSession(ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(ICommandExecutor commandExecutor, ICapabilities desiredCapabilities)
   at OpenQA.Selenium.Remote.RemoteWebDriver..ctor(Uri remoteAddress, ICapabilities desiredCapabilities)

Is not Zalenium compatible with version 3.4.0 of the web driver ??

Does anyone have this problem? Is there any way to use zalenium with version 3.4.0 of the Selenium web driver.

Thank you.

Good work.

**Comment by iMbaundso** [comment] 2017-06-30 18:49
Hi @wantorp ,

you can wait for an "official" answer but I'm quiet sure zalenium is not ready yet to work with selenium 3.4.0. Might be interesting anyways to hear if there are plans to upgrade to 3.4.0

See also: https://github.com/zalando/zalenium#about-the-project-versioning

**Comment by wantorp** [comment] 2017-07-03 08:46
Hi @iMbaundso ,

Thanks for your feedback.

**Comment by diemol** [comment] 2017-07-03 10:40
Hi @wantorp,

Yeah, we have not upgraded because there are some issues here https://github.com/elgalu/docker-selenium/pull/149

Basically, the python bindings are throwing some errors with 3.4.0
We need to check that in detail but we haven't had the time... 

I'll leave this open and close it when we release with 3.4.0

Thanks for jumping in @iMbaundso!

**Comment by wantorp** [comment] 2017-07-03 11:42
Hi @diemol,

Thanks.

**Comment by elgalu** [comment] 2017-07-03 13:29
@wantorp @iMbaundso if you can fix the python selenium tests to run with 3.4.0 then we will be glad to move FWD. Go to https://github.com/elgalu/docker-selenium/pull/149 and add the changes necessary to have the tests working, should be easy to debug with TravisCI as opening a PR at elgalu/docker-selenium will trigger the build. Is also reproducible locally.

**Closed** 2017-09-17 16:20 UTC
Labels: help wanted
