### ISSUE TITLE
Cannot forward the request Connect to 172.17.0.4:40001 [/172.17.0.4] failed: Connection refused (Connection refused) and Session [...] was terminated due to FORWARDING_TO_NODE_FAILED when using proxy

### ISSUE THREAD

**Issue by tsadoklevi** [zalando/zalenium#679] opened 2018-07-28 07:24 UTC
Hi,

We execute the following code using Jenkins on a Google Cloud Platform compute instance (VM):
```
MY_HTTP_PROXY="http://${MY_HTTP_PROXY}"
MY_HTTPS_PROXY="https://${MY_HTTPS_PROXY}"
MY_NO_PROXY='localhost, 127.0.0.1, 10.80.0.0/16, logic-player, logic-processing, logic-game, logic-admin, logic-admin-ui, ng-server, ng-client, promo-game-server, redis-sentinel, 172.17.0.*, 172.16/12, 172.17.0.*:40000'
IMAGE_NAME=dosel/zalenium

docker run --rm -d --name $DOCKER_NAME \
              -p 4444:4444 \
              -v /var/run/docker.sock:/var/run/docker.sock \
              -v $MY_LOCAL_VIDEO_FOLDER:/home/seluser/videos \
              -e "zalenium_http_proxy=$MY_HTTP_PROXY" \
              -e "zalenium_https_proxy=$MY_HTTPS_PROXY" \
              -e "zalenium_no_proxy=$MY_NO_PROXY" \
              -e ZALENIUM_EXTRA_JVM_PARAMS="-Dwebdriver.http.factory=apache" \
              --privileged $IMAGE_NAME start --screenWidth $MY_SCREEN_WIDTH --screenHeight $MY_SCREEN_HEIGHT
```
and we receive the following exceptions (multiple times during the run):
```
org.openqa.selenium.WebDriverException: cannot forward the request Connect to 172.17.0.4:40001 [/172.17.0.4] failed: Connection refused (Connection refused)
```
and 
```
org.openqa.selenium.WebDriverException: Session [9d809a10a0519c8121e9dee171f3229c] was terminated due to FORWARDING_TO_NODE_FAILED
``` 

### Zalenium Image Version(s):  
Latest
Docker Version:  
```
Client:
 Version:       18.04.0-ce
 API version:   1.37
 Go version:    go1.9.4
 Git commit:    3d479c0
 Built: Tue Apr 10 18:20:32 2018
 OS/Arch:       linux/amd64
 Experimental:  false
 Orchestrator:  swarm
Server:
 Engine:
  Version:      18.04.0-ce
  API version:  1.37 (minimum version 1.12)
  Go version:   go1.9.4
  Git commit:   3d479c0
  Built:        Tue Apr 10 18:18:40 2018
  OS/Arch:      linux/amd64
  Experimental: false
```
### Expected Behavior
When we omit the proxy settings 
```
              -e "zalenium_http_proxy=$MY_HTTP_PROXY" \
              -e "zalenium_https_proxy=$MY_HTTPS_PROXY" \
              -e "zalenium_no_proxy=$MY_NO_PROXY" \
```
the tests execute as expected. 

Any idea? Can it be a firewall issue? Are we doing something wrong or is it a bug?

**Comment by tsadoklevi** [comment] 2018-08-21 06:38
Hi @diemol and @pearj. Thank you very much for your answers. 

Unfortunately, the straight-forward way of specifying the proxy settings, that is 
```
-e "zalenium_http_proxy=$MY_HTTP_PROXY" \
-e "zalenium_https_proxy=$MY_HTTPS_PROXY" \
-e "zalenium_no_proxy=$MY_NO_PROXY" \
```
did not work with any proxy settings. 

Fortunately, the solution to that was as @TomLarrow [suggested](https://github.com/zalando/zalenium/issues/198#issuecomment-324433665)  - to build a Selenium docker image (to be used by Zalenium) with the proxy settings :
```
FROM elgalu/selenium
ENV http_proxy=http://myproxy.example.com:8080 
ENV https_proxy=http://myproxy.example.com:8080 
ENV no_proxy=localhost, 127.0.0.1, **etc**
```
Perhaps there's a bug in the implementation of the proxy settings in Zalenium?

On the other hand, building a Selenium docker image is a very convenient way to pass proxy settings when using Zalenium in Kubernetes as opposed to the alternative (which hasn't worked for me) of including the proxy settings in the Zalenium Hub configuration file (YAML). 

This leads me to suggest that all of this arguments, such as 
```
- args:
--desiredContainers
--maxDockerSeleniumContainers
--sauceLabsEnabled
--browserStackEnabled
--testingBotEnabled
--videoRecordingEnabled
--screenWidth
--screenHeight
--timeZone
--seleniumImageName
--maxTestSessions
--debugEnabled
--sendAnonymousUsageInfo
--keepOnlyFailedTests
```
would be set in a ConfigMap rather than in the Zalenium yaml file. This way, it would be possible to specify and pass new settings by redeploying a ConfigMap rather than redeploying Zalenium Hub.

**Comment by diemol** [comment] 2018-08-21 19:48
@tsadoklevi thanks for replying. We do not discard that there is a bug when setting the env vars, but what we would need is a way to reproduce it so it can be fixed.

In addition, when you set the env vars, can you see them when you go inside a container?

**Comment by remeltucker** [comment] 2018-08-28 20:44
@diemol 
Am seeing the same error as mentioned in the initial comment in this ticket.
Using elgalu/selenium as of 08/20 and modified to include the proxies.(As mentioned by user)
Using latest Zalenium.

Running docker container the same way as mentioned in this ticket. This started happening after I upgraded elgalu/selenium to Chrome 68. Working fine when I was using a 2 month old image that had Chrome 66.

Error Message as follows 
org.openqa.selenium.WebDriverException: cannot forward the request Connect to 172.17.0.4:40001 [/172.17.0.4] failed: Connection refused (Connection refused)
org.openqa.selenium.WebDriverException: Session [9d809a10a0519c8121e9dee171f3229c] was terminated due to FORWARDING_TO_NODE_FAILED

**Comment by remeltucker** [comment] 2018-08-31 14:39
any thoughts @diemol ?

**Comment by diemol** [comment] 2018-10-25 11:05
Regarding the original issue, I spent a couple of hours trying to figure out if it was a bug in Zalenium, in the end everything looks like an issue of configuring properly the proxy. 

I started locally a Squid proxy using this image: https://github.com/sameersbn/docker-squid
The I added the configuration based on this short tutorial: http://cottagedata.com/security/squid/squid.html, and all origins are accepted.

Started the proxy, and my IP in my network is 192.168.1.8.

```
docker run --rm -ti --name zalenium -p 4444:4444 -v /var/run/docker.sock:/var/run/docker.sock \
  -v /tmp/videos:/home/seluser/videos -e zalenium_http_proxy="http://192.168.1.8:3128" \
  -e zalenium_https_proxy="http://192.168.1.8:3128" \
  -e zalenium_no_proxy="localhost,127.0.0.1,192.168.1.8" --privileged dosel/zalenium start
```

After starting Zalenium like this, I can see that all the test traffic goes through the proxy by just doing:
```
docker exec -it squid tail -f /var/log/squid/access.log
```

Please have a look at your proxy configuration, be sure that all values are passed properly and well configured in the containers. (I also tried the path of creating a custom docker image with the variables for a proxy set, and it also worked).

Moreover, if I misconfigure the proxy by changing a port or the IP, I bump into the error shown at the top of this issue.  

I will close this issue since it is the consequence of an incorrect proxy configuration.

**Closed by diemol** 2018-10-25 11:05 UTC
Labels: waiting-answer

**Comment by meyerbro** [comment] 2018-11-06 12:38
Can you share your squid.conf file please @diemol ?

**Comment by diemol** [comment] 2018-11-06 13:31
Here it is https://github.com/diemol/squid-with-basic-auth

**Comment by diemol** [comment] 2018-11-06 15:14
@meyerbro not really, I don't know a lot about proxies, but it seems that you cannot specify ranges 
https://unix.stackexchange.com/questions/23452/set-a-network-range-in-the-no-proxy-environment-variable

You need to try different combinations and see what works. 
(I will close #761 since it is related to proxy configs)

**Comment by PriyaMuthuvel** [comment] 2020-01-09 06:38
Hi, 

I have tried the below commands but the thing is local host is not connecting.

**Executing the docker zalenium commands**
![image](https://user-images.githubusercontent.com/23624668/72043774-0f586f00-32d8-11ea-9764-605f13b34534.png)

![image](https://user-images.githubusercontent.com/23624668/72043922-7f66f500-32d8-11ea-8f1c-9397c46d4d75.png)


Kindly let me know where am missing
