### ISSUE TITLE
Error when accessing /dasboard in K8s

### ISSUE THREAD

**Issue by cgaulay** [zalando/zalenium#353] opened 2017-12-06 08:55 UTC
**Please make sure that you provide enough information for us to help you with this issue. Thank you!**

Zalenium Image Version(s):  
3.8.1b

## Actual Behavior -
With Zalenium 3.8.1b in Kubernetes environment, when i trying to access on /dashboard, i got an 403 nginx error page with acces denied. In nginx configuration file, dashboard alias seems to be wrong for dashboard location : 
alias   /home/seluser/videos;
i've replace it by :
alias   /home/seluser/;
and now it works !

It is possible to push a correction ?

thanks in advance ! 
Regards.

**Comment by diemol** [comment] 2017-12-06 17:42
Hi @cgaulay,

Yes, this is kind of a little issue in Kubernetes. Without changing anything, can you access the dashboard if you put a slash at the end? E.g. http://host:port/dashboard/

**Comment by diemol** [comment] 2017-12-10 22:40
So after checking this, the real bug is in the nginx configuration. When the mapped port is different from 4444 and the dashboard url does not end with a "/", then a redirection happens to port 4444 and an error is displayed.

Current workaround is to add a "/" at the end of the url. I tried to fix the nginx configuration but I was not successful, any help would be appreciated.

**Comment by doertedev** [comment] 2018-02-15 12:41
Just out of curiosity, can it be that it should point to /home/seluser instead of /home/seluser/videos? Because there are no html files in the videos directory.

**Comment by diemol** [comment] 2018-02-16 08:53
Hi @doertedev,

It should point to the videos folder, the files are creating during execution time. Actually that part is ok, it is just a matter of tuning the nginx configuration.

**Comment by peerster** [comment] 2018-03-07 19:47
One fix could be to add a rewrite that adds a trailing slash, but I'm afraid it might break something else

**Comment by peerster** [comment] 2018-03-08 11:31
Well not even that worked 😠

**Comment by Tim-Schwalbe** [comment] 2018-03-10 09:05
I am still facing this issue, also with trailing slash, I get 403 forbidden. 
using: image: dosel/zalenium:latest

**Comment by peerster** [comment] 2018-03-10 09:08
@Tim-Schwalbe can you try 3.9.1a and see if it works any better?

**Comment by Tim-Schwalbe** [comment] 2018-03-10 09:35
I only changed the image tag to image: dosel/zalenium:3.9.1a 
Now there is an issue with the docker container --> CrashLoopBackOff
The hubs seems to come up shortly and crashes after a while.
The 403 is still there.

**Comment by peerster** [comment] 2018-03-10 09:38
I think your problem is unrelated to this issue to be honest, and probably caused by your setup and/or config

**Comment by diemol** [comment] 2018-04-27 10:50
Thanks to @pearj, this has been fixed in https://github.com/zalando/zalenium/releases/tag/3.11.0e

**Closed by diemol** 2018-04-27 10:50 UTC
Labels: bug, good-first-contribution, help wanted
