### ISSUE TITLE
SauceLabsRemoteProxy failed to start after 40 seconds, failing

### ISSUE THREAD

**Issue by karl0ss** [zalando/zalenium#1070] opened 2019-10-21 14:24 UTC
## 🐛 Bug Report

Unable to connect to saucelabs with the error "SauceLabsRemoteProxy failed to start after 40 seconds, failing" displayed

## To Reproduce

Running a docker-compose file that contains 

 ```
 zalenium:
    image: "dosel/zalenium"
    container_name: zalenium
    hostname: zalenium
    depends_on:
      - hub
    tty: true
    volumes:
      - /tmp/videos:/home/seluser/videos
      - /var/run/docker.sock:/var/run/docker.sock
    ports:
      - 4444:4444
      - 8000:8000
    command: >
      start --desiredContainers 2
            --maxDockerSeleniumContainers 8
            --screenWidth 800 --screenHeight 600
            --timeZone "Europe/Berlin"
            --videoRecordingEnabled true
            --sauceLabsEnabled true
            --browserStackEnabled false
            --testingBotEnabled false
            --cbtEnabled false
            --lambdaTestEnabled false
            --startTunnel false
    environment:
      - HOST_UID
      - HOST_GID
      - SAUCE_USERNAME=myUserName
      - SAUCE_ACCESS_KEY=XXXXXX-XX-XXXXX-XXXXX-XXXXXX
      - BROWSER_STACK_USER
      - BROWSER_STACK_KEY
      - TESTINGBOT_KEY
      - TESTINGBOT_SECRET
      - CBT_USERNAME
      - CBT_AUTHKEY
      - LT_USERNAME
      - LT_ACCESS_KEY
```

## Expected behavior

I believe this should activate a connection for sauceLabs for devices not supported by zalenium (Mobiles)

## Environment

OS: Ubuntu 18.04 Docker enviroment
Zalenium Image Version(s): Pulling latest image - 3.141.59u
Docker version:  18.06.1-ce
Docker-Compose version (if applicable): 2.1

## Log

```
Docker binary already present, will use that one.

Docker version 18.09.0, build 4d60db4

-- LOG 18:09:20:895618251 Ensuring docker works...

-- LOG 18:09:21:467332441 Ensuring docker-selenium is available...

haveged: haveged starting up


Copying files for Dashboard...

Starting Nginx reverse proxy...

Starting Selenium Hub...

................18:09:27.809 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Selenium server version: 3.141.59, revision: unknown

..18:09:28.387 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Launching Selenium Grid hub on port 4445

.........18:09:30.858 [main] INFO  d.z.e.z.c.DockerContainerClient - About to clean up any left over DockerSelenium containers created by Zalenium

.......................................18:09:44.088 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Starting poller.

.........18:09:47.974 [main] INFO  d.z.ep.zalenium.aspect.HubAspect - Registering custom Zalenium servlets

.....18:09:50.901 [main] INFO  org.openqa.grid.web.Hub - Selenium Grid hub is up and running

18:09:50.904 [main] INFO  org.openqa.grid.web.Hub - Nodes should register to http://172.19.0.3:4445/grid/register/

18:09:50.907 [main] INFO  org.openqa.grid.web.Hub - Clients should connect to http://172.19.0.3:4445/wd/hub

Selenium Hub started!

Starting Sauce Labs node...

......................................18:10:14.485 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Selenium server version: 3.141.59, revision: unknown

.......18:10:19.003 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Launching a Selenium Grid node on port 30001

...................18:10:29.229 [main] INFO  global - Initialising WebDriverServlet

....18:10:31.907 [main] INFO  o.o.s.remote.server.SeleniumServer - Selenium Server is up and running on port 30001

18:10:31.915 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Selenium Grid node is up and ready to register to the hub

SauceLabsRemoteProxy failed to start after 40 seconds, failing...
```

**Comment by diemol** [comment] 2019-12-09 17:27
@karl0ss is this still happening?
This is mostly due to an issue with Sauce Labs when you tried to run that.

**Comment by karl0ss** [comment] 2019-12-12 14:34
I have not tried for a few weeks, I will have a look tomororw and see if this is still happening, thank you for getting back to me.

**Comment by networkandcode** [comment] 2020-03-19 15:46
@diemol I am facing a similar issue with kubernetes(helm chart deployment),  I followed the procedure provided on the zalenium website, but keep getting error in the log that says '.SauceLabsRemoteProxy failed ', I have used the variables SAUCE_USERNAME, SAUCE_KEY, SAUCE_LABS_URL and SAUCE_LABS_API_URL

**Comment by diemol** [comment] 2020-03-21 20:38
I just tried this and it is working with my user and password. How can this be reproduced?

**Comment by networkandcode** [comment] 2020-03-23 08:09
it worked with a trial account but not with an account that had a mobile testing licence... the only difference I saw when I accessed the api link https://eu-central-1.saucelabs.com/rest/v1/users/USERNAME (with password as the access key) is this for the normal account --  "concurrency_limit": {"mac": 0, "scout": 0, "overall": 0, "real_device": 2}, where as the trial account had all 2

**Comment by diemol** [comment] 2020-03-23 18:01
I see, but that is a bug in Sauce Labs, since Zalenium uses the `overall` field to get the concurrency limit. See https://github.com/zalando/zalenium/blob/master/src/main/java/de/zalando/ep/zalenium/proxy/SauceLabsRemoteProxy.java#L49-L50, it should say `"overall": 2` in this case.

I am closing this issue since it is not a Zalenium issue.

**Closed by diemol** 2020-03-23 18:01 UTC
Labels: waiting-answer
