### ISSUE TITLE
zalenium with browserstack in daemon mode dies unexpectedly

### ISSUE THREAD

**Issue by davidemoro** [zalando/zalenium#228] opened 2017-09-07 10:59 UTC
If you run zalenium in daemon mode with browserstack enabled, docker dies unexpectedly:

* https://gist.github.com/davidemoro/d12531e984f0c42c95ac82f1032b3747

Running this command with zalenium in foreground all goes fine:
`tox -epy36 -- --splinter-webdriver=remote --variables=credentials/credentials-ALPHA.yml --splinter-remote-url=http://localhost:4444/wd/hub -m "login" --variables capabilities/browsers/chrome/CHROME.json --variables capabilities/os/WIN10.json --variables capabilities/resolutions/1280x1024.json
`
With zalenium in daemon mode after few seconds we get a "ConnectionRefusedError: [Errno 111] Connection refused".

Tested with:
```
davide@davide-VirtualBox:~/workspaces/pcm2_qa$ docker --version
Docker version 17.05.0-ce, build 89658be
```

Any idea?

Thanks in advance

**Comment by laszlocph** [comment] 2017-09-15 12:30
I was able to reproduce this myself. Runs in the foreground (--rm -it), crashes as daemon (-d). 

As far as I understood what's happening is that the hub starts up, then the BrowserStack proxy and all seems fine. But then the whole process stars over, first the hub comes up, then the proxy.. looping for 40s when https://github.com/zalando/zalenium/blob/master/scripts/zalenium.sh#L465 kills it. I couldn't get closer in the limited time I looked at it. Just wanted to jot this down.

It works though with `docker run -d -t`.

**Comment by laszlocph** [comment] 2017-09-16 14:37
Submitted a PR to fix this: https://github.com/zalando/zalenium/pull/235

**Comment by davidemoro** [comment] 2017-09-18 10:31
Thanks a lot @laszlocph!

**Comment by diemol** [comment] 2017-09-20 21:11
Hi @davidemoro @laszlocph,

Sorry for the late reply, 

Can you show me the command you use to start Zalenium please?

And yes, we are changing the way we validate that BrowserStack is ready because it depends on docker, and this is affecting the Kubernetes version.

**Comment by diemol** [comment] 2017-09-21 13:36
We just released https://github.com/zalando/zalenium/releases/tag/3.5.3c, and now the cloud proxies are validated differently. Can you please check again?

**Comment by davidemoro** [comment] 2017-09-22 08:15
I'm going to retest, thanks. I'll let you know asap

**Comment by elgalu** [comment] 2017-09-22 09:37
> having some trouble trying to install the selenium-3.5.3 tag

What do you mean exactly? there is no python selenium binding version 3.5.3, latest is 3.5.0: https://pypi.python.org/pypi/selenium

**Comment by davidemoro** [comment] 2017-09-22 10:31
@elgalu, I've installed https://github.com/SeleniumHQ/selenium/tree/selenium-3.5.3 from github but I have the same error with 3.5.0 from pypi. Just checking if a not yet released version of selenium fixes the problem.

Anyway the daemonized zalenium no longer dies so I think this issue could be closed as well.

**Comment by diemol** [comment] 2017-09-22 10:36
@davidemoro 
The image that Zalenium uses is this one https://github.com/elgalu/docker-selenium

**Comment by diemol** [comment] 2017-09-29 05:53
OK, I'll close this issue then.

**Closed** 2017-09-29 05:53 UTC
Labels: waiting-retest
