### ISSUE TITLE
Support HTTPS or SSH tunnel

### ISSUE THREAD

**Issue by AndrewBoothman** [zalando/zalenium#1068] opened 2019-10-17 16:01 UTC
## 🚀 Feature Proposal

Support either HTTPS for accessing the Selenium Hub so that the basic authentication credentials which Zalenium supports do not have to be passed over cleartext, or ensure that all part of Zalenium support being passed over an SSH tunnel. Basic HTTP traffic such as clients connecting to the hub do work over an SSH tunnel, but not all parts of the dashboard do such as the VNC connections that seem to rely on being able to access a certain IP address, which is not accessible over the tunnel.

## Motivation

If you deploy zalenium to a public cloud, you don't want to have to pass credentials around in cleartext otherwise they might be snooped on at some point.

## Example

Deploy zalenium to a public cloud and secure all access to it using HTTPS or SSH

**Comment by diemol** [comment] 2019-12-09 17:21
Hey @AndrewBoothman,

Zalenium has internally an nginx running, you can easily leverage that to share your certificate with nginx and deploy it that way.
You could check and adapt this guides to achieve that
https://medium.com/faun/setting-up-ssl-certificates-for-nginx-in-docker-environ-e7eec5ebb418
https://medium.com/@pentacent/nginx-and-lets-encrypt-with-docker-in-less-than-5-minutes-b4b8a60d3a71

I don't think we have enough time to implement that feature natively in Zalenium, unless someone sends us a PR.

Also, this is a duplicate of #401

**Closed by diemol** 2019-12-09 17:21 UTC
