### ISSUE TITLE
Session was terminated due to FORWARDING_TO_NODE_FAILED

### ISSUE THREAD

**Issue by ankit-ojha** [zalando/zalenium#783] opened 2018-11-26 07:51 UTC
Zalenium Image Version(s):  **latest**
Docker Version:  **18.09.0, build 4d60db4**
If using docker-compose, version:  **1.23.1, build b02f1306**

OS: **Windows 10**
Docker Command to start Zalenium:  
Executing through **docker-compose.yml**

Using latest elgalu image

I have already used the comments mentioned under https://github.com/zalando/zalenium/issues/593
but no luck. Tests are started but after sometime the below exception occurs. 

Project setup is mavenized. 

docker-compose.yml

> version: '3'
> 
> services:
>   db:
>      image: ${docker.registry}/docker-xx-db-testdata:${project.version}
>      ports:
>       - "1521:1521"
> 
> 
>   wildfly:
>      image: ${docker.registry}/docker-xx-wildfly:${project.version}
>      command: /opt/xx/wildfly/bin/domain.sh -b=0.0.0.0 -bmanagement=0.0.0.0 -Dcom.xx.jvm.heap-size=${HEAP_SIZE:-1000m} -Dcom.xx.jvm.max-heap-size=${MAX_HEAP_SIZE:-2048m} -Dcom.ec.keycloak.url=http://wildfly:8180/auth
>      links:
>       - "db"
>      ports:
>       - "${WEB_PORT:-8080}:8080"
>       - "${MANAGEMENT_PORT:-9990}:9990"
> 
>   elgalu:
>    image: "elgalu/selenium:${GRIDHUB_TAG:-latest}"
>    links:
>       - "wildfly"
> 
>   zalenium:
>     image: "dosel/zalenium"
>     container_name: zalenium
>     hostname: zalenium
>     links:
>       - "wildfly"
>     tty: true
>     privileged: true
>     volumes:
>       - /var/run/docker.sock:/var/run/docker.sock
>       - /C/Zalenium:/home/seluser/videos
>     ports:
>       - 4445:4444
>     command: >
>       start --desiredContainers 2
>             --maxDockerSeleniumContainers 10
>             --maxTestSessions 150
>             --screenWidth 1920 --screenHeight 1080
>             --timeZone "Asia/Kolkata"
>             --videoRecordingEnabled true
>             --seleniumImageName "elgalu/selenium:${GRIDHUB_TAG:-latest}"
>     environment:
>            - "ZALENIUM_EXTRA_JVM_PARAMS=-Dwebdriver.http.factory=apache"
> 

```
org.openqa.selenium.WebDriverException: Session [6cbb094901e19a60a6bd40bfc120f5fe] was terminated due to FORWARDING_TO_NODE_FAILED
      Command duration or timeout: 0 milliseconds
        at sun.reflect.GeneratedConstructorAccessor242.newInstance(Unknown Source)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
        at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
        at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
        at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
        at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:658)
        at org.openqa.selenium.remote.RemoteWebDriver.getScreenshotAs(RemoteWebDriver.java:343)
        at sun.reflect.GeneratedMethodAccessor95.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.openqa.selenium.remote.Augmenter$CompoundHandler.invoke(Augmenter.java:194)
        at org.jboss.arquillian.drone.webdriver.factory.remote.reusable.ReusableRemoteWebDriver$ByteBuddy$6hgIJapw.getScreenshotAs(Unknown Source)
        at sun.reflect.GeneratedMethodAccessor94.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.arquillian.graphene.proxy.GrapheneProxyHandler.invokeReal(GrapheneProxyHandler.java:129)
        at org.jboss.arquillian.graphene.proxy.GrapheneContextualHandler$1.invoke(GrapheneContextualHandler.java:169)
        at org.jboss.arquillian.graphene.enricher.SearchContextInterceptor.intercept(SearchContextInterceptor.java:50)
        at org.jboss.arquillian.graphene.proxy.InvocationContextImpl.invoke(InvocationContextImpl.java:87)
        at org.jboss.arquillian.graphene.enricher.StaleElementInterceptor$1.apply(StaleElementInterceptor.java:47)
        at org.jboss.arquillian.graphene.enricher.StaleElementInterceptor$1.apply(StaleElementInterceptor.java:43)
        at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:208)
        at org.jboss.arquillian.graphene.wait.WebDriverWaitImpl.until(WebDriverWaitImpl.java:96)
        at org.jboss.arquillian.graphene.enricher.StaleElementInterceptor.intercept(StaleElementInterceptor.java:43)
        at org.jboss.arquillian.graphene.proxy.InvocationContextImpl.invoke(InvocationContextImpl.java:87)
        at org.jboss.arquillian.graphene.proxy.GrapheneContextualHandler$2.call(GrapheneContextualHandler.java:241)
        at org.jboss.arquillian.graphene.context.BrowserActions.performAction(BrowserActions.java:62)
        at org.jboss.arquillian.graphene.proxy.GrapheneContextualHandler.invoke(GrapheneContextualHandler.java:237)
        at org.jboss.arquillian.graphene.proxy.GrapheneContextualHandler.intercept(GrapheneContextualHandler.java:263)
        at org.jboss.arquillian.drone.webdriver.factory.remote.reusable.ReusableRemoteWebDriver$ByteBuddy$6hgIJapw$$EnhancerByGraphene$$a9eb503e.getScreenshotAs(<generated>)
        at com.ec.selenium.core.testbase.Hooks.addScreenCaptureToReports(Hooks.java:102)
        at com.ec.selenium.core.testbase.Hooks.afterScenario(Hooks.java:89)
        at sun.reflect.GeneratedMethodAccessor92.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at cucumber.runtime.Utils$1.call(Utils.java:40)
        at cucumber.runtime.Timeout.timeout(Timeout.java:16)
        at cucumber.runtime.Utils.invoke(Utils.java:34)
        at cucumber.runtime.arquillian.backend.ArquillianHookDefinition.execute(ArquillianHookDefinition.java:55)
        at cucumber.runtime.Runtime.runHookIfTagsMatch(Runtime.java:224)
        at cucumber.runtime.Runtime.runHooks(Runtime.java:212)
        at cucumber.runtime.Runtime.runAfterHooks(Runtime.java:206)
        at cucumber.runtime.arquillian.runner.BaseCukeSpace$CucumberRuntime.runAfterHooks(BaseCukeSpace.java:479)
        at cucumber.runtime.model.CucumberScenario.run(CucumberScenario.java:46)
        at cucumber.runtime.junit.ExecutionUnitRunner.run(ExecutionUnitRunner.java:102)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at cucumber.runtime.junit.ExamplesRunner.run(ExamplesRunner.java:59)
        at org.junit.runners.Suite.runChild(Suite.java:128)
        at org.junit.runners.Suite.runChild(Suite.java:27)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at cucumber.runtime.junit.ScenarioOutlineRunner.run(ScenarioOutlineRunner.java:53)
        at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:63)
        at cucumber.runtime.junit.FeatureRunner.runChild(FeatureRunner.java:18)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at cucumber.runtime.junit.FeatureRunner.run(FeatureRunner.java:70)
        at cucumber.runtime.arquillian.ArquillianCucumber$1.runFeature(ArquillianCucumber.java:40)
        at cucumber.runtime.arquillian.ArquillianCucumber$1.runFeature(ArquillianCucumber.java:26)
        at cucumber.runtime.arquillian.runner.BaseCukeSpace.runFeatures(BaseCukeSpace.java:289)
        at cucumber.runtime.arquillian.runner.BaseCukeSpace.performInternalCucumberOperations(BaseCukeSpace.java:107)
        at cucumber.runtime.arquillian.ArquillianCucumber$InstanceControlledFrameworkMethod.invokeExplosively(ArquillianCucumber.java:111)
        at org.jboss.arquillian.junit.Arquillian$8$1.invoke(Arquillian.java:342)
        at org.jboss.arquillian.container.test.impl.execution.LocalTestExecuter.execute(LocalTestExecuter.java:57)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
        at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
        at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:90)
        at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:133)
        at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:105)
        at org.jboss.arquillian.core.impl.EventImpl.fire(EventImpl.java:62)
        at org.jboss.arquillian.container.test.impl.execution.ClientTestExecuter.execute(ClientTestExecuter.java:50)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
        at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
        at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:90)
        at org.jboss.arquillian.container.test.impl.client.ContainerEventController.createContext(ContainerEventController.java:128)
        at org.jboss.arquillian.container.test.impl.client.ContainerEventController.createTestContext(ContainerEventController.java:118)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
        at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
        at org.jboss.arquillian.test.impl.TestContextHandler.createTestContext(TestContextHandler.java:116)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
        at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
        at org.jboss.arquillian.test.impl.TestContextHandler.createClassContext(TestContextHandler.java:83)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
        at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
        at org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:69)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
        at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
        at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:133)
        at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.test(EventTestRunnerAdaptor.java:122)
        at org.jboss.arquillian.junit.Arquillian$8.evaluate(Arquillian.java:338)
        at org.jboss.arquillian.junit.Arquillian$4.evaluate(Arquillian.java:220)
        at org.jboss.arquillian.junit.Arquillian.multiExecute(Arquillian.java:384)
        at org.jboss.arquillian.junit.Arquillian.access$200(Arquillian.java:54)
        at org.jboss.arquillian.junit.Arquillian$5.evaluate(Arquillian.java:231)
        at org.jboss.arquillian.junit.Arquillian$7$1.invoke(Arquillian.java:295)
        at org.jboss.arquillian.container.test.impl.execution.ClientBeforeAfterLifecycleEventExecuter.execute(ClientBeforeAfterLifecycleEventExecuter.java:88)
        at org.jboss.arquillian.container.test.impl.execution.ClientBeforeAfterLifecycleEventExecuter.on(ClientBeforeAfterLifecycleEventExecuter.java:66)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
        at org.jboss.arquillian.core.impl.EventContextImpl.invokeObservers(EventContextImpl.java:103)
        at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:90)
        at org.jboss.arquillian.container.test.impl.client.ContainerEventController.createContext(ContainerEventController.java:128)
        at org.jboss.arquillian.container.test.impl.client.ContainerEventController.createBeforeContext(ContainerEventController.java:114)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
        at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
        at org.jboss.arquillian.test.impl.TestContextHandler.createTestContext(TestContextHandler.java:116)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
        at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
        at org.jboss.arquillian.test.impl.TestContextHandler.createClassContext(TestContextHandler.java:83)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
        at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
        at org.jboss.arquillian.test.impl.TestContextHandler.createSuiteContext(TestContextHandler.java:69)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.arquillian.core.impl.ObserverImpl.invoke(ObserverImpl.java:86)
        at org.jboss.arquillian.core.impl.EventContextImpl.proceed(EventContextImpl.java:95)
        at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:133)
        at org.jboss.arquillian.core.impl.ManagerImpl.fire(ManagerImpl.java:105)
        at org.jboss.arquillian.test.impl.EventTestRunnerAdaptor.fireCustomLifecycle(EventTestRunnerAdaptor.java:142)
        at org.jboss.arquillian.junit.Arquillian$7.evaluate(Arquillian.java:289)
        at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
        at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
        at cucumber.runtime.arquillian.ArquillianCucumber.runChild(ArquillianCucumber.java:95)
        at cucumber.runtime.arquillian.ArquillianCucumber.runChild(ArquillianCucumber.java:22)
        at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
        at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
        at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
        at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
        at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
        at org.jboss.arquillian.junit.Arquillian$2.evaluate(Arquillian.java:182)
        at org.jboss.arquillian.junit.Arquillian.multiExecute(Arquillian.java:384)
        at org.jboss.arquillian.junit.Arquillian.access$200(Arquillian.java:54)
        at org.jboss.arquillian.junit.Arquillian$3.evaluate(Arquillian.java:193)
        at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
        at org.jboss.arquillian.junit.Arquillian.run(Arquillian.java:148)
        at org.apache.maven.surefire.junit4.JUnit4Provider.execute(JUnit4Provider.java:367)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeWithRerun(JUnit4Provider.java:274)
        at org.apache.maven.surefire.junit4.JUnit4Provider.executeTestSet(JUnit4Provider.java:238)
        at org.apache.maven.surefire.junit4.JUnit4Provider.invoke(JUnit4Provider.java:161)
        at org.apache.maven.surefire.booter.ForkedBooter.invokeProviderInSameClassLoader(ForkedBooter.java:290)
        at org.apache.maven.surefire.booter.ForkedBooter.runSuitesInProcess(ForkedBooter.java:242)
        at org.apache.maven.surefire.booter.ForkedBooter.main(ForkedBooter.java:121)
```

**Comment by ankit-ojha** [comment] 2018-11-26 07:54
Tried passing the parameter but this didn't help. 
environment:
           - "ZALENIUM_EXTRA_JVM_PARAMS=-Dwebdriver.http.factory=apache"

**Comment by ankit-ojha** [comment] 2018-11-26 09:05
Below exception was also observed

> `org.openqa.selenium.WebDriverException: cannot forward the request unexpected end of stream on Connection{172.25.0.6:40000, proxy=DIRECT hostAddress=/172.25.0.6:40000 cipherSuite=none protocol=http/1.1}
Command duration or timeout: 0 milliseconds
        at sun.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at sun.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at sun.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:423)
        at org.openqa.selenium.remote.ErrorHandler.createThrowable(ErrorHandler.java:214)
        at org.openqa.selenium.remote.ErrorHandler.throwIfResponseFailed(ErrorHandler.java:166)
        at org.openqa.selenium.remote.http.JsonHttpResponseCodec.reconstructValue(JsonHttpResponseCodec.java:40)
        at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:80)
        at org.openqa.selenium.remote.http.AbstractHttpResponseCodec.decode(AbstractHttpResponseCodec.java:44)
        at org.openqa.selenium.remote.HttpCommandExecutor.execute(HttpCommandExecutor.java:164)
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:601)
        at org.openqa.selenium.remote.RemoteWebElement.execute(RemoteWebElement.java:279)
        at org.openqa.selenium.remote.RemoteWebElement.findElements(RemoteWebElement.java:195)
        at org.openqa.selenium.remote.RemoteWebElement.findElementsByClassName(RemoteWebElement.java:243)
        at org.openqa.selenium.By$ByClassName.findElements(By.java:383)
        at org.openqa.selenium.remote.RemoteWebElement.findElements(RemoteWebElement.java:171)
        at org.jboss.arquillian.graphene.GrapheneElementImpl.findElements(GrapheneElementImpl.java:184)
        at org.jboss.arquillian.graphene.enricher.WebElementUtils.dropProxyAndFindElements(WebElementUtils.java:181)
        at org.jboss.arquillian.graphene.enricher.WebElementUtils$2.getTarget(WebElementUtils.java:84)
        at org.jboss.arquillian.graphene.proxy.GrapheneProxyHandler.getTarget(GrapheneProxyHandler.java:147)
        at org.jboss.arquillian.graphene.proxy.GrapheneContextualHandler$1.getTarget(GrapheneContextualHandler.java:218)
        at org.jboss.arquillian.graphene.proxy.GrapheneContextualHandler$1.invoke(GrapheneContextualHandler.java:169)
        at org.jboss.arquillian.graphene.enricher.StaleElementInterceptor$1.apply(StaleElementInterceptor.java:47)
        at org.jboss.arquillian.graphene.enricher.StaleElementInterceptor$1.apply(StaleElementInterceptor.java:43)
        at org.openqa.selenium.support.ui.FluentWait.until(FluentWait.java:208)
        at org.jboss.arquillian.graphene.wait.WebDriverWaitImpl.until(WebDriverWaitImpl.java:96)
        at org.jboss.arquillian.graphene.enricher.StaleElementInterceptor.intercept(StaleElementInterceptor.java:43)
        at org.jboss.arquillian.graphene.proxy.InvocationContextImpl.invoke(InvocationContextImpl.java:87)
        at org.jboss.arquillian.graphene.proxy.GrapheneContextualHandler$2.call(GrapheneContextualHandler.java:241)
        at org.jboss.arquillian.graphene.context.BrowserActions.performAction(BrowserActions.java:62)
        at org.jboss.arquillian.graphene.proxy.GrapheneContextualHandler.invoke(GrapheneContextualHandler.java:237)
        at com.sun.proxy.$Proxy48.size(Unknown Source)
        at com.ec.selenium.core.cell.ECCellFactory.getECCell(ECCellFactory.java:75)
        at com.ec.selenium.core.screenlet.FormScreenlet.fillValues(FormScreenlet.java:29)
        at com.ec.transport.CargoPlanning.Forecast.teststeps.CargoPlanningForecast.navigateToScreenAndCopyForecastTest(CargoPlanningForecast.java:82)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at org.jboss.arquillian.graphene.proxy.GrapheneProxyHandler.invokeReal(GrapheneProxyHandler.java:129)
        at org.jboss.arquillian.graphene.proxy.GrapheneContextualHandler$1.invoke(GrapheneContextualHandler.java:169)
        at org.jboss.arquillian.graphene.proxy.GrapheneContextualHandler$2.call(GrapheneContextualHandler.java:241)
        at org.jboss.arquillian.graphene.context.BrowserActions.performAction(BrowserActions.java:62)`

**Comment by pearj** [comment] 2018-11-26 09:14
> - "ZALENIUM_EXTRA_JVM_PARAMS=-Dwebdriver.http.factory=apache

FYI, the Apache http client has now been removed from the selenium grid, so that flag does nothing now.

**Comment by diemol** [comment] 2018-11-27 13:03
@ankit-ojha yes, the Apache Http Client was removed in the Selenium upstream project.

If you are running into this issue, can you please provide the necessary elements to reproduce it? Then we can give it a try and fix it.

**Comment by ankit-ojha** [comment] 2018-11-28 19:53
I am using the latest and greatest versions of the images mentioned in the description. Using multi-module maven project using arquillian

BTW when selenium was 3.8.1 I explored this plugin and it worked beautifully. I tweaked and tried many settings. Read all the issues and comments in order to resolve my problem. 

This is a great plugin. I am clueless now why hub and node have this issue. Either if it didn't work I would be at peace. I am yet to derive a pattern on this. Somewhere I read 7-8 minutes into the execution there was this issues. I once ran the suite for 1 hour with no issues and for sometimes it breaks during the initial minutes of execution.

**Comment by ankit-ojha** [comment] 2018-11-28 19:55
Maybe proxy? 

How to setup under docker-compose? I tried it by the way. Not sure if I did as expected.

**Comment by ankit-ojha** [comment] 2018-11-28 19:59
Additionally, 5 CPU cores 8 GB Memory 
6 containers

I did observe CPU spiking to 200% for zalenium node container when the tests were executed. If that's the case, how can I allow more CPUs to zalenium? Or maybe I am overthinking :|

**Comment by diemol** [comment] 2018-11-28 20:11
Thanks for the info. Nevertheless, I don't know yet how to reproduce the issue. The docker compose file has a lot of place holders that I don't know what value to put in there. Additionally, what test script can I use to reproduce the issue?

**Comment by ankit-ojha** [comment] 2018-11-29 10:08
It is a complex setup using arquillian where we are injecting webdriver instance using Drone. I can understand the steps or scripts that are needed to reproduce the issue. Give me couple of days to get back to you. I thought the logs would help you guys out to understand the issue
________________________________

**Comment by arndttigges** [comment] 2018-11-30 08:54
I am using the current zalenium images and facing this issue too. unfortunately i am unable to reproduce this. it just happens once. I could not discover the "caused by" in the provided stacktrace from the zalenium log:

`...	
at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.tryProduce(EatWhatYouKill.java:168)
	at org.seleniumhq.jetty9.util.thread.strategy.EatWhatYouKill.run(EatWhatYouKill.java:126)
	at 
 org.seleniumhq.jetty9.util.thread.ReservedThreadExecutor$ReservedThread.run(ReservedThreadExecutor.java:366)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:765)
	at org.seleniumhq.jetty9.util.thread.QueuedThreadPool$2.run(QueuedThreadPool.java:683)
	at java.lang.Thread.run(Thread.java:748)

Caused by: java.io.EOFException: \n not found: limit=0 content=…
	at okio.RealBufferedSource.readUtf8LineStrict(RealBufferedSource.java:237)
	at okhttp3.internal.http1.Http1Codec.readHeaderLine(Http1Codec.java:215)
	at okhttp3.internal.http1.Http1Codec.readResponseHeaders(Http1Codec.java:189)
	... 61 common frames omitted`

I hope, it helps.

**Comment by espekkaya** [comment] 2018-12-14 15:14
Hello,
I have had same issue couple of days. I have use latest version 

docker-compose file below ;
`services:
  #--------------#
  zalenium:
    image: "dosel/zalenium:latest"
    container_name: zalenium
    hostname: zalenium
    privileged: true
    tty: true
    environment:
      - "ZALENIUM_EXTRA_JVM_PARAMS=-Dwebdriver.http.factory=apache"
    volumes:
      - /tmp/videos:/home/seluser/videos
      - /var/run/docker.sock:/var/run/docker.sock
      - /usr/bin/docker:/usr/bin/docker
      - /home/sysadmin/zalenium:/tmp/node/home/seluser/folder
      - /home/sysadmin/Downloads:/tmp/node/home/seluser/Downloads
    ports:
      - 4444:4444
    command: >
      start --desiredContainers 1
            --maxDockerSeleniumContainers 3
            --screenWidth 1920 --screenHeight 1080
            --timeZone "Europe/Istanbul"
            --videoRecordingEnabled true
            --maxTestSessions 1
            --sauceLabsEnabled false
            --browserStackEnabled false
            --testingBotEnabled false
            --startTunnel false
            --debugEnabled false`

Here I'm getting liek error message;

`    [31m✖ failed[39m
      [31mWebDriverError: cannot forward the request unexpected end of stream on Connection{172.22.0.4:40001, proxy=DIRECT hostAddress=/172.22.0.4:40001 cipherSuite=none protocol=http/1.1}[39m[90m
          at Object.checkLegacyResponse (/var/lib/jenkins/workspace/E2E/Docker-Zalenium/Suites/e2e/node_modules/selenium-webdriver/lib/error.js:546:15)
          at parseHttpResponse (/var/lib/jenkins/workspace/E2E/Docker-Zalenium/Suites/e2e/node_modules/selenium-webdriver/lib/http.js:509:13)
          at doSend.then.response (/var/lib/jenkins/workspace/E2E/Docker-Zalenium/Suites/e2e/node_modules/selenium-webdriver/lib/http.js:441:30)
          at process.internalTickCallback (internal/process/next_tick.js:77:7)[39m`

**Comment by diemol** [comment] 2018-12-19 13:47
This issue is a duplicate of #742, let's continue the conversation there.

**Closed by diemol** 2018-12-19 13:47 UTC
Labels: waiting-answer
