### ISSUE TITLE
Zalenium Chrome Only

### ISSUE THREAD

**Issue by byip-ujet** [zalando/zalenium#741] opened 2018-10-11 01:31 UTC
Zalenium Image Version(s):  
Docker Version:  18.06.1-ce
If using docker-compose, version:  1.22.0

OS: OSX High Sierra
Docker Command to start Zalenium:  
- docker-compose -f local_run/zalenium-compose.yml up -d
 
We are attempting to start zalenium without firefox (chrome only).  However we are unable to find a compatible chrome-only image to use.  Is this feature supported? And if so how do we implement it?

**Comment by diemol** [comment] 2018-10-11 08:46
Hi @byip-ujet,

This is a duplicate of #735. Basically you can create your own image based on the docker-selenium one. 

If you have more questions related to this item, I invite you to join https://seleniumhq.herokuapp.com, go to the #zalenium channel and post them there.

**Closed by diemol** 2018-10-11 08:46 UTC
