### ISSUE TITLE
why test status was TIMEOUT

### ISSUE THREAD

**Issue by koala2012** [zalando/zalenium#466] opened 2018-03-07 16:00 UTC
I just run test by selenium, I have 2 tests both were very short only had 6 seconds, why the the recording video had 90 seconds? and why the test status was TIMEOUT? the backend log as following

```
09:45:53.406 INFO [RequestHandler.process] - Got a request to create a new session: Capabilities {browserName: firefox, javascriptEnable: true, version: }
09:45:53.411 INFO [DockerSeleniumStarterRemoteProxy.getNewSession] - [DS] Starting new node for {browserName=firefox, version=, javascriptEnable=true}.
2018-03-06 09:45:54 INFO  DefaultDockerClient:678 - Starting container with Id: 057523e23037b60c69901012a6ba7a42fe9569a9534df16cf2b9f35d52877b08
09:46:01.798 INFO [DockerSeleniumStarterRemoteProxy.checkContainerStatus] - [DS] Container zalenium_40004 is up after ~7 seconds...
09:46:02.417 INFO [ZaleniumRegistry.add] - Registered a node http://172.17.0.3:40004
09:46:02.428 INFO [TestSlot.getNewSession] - Trying to create a new session on test slot {server:CONFIG_UUID=e37fd6c8-164c-41a9-b3d1-5fbf7ea788f0, seleniumProtocol=WebDriver, zal:tz=Europe/Berlin, version=58.0.2, platform=LINUX, acceptSslCerts=true, zal:screenResolution=1920x1080, zal:screen-resolution=1920x1080, browserName=firefox, zal:resolution=1920x1080, maxInstances=1, platformName=LINUX}
09:46:06.497 INFO [DockerContainerClient.executeCommand] - http://172.17.0.3:40004 [bash, -c, start-video]
09:46:24.335 INFO [RequestHandler.process] - Got a request to create a new session: Capabilities {browserName: firefox, javascriptEnable: true, version: }
09:46:24.337 INFO [DockerSeleniumStarterRemoteProxy.getNewSession] - [DS] Starting new node for {browserName=firefox, version=, javascriptEnable=true}.
2018-03-06 09:46:24 INFO  DefaultDockerClient:678 - Starting container with Id: 400f20b4dea8655a49ba6464b5fff0661e245262ca638c3274e016d2e6f90d66
09:46:33.116 INFO [DockerSeleniumStarterRemoteProxy.checkContainerStatus] - [DS] Container zalenium_40005 is up after ~8 seconds...
09:46:33.436 INFO [ZaleniumRegistry.add] - Registered a node http://172.17.0.4:40005
09:46:33.475 INFO [TestSlot.getNewSession] - Trying to create a new session on test slot {server:CONFIG_UUID=20e225ff-638f-4da1-bbc5-af529cb17e04, seleniumProtocol=WebDriver, zal:tz=Europe/Berlin, version=58.0.2, platform=LINUX, acceptSslCerts=true, zal:screenResolution=1920x1080, zal:screen-resolution=1920x1080, browserName=firefox, zal:resolution=1920x1080, maxInstances=1, platformName=LINUX}
09:46:38.046 INFO [DockerContainerClient.executeCommand] - http://172.17.0.4:40005 [bash, -c, start-video]
09:47:54.455 INFO [DockerSeleniumRemoteProxy$DockerSeleniumNodePoller.run] - http://172.17.0.3:40004 Shutting down node due to test inactivity
09:47:54.660 INFO [DockerContainerClient.executeCommand] - http://172.17.0.3:40004 [bash, -c, notify 'Zalenium', '**TEST TIMED OUT**', --icon=/home/seluser/images/timeout.png]
09:47:55.871 INFO [DockerContainerClient.executeCommand] - http://172.17.0.3:40004 [bash, -c, stop-video]
09:48:18.639 INFO [DockerSeleniumRemoteProxy$DockerSeleniumNodePoller.run] - http://172.17.0.4:40005 Shutting down node due to test inactivity
09:48:18.717 INFO [DockerContainerClient.executeCommand] - http://172.17.0.4:40005 [bash, -c, notify 'Zalenium', 'TEST TIMED OUT', --icon=/home/seluser/images/timeout.png]
09:48:19.103 INFO [DockerContainerClient.executeCommand] - http://172.17.0.4:40005 [bash, -c, stop-video]
09:48:28.648 INFO [DockerSeleniumRemoteProxy.copyVideos] - http://172.17.0.3:40004 Video file copied to: /home/seluser/videos/zalenium_772f12e2-8676-4736-8c99-b547874fc99a_firefox_LINUX_20180306094828536.mp4
09:48:28.835 INFO [DockerContainerClient.executeCommand] - http://172.17.0.3:40004 [bash, -c, transfer-logs.sh]
09:48:29.106 INFO [DockerSeleniumRemoteProxy.copyLogs] - http://172.17.0.3:40004 Logs copied to: /home/seluser/videos/logs/zalenium_772f12e2-8676-4736-8c99-b547874fc99a_firefox_LINUX_20180306094828536
09:48:29.128 INFO [DockerContainerClient.executeCommand] - http://172.17.0.3:40004 [bash, -c, cleanup-container.sh]
09:48:35.503 INFO [DefaultRemoteProxy.onEvent] - http://172.17.0.3:40004 Marking the node as down because the test has been idle for more than 90 seconds.
09:48:35.504 WARN [ZaleniumRegistry.removeIfPresent] - Cleaning up stale test sessions on the unregistered node http://172.17.0.3:40004
09:48:50.216 INFO [DockerSeleniumRemoteProxy.copyVideos] - http://172.17.0.4:40005 Video file copied to: /home/seluser/videos/zalenium_00b7e4c1-99eb-401c-8dd3-e653d3a6c78d_firefox_LINUX_20180306094850032.mp4
09:48:50.238 INFO [DockerContainerClient.executeCommand] - http://172.17.0.4:40005 [bash, -c, transfer-logs.sh]
09:48:50.506 INFO [DockerSeleniumRemoteProxy.copyLogs] - http://172.17.0.4:40005 Logs copied to: /home/seluser/videos/logs/zalenium_00b7e4c1-99eb-401c-8dd3-e653d3a6c78d_firefox_LINUX_20180306094850032
09:48:50.524 INFO [DockerContainerClient.executeCommand] - http://172.17.0.4:40005 [bash, -c, cleanup-container.sh]
09:48:56.178 INFO [DefaultRemoteProxy.onEvent] - http://172.17.0.4:40005 Marking the node as down because the test has been idle for more than 90 seconds.
09:48:56.179 WARN [ZaleniumRegistry.removeIfPresent] - Cleaning up stale test sessions on the unregistered node http://172.17.0.4:40005
```

**Comment by diemol** [comment] 2018-03-08 08:17
Hi @koala2012,

Selenium will perceive that a session has been terminated when you do `driver.quit()`, and then Zalenium relies to that to mark the test as completed. If the test does not do `driver.quit()` then the session stays alive for 90 seconds (default value), and then it is marked as time out.

Please ensure that you are doing `driver.quit()` to close the session properly.

I'll close this issue, but if you find that the root cause was not really the `driver.quit()` part, feel free to reopen it.

**Closed by diemol** 2018-03-08 08:17 UTC
