### ISSUE TITLE
Facing session id issue in latest Zalenium 

### ISSUE THREAD

**Issue by Rameshbabub** [zalando/zalenium#1150] opened 2020-02-03 08:12 UTC
Summary:

We have our own framework where we are sending the desire cap of "Browser as chrome and platform as windows". When we used the old version of "3.141.59n" for zalenium it is working fine and some times we will get node forwarding issue. 

Now we have updated to latest version and seems none of the execution is happened and getting "session_id in the exception", i have traceback the issue also. but it is pointing to webdriver.py under the selenium/webdriver/remote library.

It is for chrome browser and version as 79

**Comment by diemol** [comment] 2020-03-21 21:02
Zalenium does not support Windows in the capabilities, a cloud provider extension would be needed for that.
I am closing this since the issue is more a description than an actual issue with a way to reproduce it.

**Closed by diemol** 2020-03-21 21:02 UTC
