### ISSUE TITLE
Spinning up "Zombie" pods in OpenShift

### ISSUE THREAD

**Issue by TomLarrow** [zalando/zalenium#275] opened 2017-10-13 15:58 UTC
Lately, we've been seeing a number of Selenium pods being started that just aren't doing anything.  They don't connect to the hub, don't register, never see traffic, but count against the number of pods that Zalenium will open with the --maxDockerSeleniumContainers parameter.

Currently we have this set to 30 in our grid, and at the moment I have 11 pods behaving this way, as there are 30 pods running in the OpenShift project, but the hub is reporting only having 19 nodes connected an running tests.  These dead pods seem to come in bunches, I have:

4 that the OpenShift console lists as a day old
2 that are 21 hours old
3 that are 14 hours old
2 that are 1 hour old

Generally when tests hit the grid they come in in parallel sets of 10 and I'm wondering if there is something involved in starting up a number of pods at the same time which may be causing them to start incorrectly.

All of these zombie pods so far have been attempting to run Chrome, but as 95% of our current testing is in Chrome I can't rule out that it would happen with Firefox, I'll run some more tests with it.

In each instance the pod consumes virtually no cpu, and less than 300mb of memory. Taking a look at the process list, Chromedriver is running, but nothing has been written to /var/log/cont/chrome_driver.log (the file does not exist)

Everything cleans up correctly if I restart the Zalenium pod.  Let me know if there is anything else I can do to help debug this issue.

**Comment by TomLarrow** [comment] 2017-10-16 18:18
Confirming this happens with Firefox as well.  Threw a job containing 50 parallel tests at a completely empty hub.  It spun up 30 containers, yet only 23 nodes registered with the hub and executed tests.

The remaining started up in this zombie state

ps aux|grep geckodriver                                                                                                                                                                         
seluser     202  0.0  0.2 30215844 91992 ?      Sl   13:05   0:03 java -Dwebdriver.firefox.logfile=/var/log/cont/firefox_driver.log -Xmx26142512k -Dwebdriver.gecko.driver=/usr/bin/geckodriver -j
ar /home/seluser/selenium-server-standalone-3.jar -port 40004 -host 10.1.5.106 -role node -hub http://10.1.6.194:4445/grid/register -browser browserName=firefox,maxInstances=1,platform=LINUX,acc
eptSslCerts=true,screenResolution=1200x930,resolution=1200x930,screen-resolution=1200x930,tz=America/New_York,version=56.0 -maxSession 1 -timeout 19000 -browserTimeout 16000 -cleanUpCycle 5000 -
nodePolling 101000 -unregisterIfStillDownAfter 2500 -proxy de.zalando.ep.zalenium.proxy.DockerSeleniumRemoteProxy -registerCycle 0       

$ cat /var/log/cont/firefox_driver.log                                                                                                                              
cat: /var/log/cont/firefox_driver.log: No such file or directory

**Comment by TomLarrow** [comment] 2017-10-20 19:23
A further piece of information.  These zombie pods always seem to be on the same host as the Zalenium hub.  Not all pods that get assigned to that host end up in this state, but it seems that only nodes on the same host end up in this state.  When the Zalenium hub spun up on a new host, we saw only pods on that host experience this behavior

**Comment by diemol** [comment] 2017-10-29 17:44
Hi @TomLarrow, sorry for the late reply. 

It seems like a lot of pods are being created and the hub cannot handle all of them, therefore some are left unattended and unregistered. 

This is happening because we were assuming that the nodes were always going to be registered, and of course we assumed that less threads were present. Therefore we set the config value in Selenium to [zero](https://github.com/zalando/zalenium/blob/master/src/main/java/de/zalando/ep/zalenium/proxy/DockerSeleniumStarterRemoteProxy.java#L554). If something bigger than zero, then the node tries to register again.

To understand better the issue, would it be possible for you to run the tests with less threads and see some results? At the same time I will check a way to change the parameter without having side issues.

**Comment by mickfeech** [comment] 2017-10-30 13:26
@diemol - We are seeing the issues with running the default of maxTestSessions equal to 1

**Comment by diemol** [comment] 2017-10-30 13:34
Hey @mickfeech

How many tests in parallel are you running in k8s?

**Comment by mickfeech** [comment] 2017-10-30 18:48
We are typically setting MaxInstances = 10

**Comment by TomLarrow** [comment] 2017-11-07 02:19
Sorry, was out the past week, On returning the hub is showing no nodes connected, yet there were 21 pods (not counting the hub) running.  So while we tell our grid it can scale to 30, there are only 9 spots left due to these non-connected pods.

By "less threads" do you just mean the number of parallel tests, or is there another threading option I'm missing?  While most of our jobs are configured to spawn 10 concurrent tests at once, like @mickfeech said, our most common job which runs 20+ times a day only spawns 3 instances

Generally I'm seeing the non-connected pods in groups of 3-4 with the same timestamp, so I believe they are happening when it tries to start 10 tests at once, not when it runs the more common tests with 3 parallel instances

**Comment by diemol** [comment] 2017-11-10 08:31
OK, then I think that the issue is mostly related to that. The hub receives many requests and cannot register them all, and since we don't retry the registration, this healthy nodes end up being zombies.

I will look into that, first to see if there is a quick workaround, but in the long term I want to revise the registration logic (since it is now possible to overwrite this behaviour starting from the Selenium 3.7.1).

For now, perhaps the easiest way to handle it, is to restart Zalenium every now and then. 

I'll let you know in a couple of weeks how it is going.

**Comment by diemol** [comment] 2017-11-15 14:14
@TomLarrow, is it possible for you to provide us the hub logs?
#320 was created recently, and I think it might be something similar to this.

**Comment by TomLarrow** [comment] 2017-11-16 15:40
@diemol While we are seeing some pods created without services, some do still have the services, yet never connect

[zalenium0.log](https://github.com/zalando/zalenium/files/1479129/zalenium0.log)
[zalenium1.log](https://github.com/zalando/zalenium/files/1479130/zalenium1.log)

**Comment by diemol** [comment] 2017-12-10 22:26
Hi,

A release was made moments ago https://github.com/zalando/zalenium/releases/tag/3.8.1c
In this release, the nodes will try to register again whenever the initial registration was not successful, which looks like the root problem of this issue.

Could you please give it a try and report back?

In addition, a few questions:

- The dead/zombie pods, do you know what status they had? Running/Pending/Etc...
- Do you start Zalenium with zero desiredContainers always? Have you tried the `--maxTestSessions` parameter?
  - I ask because what I have seen when deploying in k8s is that creating and destroying lots of pods on the run doesn't seem to be the best use of k8s. What I mean is that in docker, creating a container is something that usually happens quickly, but in k8s this takes a bit longer, so combining `--desiredContainers` and `--maxTestSessions` kind of makes things better in k8s.

**Comment by TomLarrow** [comment] 2017-12-11 01:15
We don't have --desiredContainers or --maxTestSessions set, just maxDockerSeleniumContainers and I just threw 55 simultaneous Chrome tests at the grid.  Before this always resulted in at least 2 zombie pods, sometimes as many as 9.  Now none.  The extra tests waited pertinently in the queue until a node was available.

I repeated the test with Firefox, and again, same result. No pods that were listed in a running state that were not connected to the hub.

I'll keep testing, and watch it as we see general users use it.

I read up on --desiredContainers and --maxTestSessions some, and while it may be useful, we've stayed away from desiredContainers, simply because when we were manually using a "static" Selenium Grid were nodes stayed active for long periods of time I was constantly having to find time to restart nodes as there seemed to be memory leaks in Chrome nodes that stayed up for a couple hours and ran lots of tests.  We really liked that Zalenium spun the nodes back down after the tests complete.  I know it increases time but it was giving us a far more reliable set of results, as tests were never going to nodes, about to crash because they were consuming multiple gigs of memory

**Comment by diemol** [comment] 2017-12-11 08:19
Thanks for the quick feedback @TomLarrow!

That's good news, I hope it continues to behave like that.

I understand, if one is having Zalenium as a "permanent" grid, that's a good thing, not having to worry about node status. 

I'll keep this issue open for a few days more to see if anything else happens.

**Comment by diemol** [comment] 2017-12-13 23:47
I just closed #320 since positive feedback was given to an issue similar to this one, so I'll go ahead and close this one as well since things seem to work better now.

Please reopen in case something is not working properly.

**Closed by diemol** 2017-12-13 23:47 UTC
Labels: bug, waiting-retest
