### ISSUE TITLE
Unable to view video for failed scenarios

### ISSUE THREAD

**Issue by sunipa11** [zalando/zalenium#659] opened 2018-07-16 11:56 UTC
Hi,

Unable to view video for failed scenarios.
I executed few automated selenium tests and I was expecting that I will get video recording for failed scenarios as well but video recording was available only for passed scenarios.
Please suggest if I am missing anything.

Regards,

**Comment by diemol** [comment] 2018-07-16 11:58
Hi @sunipa11,

Could you please provide more information? There is a template available when the issue is created, please fill the data that we need there to help you, otherwise we cannot really be useful.

**Comment by diemol** [comment] 2018-07-16 16:24
Closing since the conversation moved to Slack (we are waiting for you to reply @sunipa11)

**Closed by diemol** 2018-07-16 16:24 UTC
Labels: waiting-answer
