### ISSUE TITLE
Seeing connection time out issues

### ISSUE THREAD

**Issue by pkundarapu** [zalando/zalenium#1157] opened 2020-02-14 21:02 UTC
org.openqa.selenium.remote.UnreachableBrowserException: Could not start a new session. Possible causes are invalid address of the remote server or browser start-up failure.
Build info: version: '3.141.59', revision: 'e82be7d358', time: '2018-11-14T08:17:03'
System info: host: 'MBP15-PBJGH8.local', ip: '2601:646:8a82:5a10:e45c:ab0:217:5cee%en0', os.name: 'Mac OS X', os.arch: 'x86_64', os.version: '10.14.6', java.version: '1.8.0_201'
Driver info: driver.version: Driver
        at org.openqa.selenium.remote.RemoteWebDriver.execute(RemoteWebDriver.java:573)
        at org.openqa.selenium.remote.RemoteWebDriver.startSession(RemoteWebDriver.java:213)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:131)
        at org.openqa.selenium.remote.RemoteWebDriver.<init>(RemoteWebDriver.java:144)
        at automationFramework.Driver.startWebDriver(Driver.java:80)
Caused by: java.net.ConnectException: Failed to connect to zalenium.es-use.us-east-1.acceptance.cloud.com/3.232.137.2:80
        at okhttp3.internal.connection.RealConnection.connectSocket(RealConnection.java:247)
        at okhttp3.internal.connection.RealConnection.connect(RealConnection.java:165)
        at okhttp3.internal.connection.StreamAllocation.findConnection(StreamAllocation.java:257)
        at okhttp3.internal.connection.StreamAllocation.findHealthyConnection(StreamAllocati
Caused by: java.net.ConnectException: Operation timed out (Connection timed out)
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)

I see this issue when multiple jobs are running and using same zalenium hub url.

**Comment by xMutaGenx** [comment] 2020-02-19 09:49
Same here, upgraded from 3.141.59w to 3.141.59y and now I'm seeing socket hang ups, connection refused etc.

**Comment by diemol** [comment] 2020-03-21 21:18
Sorry, I am closing this since there is no clear way to see how this could be reproduced.

**Closed by diemol** 2020-03-21 21:18 UTC
