### ISSUE TITLE
Tests fail with FORWARDING_TO_NODE_FAILED message when using elgalu images that has chrome 67 and later

### ISSUE THREAD

**Issue by remeltucker** [zalando/zalenium#722] opened 2018-09-10 02:13 UTC
**Please make sure that you provide enough information for us to help you with this issue. Thank you!**

Zalenium Image Version(s):  
3.14.0b (Issue exists with previous versions too)
Docker Version:  
Docker version 17.05.0-ce, build 89658be
If using docker-compose, version:  

OS: 
Linux
Docker Command to start Zalenium:  

docker run --rm -ti --sysctl net.ipv4.ip_forward=0 --name zalenium -p 8080:4444 -e ZALENIUM_EXTRA_JVM_PARAMS="-Dwebdriver.http.factory=apache" -v /var/run/docker.sock:/var/run/docker.sock -v /selGrid:/home/seluser/videos --privileged dosel/zalenium:latest start --sendAnonymousUsageInfo false --timeZone "America/New_York" --maxDockerSeleniumContainers 25 --seleniumImageName artifactory.cloud.***.com/selenium/selGrid:elgalu_modified

Note: Image of elgalu/selenium is modified to include ENV parameters for proxy and noProxy.Issue exists when using with versions of elgalu/selenium that had Chrome 67,68,69.

## Expected Behavior -
Expecting tests to get executed
## Actual Behavior -
Tests run for around 1.5 mins and then fails with the below message
Cannot forward the request Connect to 172.17.0.4:40001 [/172.17.0.4] failed: Connection refused (Connection refused) and Session [...] was terminated due to FORWARDING_TO_NODE_FAILED when using proxy

Below is the Zalenium started logs

[Zal_logs.txt](https://github.com/zalando/zalenium/files/2364923/Zal_logs.txt)

Note:Workaround was to use the elgalu/selenium image that had chrome 66 (eg:3.11.0-p12) as the base image and upgrade to later versions of chrome using the same.

**Comment by pearj** [comment] 2018-09-10 21:33
@remeltucker. What version of selenium are you using in your tests? Does it work if you update your selenium dependency to 3.14?

**Comment by pearj** [comment] 2018-09-10 21:39
By the way you don’t need to modify the elgalu image to add proxy details. You can do it via setting zalenium_no_proxy on the zalenium container and it will set the proxy details there. 

Search for “Adding proxy configuration to the containers” on https://opensource.zalando.com/zalenium/

**Comment by diemol** [comment] 2018-09-13 07:49
@remeltucker can you please show us how the proxies are set up?

**Comment by pearj** [comment] 2018-09-16 13:31
You probably would want to ask that question at https://github.com/elgalu/docker-selenium

I’m not super familiar with the docker-selenium side.

**Comment by WarleyGabriel** [comment] 2018-10-19 17:03
Hi all,
I got this situation.
```
16:40:45.569 [Terminate Test Session int id: [33cc1a45-8fb8-419d-bc3b-edb75325adee] ext id: [a25b7e11-fe78-4580-9b6b-6bbb4247896f] container: [96c6fa90d187fc5255480421d7dad0c42c8fcf339df02181ff6a5988d7e66f94]] ERROR d.z.e.z.p.DockerSeleniumRemoteProxy - 96c6fa90d187fc5255480421d7dad0c42c8fcf339df02181ff6a5988d7e66f94java.lang.NullPointerException
java.lang.NullPointerException: null
16:40:55.576 [Terminate Test Session int id: [33cc1a45-8fb8-419d-bc3b-edb75325adee] ext id: [a25b7e11-fe78-4580-9b6b-6bbb4247896f] container: [96c6fa90d187fc5255480421d7dad0c42c8fcf339df02181ff6a5988d7e66f94]] WARN  d.z.e.z.c.DockerContainerClient - http://172.18.0.6:40003 Something happened while copying the folder /var/log/cont/, most of the time it is an issue while closing the input/output stream, which is usually OK.
com.spotify.docker.client.exceptions.DockerTimeoutException: Timeout: GET unix://localhost:80/version
	at com.spotify.docker.client.DefaultDockerClient.propagate(DefaultDockerClient.java:2823)
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:2692)
	at com.spotify.docker.client.DefaultDockerClient.version(DefaultDockerClient.java:580)
	at com.spotify.docker.client.DefaultDockerClient.archiveContainer(DefaultDockerClient.java:960)
	at de.zalando.ep.zalenium.container.DockerContainerClient.copyFiles(DockerContainerClient.java:183)
	at de.zalando.ep.zalenium.proxy.DockerSeleniumRemoteProxy.copyLogs(DockerSeleniumRemoteProxy.java:626)
	at de.zalando.ep.zalenium.proxy.DockerSeleniumRemoteProxy.processContainerAction(DockerSeleniumRemoteProxy.java:566)
	at de.zalando.ep.zalenium.proxy.DockerSeleniumRemoteProxy.processContainerAction(DockerSeleniumRemoteProxy.java:552)
	at de.zalando.ep.zalenium.proxy.DockerSeleniumRemoteProxy.cleanupNode(DockerSeleniumRemoteProxy.java:706)
	at de.zalando.ep.zalenium.proxy.DockerSeleniumRemoteProxy.afterSession(DockerSeleniumRemoteProxy.java:356)
	at org.openqa.grid.internal.TestSlot.performAfterSessionEvent(TestSlot.java:253)
	at de.zalando.ep.zalenium.registry.ZaleniumRegistry._release(ZaleniumRegistry.java:194)
	at de.zalando.ep.zalenium.registry.ZaleniumRegistry.lambda$0(ZaleniumRegistry.java:178)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.util.concurrent.ExecutionException: javax.ws.rs.ProcessingException: org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
	at jersey.repackaged.com.google.common.util.concurrent.AbstractFuture$Sync.getValue(AbstractFuture.java:299)
	at jersey.repackaged.com.google.common.util.concurrent.AbstractFuture$Sync.get(AbstractFuture.java:286)
	at jersey.repackaged.com.google.common.util.concurrent.AbstractFuture.get(AbstractFuture.java:116)
	at com.spotify.docker.client.DefaultDockerClient.request(DefaultDockerClient.java:2690)
	... 12 common frames omitted
Caused by: javax.ws.rs.ProcessingException: org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:481)
	at org.glassfish.jersey.apache.connector.ApacheConnector$1.run(ApacheConnector.java:491)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at jersey.repackaged.com.google.common.util.concurrent.MoreExecutors$DirectExecutorService.execute(MoreExecutors.java:299)
	at java.util.concurrent.AbstractExecutorService.submit(AbstractExecutorService.java:112)
	at jersey.repackaged.com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:50)
	at jersey.repackaged.com.google.common.util.concurrent.AbstractListeningExecutorService.submit(AbstractListeningExecutorService.java:37)
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:487)
	at org.glassfish.jersey.client.ClientRuntime$2.run(ClientRuntime.java:178)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:271)
	at org.glassfish.jersey.internal.Errors$1.call(Errors.java:267)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:315)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:297)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:267)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:340)
	at org.glassfish.jersey.client.ClientRuntime$3.run(ClientRuntime.java:210)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	... 1 common frames omitted
Caused by: org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager.leaseConnection(PoolingHttpClientConnectionManager.java:313)
	at org.apache.http.impl.conn.PoolingHttpClientConnectionManager$1.get(PoolingHttpClientConnectionManager.java:279)
	at org.apache.http.impl.execchain.MainClientExec.execute(MainClientExec.java:191)
	at org.apache.http.impl.execchain.ProtocolExec.execute(ProtocolExec.java:185)
	at org.apache.http.impl.execchain.RetryExec.execute(RetryExec.java:89)
	at org.apache.http.impl.execchain.RedirectExec.execute(RedirectExec.java:111)
	at org.apache.http.impl.client.InternalHttpClient.doExecute(InternalHttpClient.java:185)
	at org.apache.http.impl.client.CloseableHttpClient.execute(CloseableHttpClient.java:72)
	at org.glassfish.jersey.apache.connector.ApacheConnector.apply(ApacheConnector.java:435)
	... 21 common frames omitted
```
I started my server with these parameters.
```
version: "2.0"
services:
  zalenium:
    image: dosel/zalenium
    container_name: zalenium
    privileged: true
    tty: true
    environment:
      - "ZALENIUM_EXTRA_JVM_PARAMS=-Dwebdriver.http.factory=apache"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
      - "./videos:/home/seluser/videos"
    ports:
      - "4444:4444"
    command: >
      start --timeZone ${TIMEZONE}
            --screenWidth ${SCREENWIDTH} --screenHeight ${SCREENHEIGHT}
            --maxTestSessions ${MAXTESTSESSIONS}
            --desiredContainers ${CONTAINERS}
            --videoRecordingEnabled ${VIDEORECORDINGENABLE}
```

Can you help me?
Thank you!

**Comment by diemol** [comment] 2018-10-25 11:12
Closing this one as it is a duplicate of https://github.com/elgalu/docker-selenium/issues/266

@WarleyGabriel your issue seems unrelated to this one. Please open a new one with detailed steps showing how to reproduce it.

**Closed by diemol** 2018-10-25 11:12 UTC
Labels: waiting-answer
