### ISSUE TITLE
Container stuck in 'Terminating' status

### ISSUE THREAD

**Issue by axozoid** [zalando/zalenium#1010] opened 2019-07-17 07:12 UTC
## 🐛 Bug Report

I noticed that sometimes there are containers stuck in `Terminating` status, like this:

```
NAME                             READY   STATUS               RESTARTS   AGE
zalenium-40000-67nl5             0/1     Terminating          0          3h
```

That's what I can see in logs for that container:

```--LOG 03:41:34:262364317 Kubernetes service account found.
--LOG 03:41:34:333224477 Stopping supervisord to support docker restart...
-- INFO: Docker Img. Version: 3.141.59-310
-- INFO: Chrome..... Version: 74.0.3729.169
-- INFO: Firefox.... Version: 67.0
-- INFO: Using Selenium.....: 3.141.59
supervisord --version=4.0.0.dev0
2019-07-17 03:41:35,419 INFO Included extra file "/etc/supervisor/conf.d/novnc.conf" during parsing
2019-07-17 03:41:35,419 INFO Included extra file "/etc/supervisor/conf.d/selenium-hub.conf" during parsing
2019-07-17 03:41:35,419 INFO Included extra file "/etc/supervisor/conf.d/selenium-multinode.conf" during parsing
2019-07-17 03:41:35,419 INFO Included extra file "/etc/supervisor/conf.d/selenium-node-chrome.conf" during parsing
2019-07-17 03:41:35,419 INFO Included extra file "/etc/supervisor/conf.d/selenium-node-firefox.conf" during parsing
2019-07-17 03:41:35,419 INFO Included extra file "/etc/supervisor/conf.d/video-rec.conf" during parsing
2019-07-17 03:41:35,419 INFO Included extra file "/etc/supervisor/conf.d/vnc.conf" during parsing
2019-07-17 03:41:35,419 INFO Included extra file "/etc/supervisor/conf.d/xmanager.conf" during parsing
2019-07-17 03:41:35,419 INFO Included extra file "/etc/supervisor/conf.d/xterm.conf" during parsing
2019-07-17 03:41:35,430 INFO RPC interface 'supervisor' initialized
2019-07-17 03:41:35,431 INFO RPC interface 'supervisor' initialized
2019-07-17 03:41:35,431 INFO supervisord started with pid 169
2019-07-17 03:41:36,433 INFO spawned: 'xmanager' with pid 172
2019-07-17 03:41:36,434 INFO spawned: 'vnc' with pid 173
2019-07-17 03:41:36,436 INFO spawned: 'novnc' with pid 174
2019-07-17 03:41:36,437 INFO spawned: 'selenium-multinode' with pid 175
2019-07-17 03:41:36,439 INFO spawned: 'xterm' with pid 176
2019-07-17 03:41:36,479 INFO success: xterm entered RUNNING state, process has stayed up for > than 0 seconds (startsecs)
2019-07-17 03:41:38,609 INFO success: xmanager entered RUNNING state, process has stayed up for > than 2 seconds (startsecs)
2019-07-17 03:41:38,609 INFO success: vnc entered RUNNING state, process has stayed up for > than 2 seconds (startsecs)
2019-07-17 03:41:38,609 INFO success: novnc entered RUNNING state, process has stayed up for > than 2 seconds (startsecs)
2019-07-17 03:41:40,326 INFO success: selenium-multinode entered RUNNING state, process has stayed up for > than 3 seconds (startsecs)
Trapped SIGTERM/SIGINT/x so shutting down supervisord gracefully...
2019-07-17 03:42:32,243 INFO waiting for xmanager to stop
2019-07-17 03:42:32,243 INFO waiting for vnc to stop
2019-07-17 03:42:32,243 INFO waiting for novnc to stop
2019-07-17 03:42:32,243 INFO waiting for selenium-multinode to stop
2019-07-17 03:42:32,243 INFO waiting for xterm to stop
2019-07-17 03:42:32,244 INFO stopped: xmanager (exit status 0)
2019-07-17 03:42:32,244 INFO stopped: novnc (terminated by SIGTERM)
2019-07-17 03:42:32,248 INFO stopped: vnc (exit status 0)
2019-07-17 03:42:32,252 INFO stopped: selenium-multinode (exit status 137)
2019-07-17 03:42:33,476 WARN received SIGTERM indicating exit request
2019-07-17 03:42:33,476 INFO waiting for xterm to die
2019-07-17 03:42:34,477 INFO stopped: xterm (exit status 150)
```
And the pod has been stayed in that state for more than 20min. 

## To Reproduce

Not sure how to reproduce.

## Expected behavior

A pod get terminated and recreated.

## Environment

Zalenium Image Version(s): zalenium:3.141.59
Kubernetes: v1.10.13

nodeInfo:
    architecture: amd64
    containerRuntimeVersion: docker://17.3.2
    kernelVersion: 4.9.0-7-amd64
    kubeProxyVersion: v1.10.13
    kubeletVersion: v1.10.13
    operatingSystem: linux
    osImage: Debian GNU/Linux 9 (stretch)

**Comment by axozoid** [comment] 2019-07-18 00:04
that's what you can see when you do `describe pod`:

```
Name:                      zalenium-40000-67nl5
Namespace:                 XXXXXXXXXXX
Node:                      ip-10-44-3-66.ap-southeast-2.compute.internal/10.44.3.66
Start Time:                Wed, 17 Jul 2019 13:41:20 +1000
Labels:                    app=zalenium
                           createdBy=zalenium
Annotations:               <none>
Status:                    Terminating (lasts 20h)
Termination Grace Period:  30s
IP:                        100.96.140.244
Containers:
  selenium-node:
    Container ID:   docker://b377da19cc0b022b7a680dd97341f16605c7efcc0105cd25e9835788e194ac5f
    Image:          elgalu/selenium:3.141.59-p14
    Image ID:       docker-pullable://elgalu/selenium@sha256:e9b48760be1febe6ab52b62b475d5f7fb2532139b39596782ca0a31e79a59419
    Port:           <none>
    Host Port:      <none>
    State:          Running
      Started:      Wed, 17 Jul 2019 13:41:34 +1000
    Ready:          False
    Restart Count:  0
    Limits:
      cpu:     2
      memory:  2Gi
    Requests:
      cpu:      50m
      memory:   200Mi
    Readiness:  exec [/bin/sh -c http_proxy="" curl -s http://`getent hosts ${HOSTNAME} | awk '{ print $1 }'`:40000/wd/hub/status | jq .value.ready | grep true] delay=5s timeout=5s period=1s #success=1 #failure=60
    Environment:
      SEL_NODEPOLLING_MS:            100000
      SELENIUM_HUB_HOST:             100.96.134.183
      TZ:                            UTC
      NOVNC_PORT:                    50000
      CHROME:                        false
      SELENIUM_MULTINODE_PORT:       40000
      WAIT_TIME_OUT_VIDEO_STOP:      20s
      FIREFOX:                       false
      SCREEN_HEIGHT:                 1440
      WAIT_TIMEOUT:                  120s
      SEL_BROWSER_TIMEOUT_SECS:      16000
      SCREEN_WIDTH:                  2560
      NOVNC:                         true
      SELENIUM_NODE_PARAMS:          
      SEND_ANONYMOUS_USAGE_INFO:     false
      GRID:                          false
      MULTINODE:                     true
      VIDEO_STOP_SLEEP_SECS:         1
      SELENIUM_NODE_REGISTER_CYCLE:  75000
      ZALENIUM:                      true
      SELENIUM_NODE_HOST:            0.0.0.0
      PICK_ALL_RANDOM_PORTS:         false
      BUILD_URL:                     
      VNC_PORT:                      60000
      SELENIUM_HUB_PORT:             4445
      SELENIUM_NODE_PROXY_PARAMS:    de.zalando.ep.zalenium.proxy.DockerSeleniumRemoteProxy
    Mounts:
      /dev/shm from dshm (rw)
      /tmp/mounted from zalpr-zalenium-data (rw)
      /var/run/secrets/kubernetes.io/serviceaccount from zalpr-zalenium-token-kwt9g (ro)
Conditions:
  Type           Status
  Initialized    True 
  Ready          False 
  PodScheduled   True 
Volumes:
  dshm:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     Memory
    SizeLimit:  <unset>
  zalpr-zalenium-data:
    Type:       EmptyDir (a temporary directory that shares a pod's lifetime)
    Medium:     
    SizeLimit:  <unset>
  zalpr-zalenium-token-kwt9g:
    Type:        Secret (a volume populated by a Secret)
    SecretName:  zalpr-zalenium-token-kwt9g
    Optional:    false
QoS Class:       Burstable
Node-Selectors:  <none>
Tolerations:     dedicated=zalenium:NoSchedule
                 node.kubernetes.io/not-ready:NoExecute for 300s
                 node.kubernetes.io/unreachable:NoExecute for 300s
Events:
  Type    Reason   Age                  From                                                    Message
  ----    ------   ----                 ----                                                    -------
  Normal  Killing  50s (x636 over 20h)  kubelet, ip-10-44-3-66.ap-southeast-2.compute.internal  Killing container with id docker://selenium-node:Need to kill Pod

```

**Comment by axozoid** [comment] 2019-07-22 06:41
@diemol / @arnaud-deprez  do you guys have any ideas?

**Comment by arnaud-deprez** [comment] 2019-07-23 13:59
Hi @axozoid, 

This can be due to a lot of things as you can see https://github.com/kubernetes/kubernetes/issues/51835 and https://github.com/kubernetes/kubernetes/issues/65569.

It is generally due to network, storage or node memory issue. I think we can eliminate storage as you are using `emptyDir` volume.
You can have more details in kubelet logs.

I also know there was also some issue regarding pod stuck in `Terminating` state in kubernetes 1.10.x but I don't remember where.

**Comment by pearj** [comment] 2019-08-18 10:56
Were you able to force delete the pod in the end?

If you can't even force delete pods, then I found some of the other approaches in this article could delete them: https://medium.com/techbeatly/how-to-delete-a-pod-with-terminating-state-in-openshift-or-kubernetes-cluster-4eac2ab89fe0
My issue was on an OpenShift 3.9 cluster, it wasn't with Zalenium pods, but the same issue, pods stuck in terminating for a long time (multiple hours in my case).

Regardless, this is an issue with your Kubernetes cluster and not Zalenium I believe. Are you happy for this to be closed?

**Comment by arnaud-deprez** [comment] 2019-09-05 10:42
Thanks @pearj, 

@axozoid I believe that's what our infra team was doing as a workaround but I couldn't find back the link ! :-)

**Comment by JRemitz** [comment] 2019-09-10 03:52
I was seeing this same issue. Updating values for:
```yaml
hub:
  containerSecurityContext:
    privileged: true
```
Seems to have been the fix for me. At least things are a lot more stable now.  I changed it based on the explanation for `--privileged` in the [README](https://github.com/zalando/zalenium#run-it).

**Comment by nischay30** [comment] 2019-09-30 08:35
Is there any update on this issue?

**Comment by Revellski** [comment] 2019-11-18 14:54
> I was seeing this same issue. Updating values for:
> 
> ```yaml
> hub:
>   containerSecurityContext:
>     privileged: true
> ```
> 
> Seems to have been the fix for me. At least things are a lot more stable now. I changed it based on the explanation for `--privileged` in the [README](https://github.com/zalando/zalenium#run-it).

This may have something to do with local ulimits, thus running as privileged is seen as a workaround. Could anyone confirm their config?

**Comment by axozoid** [comment] 2019-11-19 05:00
HI @pearj @arnaud-deprez  thanks for your reply! Somehow I missed this thread..

Deleting pods forcefully helps, however my initial question was kinda 'why it's happening' and if there was a fix needed from Zalenium side. 

Right now we are running K8s `1.12.10` and I can observe this picture when do `kubectl get pods`:

```
NAME                             READY   STATUS      RESTARTS   AGE
zalenium-40000-kxlf6             0/1     Completed   0          21h
zalenium-40000-lmh4r             0/1     Completed   0          24h
zalenium-40000-n6fl8             0/1     Completed   0          4d2h
zalenium-40000-s9gvq             1/1     Running     0          4h58m
zalenium-40000-zvvsk             1/1     Running     0          2d7h
zalpr-zalenium-679575755-gpxbq   1/1     Running     0          6d4h
```

**Comment by Revellski** [comment] 2019-11-19 08:40
@axozoid we ran into the exact same issues. I've ended upgrading K8s to v1.16.2 but the issue still surfaces after a few days. This may have been caused by poorly sized ulimits. @JRemitz comment is pointing in the same direction.

**Comment by diemol** [comment] 2019-12-09 16:47
Thank you all for your comments, it just seems that it points out to resource allocation or Kubernetes configuration.
If anyone feels that this is a bug in Zalenium, please send us a PR and I will be happy to review it and merge it.

For now, since there is no clear way to see if this is a Zalenium issue, I will close it. Again, feel free to comment and if needed, we can reopen.

**Closed by diemol** 2019-12-09 16:47 UTC

**Comment by ilhaan** [comment] 2021-06-24 20:56
@diemol I am seeing this happen in one of my two Zalenium deployments. The only difference between the two deployments are `desiredContainers` and `maxDockerSeleniumContainers` values: 

* dev install (no issue): 
```
desiredContainers: 8
maxDockerSeleniumContainers: 10
```
* prod install (pods stuck in "Terminating" after completing test): 
```
desiredContainers: 50
maxDockerSeleniumContainers: 100
```

I tried the `containerSecurityContext` config mentioned [above](https://github.com/zalando/zalenium/issues/1010#issuecomment-529757633) and that didn't work. 

Running `kubectl describe pod` against one of pods stuck in "Terminating" status shows this message: 
```
Readiness probe failed: OCI runtime exec failed: exec failed: container_linux.go:349: starting container process caused "process_linux.go:101: executing setns process caused \"exit status 1\"": unknown
```

Please let me know if there is something else I can dig into to figure out why this is happening.
