### ISSUE TITLE
Dashboard breaks when video persistent volume is enabled

### ISSUE THREAD

**Issue by gerrit8143** [zalando/zalenium#926] opened 2019-04-05 08:42 UTC
## 🐛 Bug Report

Dashboard returns 403 Forbidden when video persistent volume is enabled in zalenium helm chart.

## To Reproduce

Deploy zalenium helm chart to Kubernetes with video persistent volume enabled.

## Expected behavior

persistent volume is mounted and dashboard still works.

## Test script reproducing this issue (when applicable)
1. i pulled the master
2. cd zalenium/charts/zalenium
3. helm install --name my-release --namespace my-zalenium . --set persistence.video.enabled=true

log output is:

```
Kubernetes service account found.
Copying files for Dashboard...
cp: cannot create regular file '/home/seluser/videos/dashboard.html': Permission denied
cp: cannot create directory '/home/seluser/videos/css': Permission denied
cp: cannot create directory '/home/seluser/videos/js': Permission denied
cp: cannot create directory '/home/seluser/videos/img': Permission denied
Starting Nginx reverse proxy...
Starting Selenium Hub...
...08:29:49.170 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Selenium server version: 3.141.59, revision: unknown
08:29:49.249 [main] INFO  o.o.grid.selenium.GridLauncherV3 - Launching Selenium Grid hub on port 4445
.08:29:49.503 [main] INFO  d.z.e.z.c.k.KubernetesContainerClient - Initialising Kubernetes support
..08:29:49.911 [main] INFO  d.z.e.z.c.k.KubernetesContainerClient - Kubernetes support initialised.
	Pod name: my-release-zalenium-fd989c89d-sd2bc
	app label: zalenium
	zalenium service name: zalenium
	Selenium Pod Resource Limits: {memory=Quantity(amount=2Gi, format=null, additionalProperties={}), cpu=Quantity(amount=1000m, format=null, additionalProperties={})}
	Selenium Pod Resource Requests: {memory=Quantity(amount=500Mi, format=null, additionalProperties={}), cpu=Quantity(amount=250m, format=null, additionalProperties={})}
08:29:49.911 [main] INFO  d.z.e.z.c.k.KubernetesContainerClient - About to clean up any left over docker-selenium pods created by Zalenium
.08:29:49.975 [AutoStartProxyPoolPoller] INFO  d.z.e.z.proxy.AutoStartProxySet - Starting poller.
..08:29:50.358 [main] INFO  d.z.ep.zalenium.aspect.HubAspect - Registering custom Zalenium servlets
08:29:50.433 [main] INFO  org.openqa.grid.web.Hub - Selenium Grid hub is up and running
08:29:50.433 [main] INFO  org.openqa.grid.web.Hub - Nodes should register to http://100.96.34.104:4445/grid/register/
08:29:50.433 [main] INFO  org.openqa.grid.web.Hub - Clients should connect to http://100.96.34.104:4445/wd/hub
Selenium Hub started!
Sauce Labs not enabled...
Browser Stack not enabled...
TestingBot not enabled...
Zalenium is now ready!
*************************************** Data Processing Agreement ***************************************
By using this software you agree that the following non-PII (non personally identifiable information)
data will be collected, processed and used by Zalando SE for the purpose of improving our test
infrastructure tools. Anonymisation with respect of the IP address means that only the first two octets
of the IP address are collected.

See the complete license at https://github.com/zalando/zalenium/blob/master/LICENSE.md
*************************************** Data Processing Agreement ***************************************
08:29:58.259 [Thread-10] INFO  d.z.e.z.registry.ZaleniumRegistry - Registered a node http://100.96.42.94:40000
08:29:58.314 [Thread-11] INFO  d.z.e.z.registry.ZaleniumRegistry - Registered a node http://100.96.88.80:40000

```

looks like the copying of the dashboard files to /home/seluser/videos fails (permission denied) and as a result /home/seluser/videos is empty.

strange thing is that the permissions are ok if i enter the pod with kubectl exec and copying the files manually is no problem:

```
➜  ~ kubectl exec my-release-zalenium-fd989c89d-sd2bc -ti /bin/bash                                                                                                                                                                    
seluser@my-release-zalenium-fd989c89d-sd2bc:~$ ls -l
total 39676
-rwxrw-r--. 1 seluser seluser     4529 Mar 30 08:57 Analytics.md
drwxrwxr-x. 1 seluser seluser     4096 Mar 30 08:59 css
-rwxrw-r--. 1 seluser seluser    10996 Mar 30 08:57 dashboard_template.html
drwxrwxr-x. 1 seluser seluser     4096 Mar 30 08:59 img
drwxrwxr-x. 1 seluser seluser     4096 Mar 30 08:59 js
-rwxrw-r--. 1 seluser seluser     2128 Mar 30 08:57 LICENSE.md
-rwxrw-r--. 1 seluser seluser     1082 Mar 30 08:57 logback.xml
-rwxrw-r--. 1 seluser seluser     2738 Mar 30 08:57 logging_debug.properties
-rwxrw-r--. 1 seluser seluser     2699 Mar 30 08:57 logging_info.properties
drwxr-xr-x. 2 seluser seluser     4096 Apr  5 08:29 logs
-rwxrw-r--. 1 seluser seluser     2593 Apr  5 08:29 nginx.conf
-rwxrw-r--. 1 seluser seluser     2758 Mar 30 08:57 nginx.conf.bak
-rwxrwxr-x. 1 seluser seluser     1287 Mar 30 08:57 start-browserstack.sh
-rwxrwxr-x. 1 seluser seluser     2679 Mar 30 08:57 start-saucelabs.sh
-rwxrwxr-x. 1 seluser seluser     1268 Mar 30 08:57 start-testingbot.sh
drwxr-xr-x. 3 seluser seluser     4096 Apr  5 08:29 videos
-rwxrwxr-x. 1 seluser seluser      831 Mar 30 08:57 wait-browserstack.sh
-rwxrwxr-x. 1 seluser seluser      983 Mar 30 08:57 wait-saucelabs.sh
-rwxrwxr-x. 1 seluser seluser      770 Mar 30 08:57 wait-testingbot.sh
-rwxrw-r--. 1 seluser seluser    15086 Mar 30 08:57 zalando.ico
-rw-rw-r--. 1 seluser seluser 40395884 Mar 30 08:57 zalenium-3.141.59j.jar
-rwxrwxr-x. 1 seluser seluser    33692 Mar 30 08:57 zalenium.sh
seluser@my-release-zalenium-fd989c89d-sd2bc:~$ cp /home/seluser/dashboard_template.html /home/seluser/videos/dashboard.html
seluser@my-release-zalenium-fd989c89d-sd2bc:~$ cp -r /home/seluser/css /home/seluser/videos
seluser@my-release-zalenium-fd989c89d-sd2bc:~$ cp -r /home/seluser/js /home/seluser/videos
seluser@my-release-zalenium-fd989c89d-sd2bc:~$ cp -r /home/seluser/img /home/seluser/videos
seluser@my-release-zalenium-fd989c89d-sd2bc:~$ ls -l videos/
total 40
drwxr-xr-x. 2 seluser seluser  4096 Apr  5 08:39 css
-rwxr--r--. 1 seluser seluser 10996 Apr  5 08:39 dashboard.html
drwxr-xr-x. 2 seluser seluser  4096 Apr  5 08:39 img
drwxr-xr-x. 2 seluser seluser  4096 Apr  5 08:39 js
drwx------. 2 seluser seluser 16384 Apr  5 08:29 lost+found
seluser@my-release-zalenium-fd989c89d-sd2bc:~$

```

## Environment

OS: Container Linux by CoreOS stable (2023.5.0)
Zalenium Image Version(s): 3.141.59j
Docker version: 18.06.1-ce
Docker-Compose version (if applicable):
If using Kubernetes, specify your environment, and if relevant your manifests:
Kubernetes v1.11.8 installed with kops on AWS

**Comment by baflQA** [comment] 2019-04-18 07:26
Looks like I'm experiencing the same(similar) issue when resetting the dashboard. Once Reset is performed, 403 is returned when trying to open the dashboard.

**Comment by diemol** [comment] 2019-05-02 12:58
I'll close this one as a duplicate of #901, which has a fix already and will be released soon. Please reopen in case it does not fix it after the release.

**Closed by diemol** 2019-05-02 12:58 UTC

**Comment by tegataiprime** [comment] 2020-03-11 19:05
I don't think this is a duplicate.  I get the same error when deploying to AWS EKS and using an EBS Volume to store video data via a persistent volume claim.

My storage class:
```yaml
kind: StorageClass
apiVersion: storage.k8s.io/v1
metadata:
  name: standard
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
provisioner: kubernetes.io/aws-ebs
parameters:
  type: gp2
  zones: us-east-1a, us-east-1b, us-east-1c
  encrypted: "true"
```

From my values-test.yaml file:
```yaml
persistence:
  video:
    enabled: true
    storageClass: standard
```

From the top of the log file:
```
Kubernetes service account found.
Copying files for Dashboard...
cp: cannot create regular file '/home/seluser/videos/dashboard.html': Permission denied
cp: cannot create directory '/home/seluser/videos/css': Permission denied
cp: cannot create directory '/home/seluser/videos/js': Permission denied
cp: cannot create directory '/home/seluser/videos/img': Permission denied
```

**Comment by pearj** [comment] 2020-03-19 12:23
@tegataiprime your problem sounds like you need to set the podSecurityContext to make sure you PVC is mounted with the correct permissions. 

Have a look at https://github.com/zalando/zalenium/blob/master/charts/zalenium/values.yaml

**Comment by tegataiprime** [comment] 2020-03-20 12:06
@pearj Yup!  That did the trick.  Many thanks :)
